content/rs/clusters/new-cluster-setup.md

Fix broken link to Create a new database
DOC-1453

DOC-1453 broken link

---

content/kubernetes/re-clusters/upgrade-redis-cluster.md

Staging link: https://docs.redis.com/staging/jira-doc-1458/kubernetes/re-clusters/upgrade-redis-cluster/

DOC-1458: "Copy to clipboard" scrolls with text in code snippet

---

content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md

[Staged preview](https://docs.redis.com/staging/bloom-release-notes/modules/redisbloom/release-notes/redisbloom-2.2-release-notes/)

Added RedisBloom v2.2.17 release notes

---

content/kubernetes/re-clusters/delete_custom_resources.md

Fix minor typo in REC CR troubleshooting docs

---

content/glossary/_index.md
content/kubernetes/deployment/quick-start.md
content/kubernetes/re-clusters/cluster-recovery.md
content/rs/administering/designing-production/persistent-ephemeral-storage.md
content/rs/databases/active-active/develop/hyperloglog-active-active.md
content/rs/installing-upgrading/get-started-redis-enterprise-software.md
content/rs/logging/_index.md
content/rs/logging/log-security.md
content/rs/logging/redis-slow-log.md
content/rs/logging/rsyslog-logging/_index.md
content/rs/logging/rsyslog-logging/bdb-events.md
content/rs/logging/rsyslog-logging/cluster-events.md
content/rs/logging/rsyslog-logging/node-events.md
content/rs/logging/rsyslog-logging/user-events.md
content/rs/security/_index.md
content/rs/security/logging.md
content/rs/security/tls/enable-tls.md

Jira: DOC-1419
Staged preview: https://docs.redis.com/staging/jira-doc-1419/rs/logging/

RS reorg: Logging section DOC-1419

---

content/kubernetes/re-clusters/create-aa-database.md

Jira: DOC-1473
Staging: https://docs.redis.com/staging/jira-doc-1473/kubernetes/re-clusters/create-aa-database/

K8s: crdb-cli example fix DOC-1473

---

content/modules/redisearch/redisearch-active-active.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1505/modules/redisearch/redisearch-active-active/)

A-A RediSearch: fixed broken link, fixed typos, copy edits

---

content/modules/modules-quickstart.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1494/modules/modules-quickstart/#try-modules)

Small updates to main module quick start

---

content/modules/redisearch/_index.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1507/modules/redisearch/)
Fixed links:
- [Natural languages for stemming](https://docs.redis.com/staging/jira-doc-1507/modules/redisearch/#:~:text=over%2015%20natural%20languages%20for%20stemming)
- [Interactive search suggestions](https://docs.redis.com/staging/jira-doc-1507/modules/redisearch/#:~:text=real%2Dtime%20interactive%20search%20suggestions.)

Fixed RediSearch links

---

content/modules/redisearch/_index.md
content/modules/redisearch/commands.md
content/modules/redisearch/redisearch-quickstart.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1487/modules/redisearch/commands/)

Added RediSearch commands page

---

content/kubernetes/re-clusters/create-aa-database.md
content/kubernetes/re-databases/ingress_routing_with_istio.md
content/kubernetes/re-databases/routes.md
content/kubernetes/re-databases/set-up-ingress-controller.md

Staging: https://docs.redis.com/staging/jira-doc-883/kubernetes/re-databases/routes/
Jira: DOC-883

K8s: OpenShift routes article DOC-883

---

content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md

[Staged preview](https://docs.redis.com/staging/gears-release-notes/modules/redisgears/release-notes/redisgears-1.2-release-notes/)

Added RedisGears v1.2.5 release notes

---

content/rc/security/encryption-at-rest.md

Removed outdated documentation regarding encryption of persistence in AWS to fit current UI.

Removed outdated documentation to fit current UI

---

content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md

Added a note to v2.8.12

---

content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md

[Staged preview](https://docs.redis.com/staging/json-release-notes/modules/redisjson/release-notes/redisjson-2.0-release-notes/)

Added RedisJSON v2.0.11 release notes

---

content/rc/subscriptions/_index.md

https://redislabs.atlassian.net/browse/DOC-1532
Updated manage subscriptions table to include ranges, this should more accurately reflect the differences between each subscription plan.

Added ranges to RC manage subscriptions table

---

content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md

[Staged preview](https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)

Added RediSearch v2.4.11 release notes

---

content/rs/monitoring-metrics/prometheus-integration.md

Fixed links so that the url is not visible on the page

Fixed links on Prometheus integration

---

content/modules/redisjson/_index.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1539/modules/redisjson/)

Updated RedisJSON overview

---

content/rs/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1525/rs/

DOC-1525: Create RS landing page

---

content/rc/_index.md
content/rs/_index.md

https://docs.redis.com/staging/preview-doc-entries/rs/
https://docs.redis.com/staging/preview-doc-entries/rc/

RC and RS Landing Pages

---

content/rc/subscriptions/create-fixed-subscription.md

These connection limits match the cloud pricing page https://redis.com/redis-enterprise-cloud/pricing/

Update new connection limits

---

content/rs/release-notes/rs-6-2-10-february-2022.md

These limitations were described in 6.2.8 release notes

Add a reference to RHEL 8 known limitations

---

content/rs/references/rest-api/requests/crdbs/_index.md
content/rs/references/rest-api/requests/crdbs/flush.md

Staging link: https://docs.redis.com/latest/rs/references/rest-api/requests/crdbs/

DOC-1476: Update /crdbs/ endpoint

---

content/rs/references/rest-api/requests/bdbs/actions/backup_reset_status.md
content/rs/references/rest-api/requests/bdbs/actions/export.md
content/rs/references/rest-api/requests/bdbs/actions/export_reset_status.md
content/rs/references/rest-api/requests/bdbs/actions/import.md
content/rs/references/rest-api/requests/bdbs/actions/import_reset_status.md
content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md

Staging link: https://docs.redis.com/staging/jira-doc-1477/rs/references/rest-api/requests/bdbs/actions/

DOC-1477: Update bdbs/actions endpoints

---

content/rs/references/rest-api/requests/bdbs/peer_stats.md
content/rs/references/rest-api/requests/bdbs/stats/_index.md
content/rs/references/rest-api/requests/bdbs/stats/last.md
content/rs/references/rest-api/requests/bdbs/sync_source_stats.md

Staging links:
https://docs.redis.com/staging/jira-doc-1514/rs/references/rest-api/requests/bdbs/stats/
https://docs.redis.com/staging/jira-doc-1514/rs/references/rest-api/requests/bdbs/peer_stats/
https://docs.redis.com/staging/jira-doc-1514/rs/references/rest-api/requests/bdbs/sync_source_stats/

DOC-1514: Update /bdbs/stats pages

---

content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md

Reverts RedisLabs/redislabs-docs#2073

Revert "Change RedisJSON v2.2 release notes to a draft"

---

content/modules/redisjson/active-active.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1448/modules/redisjson/active-active/)

Added A-A JSON design link

---

content/modules/enterprise-capabilities.md
content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md

[Staged preview](https://docs.redis.com/staging/json-release-notes/modules/redisjson/release-notes/redisjson-2.2-release-notes/)

Changed RedisJSON v2.2 to preview release

---

content/rs/monitoring-metrics/prometheus-integration.md

https://redislabs.atlassian.net/browse/DOC-1550

Added common use cases for Prometheus and Grafana together with RS

---

content/modules/redis-stack.md

Redis Stack is an OSS delivery vehicle.  So, this page describes the relationship between Stack and Enterprise.

change title from "on" to "and"

---

content/rs/references/rest-api/requests/roles/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1480/rs/references/rest-api/requests/roles/

DOC-1480: Update /roles/ page

---

content/rs/release-notes/rs-6-2-12.md

RS: Update release note links

---

content/modules/redisbloom/_index.md
content/modules/redisbloom/commands.md
content/modules/redisbloom/redisbloom-quickstart.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1491/modules/redisbloom/commands)

Added RedisBloom commands table

---

content/modules/redisgraph/_index.md
content/modules/redisgraph/commands.md
content/modules/redisgraph/redisgraph-quickstart.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1489/modules/redisgraph/commands/)

Added RedisGraph command table

---

content/modules/redistimeseries/_index.md
content/modules/redistimeseries/commands.md
content/modules/redistimeseries/redistimeseries-quickstart.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1490/modules/redistimeseries/commands/)

Added RedisTimeSeries command table

---

content/rs/references/rest-api/requests/nodes/_index.md
content/rs/references/rest-api/requests/nodes/actions.md
content/rs/references/rest-api/requests/nodes/stats/_index.md
content/rs/references/rest-api/requests/nodes/stats/last.md

Staging links:
https://docs.redis.com/staging/jira-doc-1478/rs/references/rest-api/requests/nodes/
https://docs.redis.com/staging/jira-doc-1478/rs/references/rest-api/requests/nodes/actions/

DOC-1478: Update /nodes/ pages

---

content/rs/references/rest-api/requests/bdbs/_index.md

Staging Link: https://docs.redis.com/staging/jira-doc-1475/rs/references/rest-api/requests/bdbs/

DOC-1475: Update/re-organize /bdbs/ endpoint

---

content/rc/api/examples/audit-system-logs.md
content/rc/databases/system-logs.md

DOC-1562: RC - Fix broken image in API System Logs example

---

content/embeds/supported-platforms-embed.md

DOC-1571: RS - Update Supported platforms to RHEL 8.6

---

content/embeds/hardware-requirements-embed.md

DOC-1557: RS - Update memory requirements

---

content/kubernetes/deployment/quick-start.md

Collapse the installation steps into a single apply rather than download then apply.

Update operator installation

---

content/rs/references/rest-api/requests/redis_acls/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1481/rs/references/rest-api/requests/redis_acls/

DOC-1481: Update/add examples for /redis_acls/ page

---

content/rs/references/rest-api/requests/cluster/stats/_index.md
content/rs/references/rest-api/requests/cluster/update-cert.md

Staging Links:
https://docs.redis.com/staging/jira-doc-1482/rs/references/rest-api/requests/cluster/stats/
https://docs.redis.com/staging/jira-doc-1482/rs/references/rest-api/requests/cluster/update-cert/

DOC-1482: Update cluster/stats and cluster/update_cert API requests

---

content/glossary/_index.md

DOC-1542
Verified or added the following terms:
high availability
multi-primary
replicaHA
clustering
replication
consistency
syncer
distributed sync
proxy policy
data persistence
participating clusters
replication backlog
FQDN
mDNS
tombstone

Glossary changes DOC-1542

---

content/modules/enterprise-capabilities.md

DOC-1576: Update RedisGraph support for eviction expiration

---

content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md

[Staged preview](https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)

Added RediSearch v2.4.14 release notes

---

content/rs/references/rest-api/requests/users/_index.md

https://docs.redis.com/staging/jira-doc-1484/rs/references/rest-api/requests/users/

DOC-1484: /users/ API request updates

---

content/modules/redisgears/installing-redisgears.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1500/modules/redisgears/installing-redisgears/#install-redisgears-and-dependencies)

Fixed RedisGears install OS & version

---

content/rc/databases/import-data.md

Staging link: https://docs.redis.com/staging/jira-doc-1470/rc/databases/import-data/

DOC-1470: RC Import Data Update

---

content/rs/references/rest-api/requests/bootstrap/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1483/rs/references/rest-api/requests/bootstrap/

DOC-1483: Update /boostrap/ REST API Reference

---

content/ri/installing/install-redis-desktop.md

Updates email and download links #DOC-1600

DOC-1600: Update RedisInsight Links

---

content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md

[Staged preview](https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.2-release-notes/#field-aliasing)

Search release notes: fields changed to attributes

---

content/rs/release-notes/rs-6-2-10-february-2022.md

Confirmed with Alon Shmueli (TA director)

Added support for RHEL 8.6 in RS 6.2.10 release notes

---

content/rc/cloud-integrations/gcp-marketplace/_index.md

Staging Link: https://docs.redis.com/staging/jira-doc-1582/rc/cloud-integrations/gcp-marketplace/

Fix GCP Marketplace steps (DOC-1582)

---

content/kubernetes/deployment/openshift/openshift-cli.md
content/kubernetes/deployment/openshift/openshift-operatorhub.md
content/kubernetes/deployment/quick-start.md

Added notes to create REC step of deployment articles. 
- https://docs.redis.com/staging/jira-doc-1573/kubernetes/deployment/quick-start/
- https://docs.redis.com/staging/jira-doc-1573/kubernetes/deployment/openshift/openshift-operatorhub/
- https://docs.redis.com/staging/jira-doc-1573/kubernetes/deployment/openshift/openshift-cli/
Jira: DOC-1561

DOC-1561 one node REC not supported

---

content/rs/release-notes/rs-6-2-18.md
content/rs/security/audit-events.md
content/rs/security/internode-encryption.md

RS - DOC-1616: v6.2.18 release notes and supporting docs

---

content/rs/_index.md
layouts/partials/home/options.html

DOC-1641 - RS: "Hero" page should reflect the reorg

---

content/rs/release-notes/rs-6-2-18.md

DOC 1645 - RS: 6.2.18 release note typos

---

content/kubernetes/deployment/openshift/openshift-cli.md

Jira: DOC-1639
Slack thread: https://redis.slack.com/archives/CB1LUCQ9Y/p1662918327185659
Staged preview: https://docs.redis.com/staging/jira-doc-1639/kubernetes/deployment/openshift/openshift-cli/

DOC-1639 OpenShift CLI deployment fixes

---

content/rc/api/examples/manage-subscriptions.md

Staging link: https://docs.redis.com/staging/jira-doc-1433/rc/api/examples/manage-subscriptions/

DOC-1433: Add Cloud API examples for managing a subscription in API "Create and edit subscriptions" page

---

content/rs/security/audit-events.md

DOC-1644: RS - Clarify auditing instructions

---

content/embeds/tls-configuration-procedure.md
content/rs/databases/import-export/replica-of/create.md
content/rs/release-notes/rs-6-2-10-february-2022.md
content/rs/security/certificates/updating-certificates.md

DOC-1451 - RS: Update Create Replica Of database article

---

content/kubernetes/reference/cluster-options.md
content/kubernetes/security/manage-rec-credentials.md

Jira: DOC-1683
Staged preview: https://docs.redis.com/staging/jira-doc-1683/kubernetes/security/manage-rec-credentials/

K8s: DOC-1683 incorrect command to remove replace password

---

content/rs/release-notes/rs-6-2-18.md

DOC-1645: Fix typos in 6.2.18 release notes

---

content/kubernetes/memory/sizing-on-kubernetes.md

Add a warning about adjusting REC memory size with respect to existing persistent volume size, which cannot be changed after creation.

Add a warning regarding adjusting REC memory size

---

content/kubernetes/re-clusters/redis-on-flash.md

Jira: DOC-1312
Staged preview: https://docs.redis.com/staging/jira-doc-1312/kubernetes/re-clusters/redis-on-flash/

K8s: RoF preview content

---

content/rs/references/cli-utilities/crdb-cli/_index.md
content/rs/references/cli-utilities/crdb-cli/task/_index.md
content/rs/references/cli-utilities/crdb-cli/task/cancel.md
content/rs/references/cli-utilities/crdb-cli/task/list.md
content/rs/references/cli-utilities/crdb-cli/task/status.md

DOC-1690: RS - Update crdb-cli task command reference

---

content/rs/references/cli-utilities/rladmin/info.md

DOC-1691 - RS: Update rladmin info reference to include syncer_mode

---

content/rs/databases/active-active/synchronization-mode.md

DOC-1692 - RS: Update Configure distributed synchronization to include syncer_mode 

---

content/rs/references/compatibility/commands/connection.md

Initial compatibility tables for OSS Redis connection commands and Redis Enterprise Software/Cloud.
[Staged preview](https://docs.redis.com/staging/jira-doc-1669/rs/references/compatibility/commands/connection/)

Connection commands compatibility

---

content/glossary/_index.md
content/rs/databases/redis-on-flash/getting-started-redis-flash.md
content/rs/databases/redis-on-flash/rof-quickstart.md
content/rs/installing-upgrading/get-started-redis-enterprise-software.md

Edits for clarity, reduce length, and remove broken image.
Preview: https://docs.redis.com/staging/jira-doc-1647/rs/databases/redis-on-flash/rof-quickstart/

DOC-1647: Redis on Flash quick start edits 

---

content/rs/references/compatibility/commands/scripting.md

Initial compatibility table for OSS Redis scripting commands and Redis Enterprise Software/Cloud.
[Staged preview](https://docs.redis.com/staging/jira-doc-1676/rs/references/compatibility/commands/scripting/)

Scripting command compatibility

---

content/rs/references/compatibility/commands/transactions.md

Initial compatibility table for OSS Redis transaction commands and Redis Enterprise Software/Cloud.
[Staged preview](https://docs.redis.com/staging/jira-doc-1681/rs/references/compatibility/commands/transactions/)

Transaction commands compatibility

---

content/rs/references/compatibility/config-settings.md

Initial compatibility table for OSS Redis config settings and Redis Enterprise Software/Cloud.
[Staged preview](https://docs.redis.com/staging/jira-doc-1682/rs/references/compatibility/config-settings/)

OSS Redis config compatibility

---

content/rc/security/database-security/network-security.md

Build error fix: Typo in VPC peering relref

---

content/ri/release-notes/v.2.4.0.md
content/ri/release-notes/v.2.6.0.md
content/ri/release-notes/v1.12.0.md
content/ri/release-notes/v1.13.0.md
content/ri/release-notes/v2.0.md
content/ri/release-notes/v2.10.0.md
content/ri/release-notes/v2.12.0.md
content/ri/release-notes/v2.2.0.md
content/ri/release-notes/v2.8.0.md

RI release notes update

---

content/rs/installing-upgrading/product-lifecycle.md

August 2023 is 6 months from Feb 2023 not Feb 2022.

Update product-lifecycle.md with correct EOL date in the notes

---

content/modules/redisgraph/_index.md
content/modules/redisgraph/config.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1443/modules/redisgraph/config/)

RedisGraph config compatibility

---

content/modules/redistimeseries/_index.md
content/modules/redistimeseries/config.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1708/modules/redistimeseries/config/)

RedisTimeSeries config compatibility table

---

content/modules/redisearch/commands.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1712/modules/redisearch/commands/)

RediSearch command compatibility

---

content/kubernetes/security/manage-rec-certificates.md

Jira: DOC-1730
Staged preview: https://docs.redis.com/staging/jira-doc-1730/kubernetes/security/manage-rec-certificates/

DOC-1730 K8s: change create secret to kubectl cmd

---

content/modules/redisjson/commands.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1714/modules/redisjson/commands/)

RedisJSON command compatibility

---

content/modules/redisbloom/commands.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1711/modules/redisbloom/commands/)

RedisBloom command compatibility

---

content/rs/databases/redis-on-flash/_index.md

Complete dev edit of the Redis on Flash overview, hopefully to clarify and make it more user friendly. 
Also added note about RediSearch indexes being stored on RAM related to jira DOC-1559
Staged preview: https://docs.redis.com/staging/jira-doc-1392/rs/databases/redis-on-flash/

RoF overview edits DOC-1392

---

content/rs/release-notes/rs-6-2-18.md

Hey
Adding a deprecation notice about 3DES
@lanceleonard  can you please review?

Update rs-6-2-18.md - Adding deprecation note

---

content/rs/release-notes/rs-6-2-18.md

The release notes should be updated accordingly. Thanks!

Update the website with 6.2.18-58

---

content/rc/security/single-sign-on/saml-sso.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1735/rc/security/single-sign-on/saml-sso/#add-saml-users)

Updated redisAccountMapping options

---

content/rs/clusters/maintenance-mode.md

DOC-280 - RS: Update maintenance mode doc to reflect deactivation

---

content/rc/security/single-sign-on/saml-sso.md

@rrelledge @lanceleonard please confirm that the URL is still correctly formatted as intended

Update SP meta data URLs

---

content/modules/redisgears/installing-redisgears.md

DOC-1777 - Modules: RedisGears install download link leads to a 404 

---

content/kubernetes/logs/collect-logs.md

--Waiting on changes from R&D and the okay from Yuval--
Staged preview: https://docs.redis.com/staging/jira-doc-1761/kubernetes/logs/collect-logs/
JIRA: DOC-1761

DOC-1761 K8s: log collector mode

---

content/kubernetes/re-clusters/create-aa-database.md
content/kubernetes/re-databases/set-up-ingress-controller.md

Jira: DOC-1788
Preview: https://docs.redis.com/staging/jira-doc-1788/kubernetes/re-databases/set-up-ingress-controller/
https://docs.redis.com/staging/jira-doc-1788/kubernetes/re-clusters/create-aa-database/

DOC-1788 update ssl-passthrough annotation

---

content/rs/security/access-control/create-roles.md

Updates:
- Clarified default management role permissions info/tables/links for RS admin console versus REST API
- Reformatted admin console permissions table
[Staged preview](https://docs.redis.com/staging/jira-doc-1447/rs/security/access-control/create-roles/#default-management-roles)

Updated RS default role permissions

---

content/rs/databases/import-export/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1719/rs/databases/import-export/

DOC-1719: Replace TOC and edit descriptions for databases/import-export index page

---

content/rs/clusters/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1721/rs/clusters/

DOC-1721: Edit descriptions for clusters index page

---

content/rs/release-notes/rs-6-2-18.md

Contains updates relevant to the RS version that is on the download center

6.2.18 December release is out

---

content/rc/security/database-security/passwords-users-roles.md

Initial draft of RC pub/sub ACLs.
Staged preview:
- [Define permissions](https://docs.redis.com/staging/jira-doc-1773/rc/security/database-security/passwords-users-roles/#define-permissions)
- [Pub/sub ACL rules](https://docs.redis.com/staging/jira-doc-1773/rc/security/database-security/passwords-users-roles/#pubsub-acl-rules)
- [Rule builder updates](https://docs.redis.com/staging/jira-doc-1773/rc/security/database-security/passwords-users-roles/#configure-permissions-with-redis-acls)

RC pub/sub ACLs

---

content/rs/databases/configure/database-persistence.md

- Initial draft
- Add section re: Active-Active considerations

DOC-1794: RS - Broken links on "Configure database persistence"

---

content/kubernetes/re-clusters/upgrade-redis-cluster.md
content/kubernetes/release-notes/k8s-6-2-18-41.md

Staged preview: https://docs.redis.com/staging/jira-doc-1784/kubernetes/release-notes/k8s-6-2-18-41/

DOC-1784 K8s Neptune maint 6.2.18-41 release notes

---

content/rs/references/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1724/rs/references/

DOC-1724: Replace TOC and edit descriptions for reference index page

---

content/rs/_index.md

Fix typo in RS main page

---

content/rc/cloud-integrations/prometheus-integration.md

Staging link: https://docs.redis.com/staging/jira-doc-1740/rc/cloud-integrations/prometheus-integration/

DOC-1740: RC Quick start for Prometheus/Grafana

---

content/rc/security/single-sign-on/saml-sso.md

- note about SAML integration guides
- note about implications for deprovisioning for API keys

SAML docs updates

---

content/rs/security/_index.md

As per the subject, fixed two instances of said typographical error

Fixed typo 'unauthroized'

---

content/kubernetes/release-notes/k8s-6-2-18-41.md

Staged preview: https://docs.redis.com/staging/k8s-rn-order/kubernetes/release-notes/

K8s - release note order error

---

content/rs/databases/memory-performance/memory-limit.md

Fixed formatting for related info link in RS memory limits doc.
[Staged preview](https://docs.redis.com/staging/fix-link/rs/databases/memory-performance/memory-limit/#related-info)

RS: Fix link and typos

---

content/kubernetes/re-clusters/cluster-recovery.md

Jiras: DOC-1623 DOC-1746
Staged preview:
https://docs.redis.com/staging/jira-doc-1623/kubernetes/re-clusters/cluster-recovery/

DOC-1623 remove duplicate DB recovery from K8s cluster recovery guide

---

content/rc/security/private-service-connect.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1818/rc/security/private-service-connect/)

RC Private Service Connect feedback updates

---

content/rs/security/audit-events.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1696/rs/security/audit-events/)

Edit RS audit events reference tables

---

content/rs/references/cli-utilities/rladmin/cluster/config.md
content/rs/references/rest-api/objects/cluster/_index.md

- [rladmin cluster config](https://docs.redis.com/staging/jira-doc-1697/rs/references/cli-utilities/rladmin/cluster/config/)
- [REST API cluster object](https://docs.redis.com/staging/jira-doc-1697/rs/references/rest-api/objects/cluster/)

RS PEM encryption references

---

content/rc/security/database-security/passwords-users-roles.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1805/rc/security/database-security/passwords-users-roles/#pubsub-acl-rules)

RC pub/sub ACLs - Redis 7 differences

---

content/rc/security/access-management.md

[Staged preview](https://docs.redis.com/staging/pr-1764-patch/rc/security/access-management)

Removed outdated GCP Marketplace team management section

---

content/rs/security/access-control/manage-users/manage-passwords.md

- Updating link target and anchors, per ticket.

DOC-1867: RS - "Manage passwords" has broken Internal link 

---

content/rs/databases/import-export/import-data.md

Another change made for Azure, affecting all RS and missing documentation

Update mount point import

---

content/rs/release-notes/rs-6-2-12.md

Retroactively add a change made in Azure and not documented for RS

Import enhancement

---

content/rs/databases/active-active/create.md

updated the written path to reflect what is in the UI. it was settings >teams but should be access control >users.

Updated create.md to match the UI

---

content/embeds/supported-platforms-embed.md

- [Supported platforms table](https://docs.redis.com/staging/jira-doc-1861/rs/installing-upgrading/supported-platforms/#supported-platforms)
- [SHA1 certificate limitation](https://docs.redis.com/staging/jira-doc-1861/rs/installing-upgrading/supported-platforms/#ubuntu-20-rejects-sha1-certificates)

RS: Added Ubuntu 20.04 to supported platforms

---

content/rc/security/access-management.md

DOC-1875: RC - Billing alert user limit

---

content/kubernetes/release-notes/k8s-6-2-18-41-jan-2023.md

Just adjusting weights so they appear in the right order.

K8s release notes fix

---

content/rs/references/rest-api/requests/bdbs/modules/config.md
content/rs/references/rest-api/requests/modules/config.md

- [/bdbs/uid/modules/config](https://docs.redis.com/staging/jira-doc-1869/rs/references/rest-api/requests/bdbs/modules/config/)
- [/modules/config/bdb/](https://docs.redis.com/staging/jira-doc-1869/rs/references/rest-api/requests/modules/config/)

Fixed /modules/config REST API request examples

---

content/rs/security/access-control/manage-users/manage-passwords.md

DOC-1878 - RS: Update password complexity rule text

---

content/rs/release-notes/rs-6-4-2.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1858/rs/release-notes/rs-6-4-2/)

RS v6.4.2 release notes

---

content/rs/references/rest-api/objects/bdb/_index.md
content/rs/references/rest-api/objects/cluster_settings.md
content/rs/references/rest-api/objects/db-conns-auditing-config.md
content/rs/references/rest-api/requests/cluster/auditing-db-conns.md
content/rs/references/rest-api/requests/cluster/policy.md
content/rs/security/audit-events.md

Request reference previews:
- [Cluster policy requests](https://docs.redis.com/staging/jira-doc-1694/rs/references/rest-api/requests/cluster/policy/)
- [Auditing database connections requests](https://docs.redis.com/staging/jira-doc-1694/rs/references/rest-api/requests/cluster/auditing-db-conns/)
Object reference previews:
- [Database connection auditing configuration](https://docs.redis.com/staging/jira-doc-1694/rs/references/rest-api/objects/db-conns-auditing-config/)
- [Cluster settings object](https://docs.redis.com/staging/jira-doc-1694/rs/references/rest-api/objects/cluster_settings/)
- [BDB object](https://docs.redis.com/staging/jira-doc-1694/rs/references/rest-api/objects/bdb/)

REST API references for RS audit events

---

content/rc/databases/configuration/data-eviction-policies.md
content/rs/databases/active-active/create.md
content/rs/databases/active-active/develop/develop-for-aa.md

- [RC: available eviction policies](https://docs.redis.com/staging/jira-doc-1847/rc/databases/configuration/data-eviction-policies/#available-policies) - removed outdated note
- [RS: Develop apps with Active-Active databases](https://docs.redis.com/staging/jira-doc-1847/rs/databases/active-active/develop/develop-for-aa/#eviction)
- [RS: Create an Active-Active database](https://docs.redis.com/staging/jira-doc-1847/rs/databases/active-active/create/#create-an-active-active-database)

Active-Active eviction policy support updates

---

content/rs/networking/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1723/rs/networking/

DOC-1723: Edit descriptions for networking index page

---

content/rs/installing-upgrading/upgrading.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1848/rs/installing-upgrading/upgrading/#default-db-versions)

Upgrade RS - default DB version change

---

.circleci/config.yml
layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

#hold-off until the scheduled release.
Note: the CircleCI config changes were necessary because the build was broken for this older branch.

Update RS version dropdown - 6.0-build branch

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

#hold-off until scheduled release.

Update RS version dropdown - 6.2-build branch

---

content/rs/clusters/optimize/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1722-real/rs/clusters/optimize/

DOC-1722: Edit descriptions for clusters/optimize index page

---

content/kubernetes/deployment/openshift/openshift-operatorhub.md

Staged preview: https://docs.redis.com/staging/jira-doc-1780/kubernetes/deployment/openshift/openshift-operatorhub/
Jiras: DOC-1780 and DOC-1840

K8s: OperatorHub deployment dev edits DOC-1780 DOC-1840

---

content/kubernetes/deployment/quick-start.md

Jira: DOC-1813
Staged preview: https://docs.redis.com/latest/kubernetes/deployment/quick-start/
Waiting on feedback about which files are part of the bundle and the best practice for customers to obtain files that aren't.

K8s: Admission controller quick start edits

---

content/embeds/supported-platforms-embed.md

DOC-1912 - RS: Add RHEL 8.7 to supported platforms

---

content/rs/security/access-control/ldap/migrate-to-role-based-ldap.md

DOC-1627: Update LDAP Migration process

---

content/kubernetes/deployment/openshift/openshift-cli.md
content/kubernetes/deployment/openshift/openshift-operatorhub.md

https://docs.redis.com/staging/jira-doc-1817/kubernetes/deployment/openshift/openshift-cli
https://docs.redis.com/staging/jira-doc-1817/kubernetes/deployment/openshift/openshift-operatorhub
Jira: DOC-1817
This PR also includes work for DOC-1920 to remove mentions of OpenShift 3 (no longer supported).

DOC-1817 Update scc.yaml steps in OpenShift install

---

content/rs/references/compatibility/breaking-changes.md
content/rs/references/compatibility/commands/_index.md
content/rs/references/compatibility/config-settings.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1882/rs/references/compatibility/breaking-changes/)

Breaking changes list

---

layouts/partials/navigation.html

[Staged preview](https://docs.redis.com/staging/jira-doc-1919/)

Added RC & RS doc links to top navigation menu

---

content/embeds/supported-platforms-embed.md

- [Supported platforms table](https://docs.redis.com/staging/jira-doc-1923/rs/installing-upgrading/supported-platforms/#supported-platforms)
- [Ubuntu 20 limitation](https://docs.redis.com/staging/jira-doc-1923/rs/installing-upgrading/supported-platforms/#ubuntu-20-rejects-sha1-certificates)

RS Ubuntu 20 support

---

content/rs/databases/import-export/import-data.md
content/rs/release-notes/legacy-release-notes/_index.md
content/rs/release-notes/legacy-release-notes/rs-5-5-preview-april-2019.md
content/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
content/rs/release-notes/rs-6-4-2.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1922/rs/release-notes/rs-6-4-2/)

RS 6.4.2 March release notes update

---

static/theme-flex/style.css

- [Cloud docs](https://docs.redis.com/staging/jira-doc-1918/rc/)
- [Software docs](https://docs.redis.com/staging/jira-doc-1918/rs/)

Increased section title font size in ToC

---

content/rs/release-notes/rs-6-2-18.md
content/rs/release-notes/rs-6-4-2.md

- [RS 6.4.2 release notes](https://docs.redis.com/staging/jira-doc-1932/rs/release-notes/rs-6-4-2/)
- [RS 6.2.18 release notes](https://docs.redis.com/staging/jira-doc-1932/rs/release-notes/rs-6-2-18/)

RS release notes format updates (6.2.18 & 6.4.2)

---

content/kubernetes/deployment/openshift/openshift-operatorhub.md

Staged preview: https://docs.redis.com/staging/jira-doc-1945/kubernetes/deployment/openshift/openshift-operatorhub/

K8s: DOC-1945

---

content/kubernetes/deployment/openshift/openshift-cli.md

https://docs.redis.com/staging/scc-fix-317/kubernetes/deployment/openshift/openshift-cli/

K8s: corrected scc 6.2.18-41 note

---

content/embeds/backup-locations.md
content/modules/modules-quickstart.md
content/rc/api/examples/manage-subscriptions.md
content/rc/cloud-integrations/_index.md
content/rc/cloud-integrations/aws-marketplace/_index.md
content/rc/cloud-integrations/gcp-marketplace/_index.md
content/rc/cloud-integrations/gcp-marketplace/team-management.md
content/rc/databases/back-up-data.md
content/rc/databases/import-data.md
content/rc/security/database-security/network-security.md
content/rc/security/encryption-at-rest.md
content/rc/security/private-service-connect.md
content/rc/security/shared-responsibility-model.md
content/rc/security/vpc-peering.md
content/rc/subscriptions/create-fixed-subscription.md
content/rc/subscriptions/create-flexible-subscription.md
content/rs/databases/import-export/export-data.md
content/rs/databases/import-export/schedule-backups.md

Staging links:
DOC-1913: https://docs.redis.com/staging/jira-doc-1913/rc/cloud-integrations/gcp-marketplace/team-management/
DOC-1776: https://docs.redis.com/staging/jira-doc-1913/rc/cloud-integrations/gcp-marketplace/

DOC-1913, DOC-1776, and DOC-1954: GCP Fixes

---

content/kubernetes/active-active/preview/create-reaadb.md

The RERC were invalid due to broken indentation

indentation fix

---

content/rc/databases/back-up-data.md

Staging link: https://docs.redis.com/staging/jira-doc-1315/rc/databases/back-up-data/#aws-s3

DOC-1315: Missing limitation indicator for S3 bucket usage on multiple accounts

---

content/rc/security/single-sign-on/saml-sso/_index.md

Staging link: https://docs.redis.com/staging/jira-doc-1927/rc/security/single-sign-on/saml-sso/#set-up-app
Would like to merge this with the SAML integration guides (#2345).

DOC-1927: Improve redisAccountMapping field description

---

content/kubernetes/re-clusters/multi-namespace.md

Jira: DOC-1953
Staged preview: https://docs.redis.com/staging/jira-doc-1953/kubernetes/re-clusters/multi-namespace/
preview-jira-doc-1953
staging-jira-doc-1953/kubernetes/re-clusters/multi-namespace/

K8s: multi-namespace corrections DOC-1953

---

content/kubernetes/re-clusters/multi-namespace.md

The note about role and rolebinding was in the wrong place

The note about role and rolebinding was in the wrong place

---

content/rs/security/tls/ciphers.md

[Staged preview](https://docs.redis.com/staging/jira-doc-1838/rs/security/tls/ciphers/)

Clarified/cleaned up RS version cipher suite support

---

content/rs/release-notes/rs-6-2-18.md

[Staged preview](https://docs.redis.com/staging/fix-6.2-eol/rs/release-notes/rs-6-2-18/#product-lifecycle-updates)

Fix RS 6.2 EOL in release notes

---

content/kubernetes/security/manage-rec-certificates.md

Jira: https://redislabs.atlassian.net/browse/DOC-1967
Staged preview: https://docs.redis.com/staging/jira-doc-1967/kubernetes/security/manage-rec-certificates/

Fix K8s code block formatting

---

content/kubernetes/release-notes/k8s-6-4-2-4.md

Staged preview: https://docs.redis.com/staging/jira-doc-2075/kubernetes/release-notes/k8s-6-4-2-4/

K8s: release notes - add resharding limitation from RS

---

content/kubernetes/active-active/preview/_index.md
content/kubernetes/active-active/preview/create-reaadb.md
content/kubernetes/active-active/preview/prepare-clusters.md

Jira: https://redislabs.atlassian.net/browse/DOC-2069
- https://docs.redis.com/staging/DOC-2069/kubernetes/active-active/preview/
- https://docs.redis.com/staging/DOC-2069/kubernetes/active-active/preview/prepare-clusters/
- https://docs.redis.com/staging/DOC-2069/kubernetes/active-active/preview/create-reaadb/

DOC-2069 AA preview content fixes

---

content/kubernetes/deployment/openshift/openshift-cli.md
content/kubernetes/deployment/openshift/openshift-operatorhub.md
content/kubernetes/deployment/quick-start.md

Jira: https://redislabs.atlassian.net/browse/DOC-1898
Staged preview pages: 
- https://docs.redis.com/staging/jira-doc-1898/kubernetes/deployment/quick-start/
- https://docs.redis.com/staging/jira-doc-1898/kubernetes/deployment/openshift/openshift-operatorhub/
- https://docs.redis.com/staging/jira-doc-1898/kubernetes/deployment/openshift/openshift-cli/

K8s: add warning not to edit or delete statefulset

---

content/kubernetes/re-clusters/multi-namespace.md

Jira: DOC-2107
Staging preview: https://docs.redis.com/staging/DOC-2107/kubernetes/re-clusters/multi-namespace/

K8s: multi-namespace version note

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

changes RDI to redis-di in version selector scripts

Version selector script update

---

content/kubernetes/deployment/openshift/openshift-cli.md
content/kubernetes/deployment/quick-start.md

Jira: DOC-2066
https://docs.redis.com/staging/DOC-2066/kubernetes/deployment/openshift/openshift-cli/
https://docs.redis.com/staging/DOC-2066/kubernetes/deployment/quick-start/

K8s: correct webhook name for 6.2.4-4

---

content/rdi/_index.md
content/rdi/quickstart/_index.md

Adds private preview banner, corrects use of word quickstart

Adds RDI private preview banner

---

content/rdi/_index.md
content/rdi/quickstart/_index.md

Adds private preview banner, updates word quickstart

Add RDI preview banner

---

content/kubernetes/memory/node-selection.md

I think that the value for rackAwarenessNodeLabel is incorrect

I think that the value for rackAwarenessNodeLabel is incorrect

---

content/kubernetes/re-clusters/upgrade-redis-cluster.md

Jira: DOC-2117
Staged preview: https://docs.redis.com/staging/DOC-2117/kubernetes/re-clusters/upgrade-redis-cluster/

K8s: DOC-2117 warning

---

content/rc/security/_index.md
content/rc/security/access-control/_index.md
content/rc/security/access-control/data-access-control/_index.md
content/rc/security/access-control/data-access-control/create-assign-users.md
content/rc/security/access-control/data-access-control/default-user.md

https://docs.redis.com/staging/DOC-2129/rc/security/access-control/
https://docs.redis.com/staging/DOC-2129/rc/security/access-control/data-access-control/
Once this is approved, I'll open the PR for the full access control reorg.

DOC-2129: Create Access Control and Data Access Control landing pages

---

content/rc/cloud-integrations/prometheus-integration.md
content/rs/clusters/monitoring/prometheus-integration.md

- Added links to our new, official Grafana dashboards for Redis Software and Cloud
- Revised some wording

Grafana dashboards

---

content/rs/databases/create.md

[Staged preview](https://docs.redis.com/staging/fix-link/rs/databases/create/)

RS: Fix link and note format

---

content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
content/kubernetes/release-notes/k8s-6-2-10-45-2022-07.md
content/kubernetes/release-notes/k8s-6-2-12-1.md
content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
content/kubernetes/release-notes/k8s-6-2-8-15-2022-01.md
content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md

JIRA: DOC-2155
Staged preview: https://docs.redis.com/staging/DOC-2155/kubernetes/release-notes/

DOC-2155 add known limitations to 6.2 release notes

---

content/kubernetes/deployment/openshift/openshift-cli.md
content/kubernetes/deployment/quick-start.md

Jira: DOC-2154
Staged preview: https://docs.redis.com/staging/DOC-2154/kubernetes/deployment/quick-start/
https://docs.redis.com/staging/DOC-2154/kubernetes/deployment/openshift/openshift-cli/

DOC-2154 update admission webhook name

---

content/rc/security/access-control/data-access-control/create-assign-users.md

Staging link: https://docs.redis.com/staging/DOC-1136/rc/security/access-control/data-access-control/create-assign-users/

DOC-1136: Document the limitation of "admin" SASL user for memcached

---

content/rc/rc-quickstart.md

Staging link: https://docs.redis.com/staging/DOC-2205/rc/rc-quickstart/#more-info

DOC-2205 fixed quick start security link

---

content/ri/release-notes/v1.13.0.md
content/ri/release-notes/v1.14.0.md

NOTE: Don't merge until RedisInsight v1.13.2 release.

Redisinsight v1.14.0 release notes

---

content/rs/references/cli-utilities/rladmin/cluster/config.md

[Staged preview](https://docs.redis.com/staging/DOC-2168/rs/references/cli-utilities/rladmin/cluster/config/)

RS: Customize envoy ports using rladmin

---

content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md

[Staged preview](https://docs.redis.com/staging/DOC-2169/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement/#get-request)

RS REST API: Optimize shard placement query parameters

---

content/rc/databases/import-data.md

https://docs.redis.com/staging/DOC-2230/rc/databases/import-data/#via-ftp-or-http

RC: Missing the host in the Import data documentation

---

content/rc/security/access-control/data-access-control/active-active-roles.md
content/rc/security/access-control/data-access-control/configure-acls.md
content/rc/security/access-control/data-access-control/create-roles.md

Staging link: 
https://docs.redis.com/staging/DOC-2223/rc/security/access-control/data-access-control/configure-acls/
https://docs.redis.com/staging/DOC-2223/rc/security/access-control/data-access-control/create-roles/
https://docs.redis.com/staging/DOC-2223/rc/security/access-control/data-access-control/active-active-roles/

DOC-2223 Add notes about ACL verification

---

content/embeds/supported-platforms-embed.md

- [Supported platforms table note](https://docs.redis.com/staging/DOC-2170/rs/installing-upgrading/supported-platforms/#table-note-7)
- [OS limitation](https://docs.redis.com/staging/DOC-2170/rs/installing-upgrading/supported-platforms/#modules-not-supported-for-amazon-linux-2-release-candidate)

RS: Amazon Linux 2 support update

---

content/kubernetes/memory/node-resources.md
content/kubernetes/re-clusters/node-resources.md

Jiras: DOC-1916 DOC-1659
Staged preview: https://docs.redis.com/staging/DOC-1916/kubernetes/re-clusters/node-resources/

K8s: Node resource eviction thresholds and resource quotas (content migration)

---

content/kubernetes/active-active/preview/edit-rerc.md

Jira: DOC-1844
Readme source material: https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/active_active_database_readme.md#update-existing-participating-cluster-rerc-details
Staged preview: https://docs.redis.com/staging/DOC-1844/kubernetes/active-active/preview/edit-rerc/

DOC-1844 K8s: Edit RERC 

---

content/rs/release-notes/rs-6-2-18-releases/_index.md

[Staged preview](https://docs.redis.com/staging/DOC-2204/rs/release-notes/rs-6-2-18-releases/#feature-limitations)

Add CRDB restart loop to RS 6.2.18 known issues

---

content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md

adding some revolved issues and known limitations

Amiramm patch 3

---

content/rc/api/_index.md
content/rc/api/examples/create-database.md
content/rc/api/examples/manage-subscriptions.md
content/rc/api/examples/update-database.md
content/rc/api/get-started/_index.md
content/rc/api/get-started/enable-the-api.md
content/rc/api/get-started/manage-api-keys.md
content/rc/api/get-started/process-lifecycle.md
content/rc/api/get-started/use-rest-api.md

Staging links:
https://docs.redis.com/staging/DOC-1966/rc/api/
https://docs.redis.com/staging/DOC-1966/rc/api/get-started/
https://docs.redis.com/staging/DOC-1966/rc/api/get-started/enable-the-api/
https://docs.redis.com/staging/DOC-1966/rc/api/get-started/manage-api-keys/
https://docs.redis.com/staging/DOC-1966/rc/api/get-started/manage-tasks/
https://docs.redis.com/staging/DOC-1966/rc/api/get-started/process-lifecycle/
https://docs.redis.com/staging/DOC-1966/rc/api/examples/manage-subscriptions/
https://docs.redis.com/staging/DOC-1966/rc/api/examples/create-database/
https://docs.redis.com/staging/DOC-1966/rc/api/examples/update-database/

DOC-1966: REST API | Align documentation after Fixed API release

---

content/kubernetes/re-clusters/delete_custom_resources.md

Jira: DOC-2138 DOC-1843
Staged preview: https://docs.redis.com/staging/DOC-1843/kubernetes/re-clusters/delete_custom_resources/

K8s: Delete REAADB and configmap DOC-2138 DOC-1843

---

content/kubernetes/active-active/preview/global-config.md

Jira: DOC-2062
Source material: https://github.com/RedisLabs/redis-enterprise-operator/blob/master/deploy/active_active_database_readme.md#set-the-database-global-configurations-specifications
Staged preview: https://docs.redis.com/staging/DOC-2062/kubernetes/active-active/preview/global-config/

DOC-2062 Global config article for K8s AA public preview

---

content/rc/changelog/april-2023.md
content/rc/changelog/may-2023.md

Staging link: https://docs.redis.com/staging/DOC-2237/rc/changelog

DOC-2237: RC Changelog April and May 2023

---

content/ri/release-notes/v.2.24.0.md

[Staged preview](https://docs.redis.com/staging/ri-release-notes-fix/ri/release-notes/v.2.24.0/)

RI: Fixed date in link title for RI v.2.24.0 release notes

---

content/rc/cloud-integrations/gcp-marketplace/_index.md

Staging link: https://docs.redis.com/staging/DOC-2121/rc/cloud-integrations/gcp-marketplace

DOC-2121: Update GCP marketplace integration docs page

---

content/kubernetes/active-active/preview/_index.md
content/kubernetes/active-active/preview/create-reaadb.md
content/kubernetes/active-active/preview/edit-clusters.md
content/kubernetes/active-active/preview/edit-rerc.md
content/kubernetes/active-active/preview/global-config.md
content/kubernetes/active-active/preview/prepare-clusters.md

Remove steps to enable the AA controller and apply the CRDs (now down by default). 
JIRA: DOC-2244

DOC-2244 remove CRD steps and banners

---

content/rs/release-notes/rs-6-2-10-february-2022.md
content/rs/release-notes/rs-6-2-12.md
content/rs/release-notes/rs-6-2-18-releases/_index.md
content/rs/release-notes/rs-6-2-4-august-2021.md
content/rs/release-notes/rs-6-2-8-october-2021.md
content/rs/release-notes/rs-6-4-2-releases/_index.md
content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md

- [6.4.2](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-4-2-releases/#known-limitations)
- [6.2.18](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-2-18-releases/#known-limitations)
- [6.2.12](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-2-12/#known-limitations)
- [6.2.10](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-2-10-february-2022/#known-issues)
- [6.2.8](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-2-8-october-2021/#known-issues)
- [6.2.4](https://docs.redis.com/staging/DOC-2335/rs/release-notes/rs-6-2-4-august-2021/)

RS: Update known issues in 6.4.2 & 6.2 release notes

---

content/rs/security/tls/ciphers.md

[Staged preview](https://docs.redis.com/staging/DOC-1800/rs/security/tls/ciphers/)

Update TLS cipher examples to remove 3DES keys

---

content/rdi/data-transformation/examples/multiple-targets-example.md
content/rdi/data-transformation/examples/redis-sorted-set-example.md

* content/rdi/data-transformation/examples/multiple-targets-example.md
* content/rdi/data-transformation/examples/redis-sorted-set-example.md

RDSC-1302: added sorted sets example

---

content/rs/installing-upgrading/upgrading.md
content/rs/release-notes/rs-6-2-10-february-2022.md
content/rs/release-notes/rs-6-2-12.md
content/rs/release-notes/rs-6-2-18-releases/_index.md
content/rs/release-notes/rs-6-2-4-august-2021.md
content/rs/release-notes/rs-6-2-8-october-2021.md
content/rs/release-notes/rs-6-4-2-releases/_index.md
content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-81.md
content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba.md

- [Release notes](https://docs.redis.com/staging/release-rs-diablo-june/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-81/)

DOC-2332 RS 6.4.2 June release notes and docs

---

content/kubernetes/active-active/_index.md
content/kubernetes/active-active/edit-clusters.md
content/kubernetes/active-active/global-config.md
content/kubernetes/active-active/global-db-secret.md
content/kubernetes/delete_custom_resources.md

Jira: DOC-2245 DOC-2247
Preview: 
- https://docs.redis.com/staging/DOC-2245/kubernetes/active-active/global-db-secret/
- https://docs.redis.com/staging/DOC-2245/kubernetes/active-active/global-config/
- https://docs.redis.com/staging/DOC-2245/kubernetes/active-active/

K8s: DB secret sync and other AA GA changes

---

content/rdi/reference/data-transformation-block-types/map.md

… type and add example for nested jmespath

RDSC-296 update `map` block documentation with the accurate expression type and add example for nested jmespath

---

content/rdi/installation/install-k8s.md

Additional info about Gears installation on K8s

RDSC-1311 Additional info about Gears on K8s

---

content/embeds/r7.2-breaking-changes.md
content/rc/changelog/june-2023.md

Staging link: https://docs.redis.com/staging/DOC-2365/rc/changelog/june-2023/

DOC-2365 & DOC-2366: Update June changelog with breaking changes

---

content/rs/databases/import-export/replica-of/_index.md

[Staged preview](https://docs.redis.com/staging/DOC-2380/rs/databases/import-export/replica-of/)

RS: Removed outdated Replica Of video & fixed note format

---

content/kubernetes/active-active/create-reaadb.md
content/kubernetes/active-active/edit-clusters.md
content/kubernetes/active-active/edit-rerc.md
content/kubernetes/active-active/global-config.md
content/kubernetes/active-active/prepare-clusters.md

DOC-2139
Preview:
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/create-aa-crdb-cli/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/prepare-clusters/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/edit-clusters/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/global-config/
- https://docs.redis.com/staging/DOC-2139/kubernetes/active-active/edit-rerc/

K8s: add real words to example values

---

content/rc/subscriptions/maintenance/set-maintenance-windows.md

Staging link: https://docs.redis.com/staging/DOC-2377/rc/subscriptions/maintenance/set-maintenance-windows/

DOC-2377: Add Disclaimer about when maintenance window changes are updated to the Maintenance window docs

---

content/kubernetes/networking/ingressorroutespec.md

Jira: DOC-2385
Preview: https://docs.redis.com/staging/DOC-2385/kubernetes/networking/ingressorroutespec/

K8s: OpenShift ingressOrRoutes example

---

content/kubernetes/re-clusters/upgrade-redis-cluster.md

Jira: DOC-2406
Preview: https://docs.redis.com/staging/DOC-2406/kubernetes/re-clusters/upgrade-redis-cluster/#after-upgrading

K8s: revise delete scc steps in upgrade article

---

content/rc/cloud-integrations/prometheus-integration.md

Staging link: https://docs.redis.com/staging/DOC-2384/rc/cloud-integrations/prometheus-integration/

DOC-2384: Incorrect indentation in yaml example for prometheus-integration

---

content/modules/redisgears/python/recipes/write-behind.md
content/rs/clusters/cluster-recovery.md
content/rs/databases/active-active/develop/data-types/streams.md
content/rs/databases/active-active/synchronization-mode.md
content/rs/networking/multi-ip-ipv6.md
content/rs/references/cli-utilities/rladmin/migrate.md
content/rs/release-notes/rs-6-2-4-august-2021.md

Added rladmin to commands

---

content/rs/references/cli-utilities/rladmin/upgrade.md

[Staged preview](https://docs.redis.com/staging/DOC-1638/rs/references/cli-utilities/rladmin/upgrade/#parameters)

Fixed upgrade db keep_redis_version parameter

---

content/rs/databases/configure/replica-ha.md

It is not mentioned in the old UI at all as far as I know and in the new UI it's replica HA and not slave

 Update replica-ha.md

---

content/rc/subscriptions/create-flexible-subscription.md
content/ri/_index.md
content/stack/deprecated-features/_index.md
content/stack/deprecated-features/graph/_index.md
content/stack/deprecated-features/graph/commands.md
content/stack/deprecated-features/graph/config.md
content/stack/deprecated-features/graph/graph-quickstart.md
content/stack/enterprise-capabilities.md

[Staged preview](https://docs.redis.com/staging/fix-title/stack/deprecated-features/)

Renamed previous features to deprecated features

---

content/rc/cloud-integrations/terraform/_index.md
content/rc/cloud-integrations/terraform/get-started.md

Staging link:
https://docs.redis.com/staging/DOC-1586/rc/cloud-integrations/terraform

DOC-1586:  Add Terraform to the documentation 

---

content/rc/security/access-control/access-management.md
content/rc/subscriptions/create-flexible-subscription.md

DOC-2379: Billing emails flag: Update access management section
https://docs.redis.com/staging/DOC-2379/rc/security/access-control/access-management/#add-user
DOC-2443: Typo in ops/sec value for Very large shard type
https://docs.redis.com/staging/DOC-2379/rc/subscriptions/create-flexible-subscription/#shard-types

DOC-2379 & DOC-2443

---

layouts/partials/home/options.html

[Staged preview](https://docs.redis.com/staging/fix-links/)

Fix Redis Stack links on home page

---

content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md

Staged preview: https://docs.redis.com/staging/release-diablo-maint-edits/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94/

6.4.2-94 release notes update

---

content/kubernetes/active-active/create-reaadb.md
content/kubernetes/active-active/edit-rerc.md

preview: https://docs.redis.com/DOC-2449/kubernetes/active-active/edit-rerc/
https://docs.redis.com/DOC-2449/kubernetes/active-active/create-reaadb/
DOC Jira: DOC-2449
Review Jira: DOC-2497

K8s: added replication status

---

content/kubernetes/active-active/_index.md
content/kubernetes/active-active/create-reaadb.md
content/kubernetes/active-active/edit-clusters.md
content/kubernetes/active-active/edit-rerc.md
content/kubernetes/active-active/global-config.md
content/kubernetes/active-active/global-db-secret.md
content/kubernetes/active-active/prepare-clusters.md

Jira: [DOC-2454](https://redislabs.atlassian.net/browse/DOC-2454)
Preview: https://docs.redis.com/staging/alpha-flag-edit-new/kubernetes/active-active/prepare-clusters/
https://docs.redis.com/staging/alpha-flag-edit-new/kubernetes/active-active/
[DOC-2454]: https://redislabs.atlassian.net/browse/DOC-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

K8s: AA - add preview version note

---

content/kubernetes/active-active/create-reaadb.md
content/kubernetes/active-active/edit-clusters.md
content/kubernetes/active-active/edit-rerc.md
content/kubernetes/active-active/prepare-clusters.md
content/kubernetes/networking/ingressorroutespec.md
content/kubernetes/re-clusters/connect-prometheus-operator.md
content/kubernetes/security/manage-rec-credentials.md

K8s: change redis.com to example.com

---

content/rs/installing-upgrading/install/customize-install-directories.md
content/rs/installing-upgrading/install/install-on-linux.md
content/rs/release-notes/rs-6-0-12-january-2021.md
content/rs/release-notes/rs-6-0-20-april-2021.md
content/rs/release-notes/rs-6-0-8-september-2020.md
content/rs/release-notes/rs-6-0-may-2020.md
content/rs/release-notes/rs-6-2-10-february-2022.md
content/rs/release-notes/rs-6-2-12.md
content/rs/release-notes/rs-6-2-18-releases/_index.md
content/rs/release-notes/rs-6-2-4-august-2021.md
content/rs/release-notes/rs-6-2-8-october-2021.md
content/rs/release-notes/rs-6-4-2-releases/_index.md

- [6.4.2 release notes](https://docs.redis.com/staging/DOC-2514/rs/release-notes/rs-6-4-2-releases/#installation-limitations)
- The same limitation and workaround was also added to the release notes for previous versions, [Install on Linux](https://docs.redis.com/staging/DOC-2514/rs/installing-upgrading/install/install-on-linux/#limitations), and [Customize install locations](https://docs.redis.com/staging/DOC-2514/rs/installing-upgrading/install/customize-install-directories/#limitations)

RS: Known limitation & workaround for root directory installation

---

content/embeds/supported-platforms-embed.md

[Staged preview](https://docs.redis.com/staging/DOC-2134/rs/installing-upgrading/install/plan-deployment/supported-platforms/#supported-platforms)

RS: Updated supported platforms (DOC-2134 DOC-1215)

---

content/kubernetes/re-clusters/auto-tiering.md
content/rs/references/rest-api/objects/bootstrap/node_identity.md
content/rs/references/rest-api/objects/node.md
content/rs/references/rest-api/requests/bootstrap/_index.md

DOC-2515 speedb changes

---

content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md
layouts/shortcodes/details.html

Preview: https://docs.redis.com/staging/DOC-2519/kubernetes/release-notes/6-4-2-releases/6-4-2-8/

K8s 6.4.2-8 release notes

---

content/stack/release-notes/redisgraph/_index.md

[Staged preview](https://docs.redis.com/staging/graph-release-notes/stack/release-notes/redisgraph/)

Stack: Added deprecation banner to RedisGraph release notes

---

content/rc/subscriptions/maintenance/_index.md

[Staged preview](https://docs.redis.com/staging/DOC-2598/rc/subscriptions/maintenance/)

RC: maintenance windows feedback updates

---

content/rs/release-notes/rs-7-2-releases/rs-7-2-tba.md

Updating Redis Stack 7.2 features

Updating Redis Stack 7.2 features

---

content/rdi/data-transformation/data-denormalization.md

Based on the recent PR in RDI:
https://github.com/RedisLabs/redis-data-integration/pull/895

RDSC-1404-key-name-for-nesting-not-constructed-correctly

---

content/rc/changelog/august-2023.md

Staging link: https://docs.redis.com/staging/tf-link-fix/rc/changelog/august-2023/

Fix triggers and functions links in August changelog

---

content/embeds/supported-platforms-embed.md

[Staged preview](https://docs.redis.com/staging/fix-platforms-table/rs/installing-upgrading/install/plan-deployment/supported-platforms/)

Fix 7.2 version number in supported platforms table

---

content/kubernetes/reference/supported_k8s_distributions.md
layouts/shortcodes/table-scrollable.html

Staged preview: https://docs.redis.com/staging/DOC-2610/kubernetes/reference/supported_k8s_distributions/

DOC-2610 K8s: Expand supported distribution page 

---

content/kubernetes/reference/supported_k8s_distributions.md
content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
content/kubernetes/release-notes/7-2-4-releases/_index.md

Staged preview: https://docs.redis.com/staging/DOC-2635/kubernetes/release-notes/7-2-4-releases/7-2-4-2/
https://docs.redis.com/staging/DOC-2635/kubernetes/reference/supported_k8s_distributions/

K8s: 7.2.4-2 release notes and supported distributions

---

content/embeds/supported-platforms-embed.md

[Staged preview](https://docs.redis.com/staging/DOC-2473/rs/installing-upgrading/install/plan-deployment/supported-platforms/#virtualization-platforms)

RS: Generalize virtualization platform section

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html

[Staged preview](https://docs.redis.com/staging/DOC-2548-v6.4/kubernetes/)

k8s version selector for 6.4 branch

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html

[Staged preview](https://docs.redis.com/staging/DOC-2548-v7.2/kubernetes/)

k8s version selector for 7.2 latest branch

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
content/kubernetes/release-notes/7-2-4-releases/_index.md

- https://docs.redis.com/staging/DOC-2649/kubernetes/release-notes/7-2-4-releases/
- https://docs.redis.com/staging/DOC-2649/kubernetes/release-notes/7-2-4-releases/7-2-4-2/

K8s: cluster recovery with modules - changes to highlights and known limitations

---

content/rs/references/rest-api/objects/node.md

[Staged preview](https://docs.redis.com/staging/DOC-1783/rs/references/rest-api/objects/node/)

RS: Fix accept_servers description in node REST API object

---

content/rs/references/cli-utilities/rladmin/cluster/master.md

[Staged preview](https://docs.redis.com/staging/DOC-1828/rs/references/cli-utilities/rladmin/cluster/master/)

RS: rladmin cluster master reference

---

website.json

Redirect /rdi/ to /latest/rdi/

---

content/rc/billing-and-payments.md
content/rc/databases/delete-database.md

Staging links:
https://docs.redis.com/staging/DOC-2657/rc/billing-and-payments/
https://docs.redis.com/staging/DOC-2657/rc/databases/delete-database/

DOC-2657: Add notes clarifying refunds and charging policies

---

content/kubernetes/_index.md
content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
content/kubernetes/release-notes/7-2-4-releases/_index.md

Remove TGK 2.1/2.2 and add RED-106834 limitation.

K8s: release note updates

---

content/rc/billing-and-payments.md

Staging link: https://docs.redis.com/staging/fix-billing-note/rc/billing-and-payments/

DOC-2684: Update refunds policy statement

---

content/rs/databases/connect/test-client-connectivity.md

DOC-2150
[Staged preview](https://docs.redis.com/staging/DOC-2150/rs/databases/connect/test-client-connectivity/)

RS: Fix outdated test DB connections examples

---

content/rs/databases/connect/supported-clients-browsers.md

DOC-2658
[Staged preview](https://docs.redis.com/staging/DOC-2658/rs/databases/connect/supported-clients-browsers/#discovery-service)

RS: Update recommended clients with Sentinel support

---

content/rs/references/cli-utilities/rladmin/node/snapshot.md

DOC-1610
[Staged preview](https://docs.redis.com/staging/DOC-1610/rs/references/cli-utilities/rladmin/node/snapshot/)

RS: More info for rladmin node snapshot reference

---

content/rs/networking/port-configurations.md

DOC-1546 & DOC-2636
[Staged preview](https://docs.redis.com/staging/DOC-1546-DOC-2636/rs/networking/port-configurations/)

RS: Add Prometheus ports 8000 & 9090 to ports table

---

content/rs/references/cli-utilities/rladmin/cluster/create.md
content/rs/references/cli-utilities/rladmin/cluster/join.md

- [rladmin cluster create](https://docs.redis.com/staging/DOC-1520/rs/references/cli-utilities/rladmin/cluster/create/)
- [rladmin cluster join](https://docs.redis.com/staging/DOC-1520/rs/references/cli-utilities/rladmin/cluster/join/)

RS: Multiple IP addresses syntax in rladmin cluster create/join reference

---

content/rs/references/cli-utilities/rladmin/cluster/config.md
content/rs/references/rest-api/objects/cluster/_index.md
content/rs/references/rest-api/objects/node.md
content/rs/references/rest-api/requests/license/_index.md
content/rs/release-notes/rs-7-2-4-releases/_index.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-tba.md

- [Release notes](https://docs.redis.com/staging/release-rs-everest-sept/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-tba/) - build number and MD5 checksums to be added when available
- [rladmin cluster config](https://docs.redis.com/staging/release-rs-everest-sept/rs/references/cli-utilities/rladmin/cluster/config/) - added `reserved_ports`
- [Cluster REST API object](https://docs.redis.com/staging/release-rs-everest-sept/rs/references/rest-api/objects/cluster/) - added `reserved_ports`
- [License REST API request](https://docs.redis.com/staging/release-rs-everest-sept/rs/references/rest-api/requests/license/) - added `ram_shards_in_use` and `flash_shards_in_use`

RS 7.2.4 September maintenance release

---

content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md

[Staged preview](https://docs.redis.com/staging/rs-rn-cves-aug/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52/#security)

RS: Update CVEs in 7.2.4-52 release notes

---

content/rc/cloud-integrations/aws-marketplace/aws-bedrock.md

Staging link: https://docs.redis.com/staging/DOC-2666/rc/cloud-integrations/aws-marketplace/aws-bedrock/

DOC-2666: Amazon Bedrock Integration Phase 1

---

content/rs/clusters/_index.md

[Staged preview](https://docs.redis.com/staging/DOC-2701/rs/)

RS: Moved clusters above databases in ToC

---

content/rs/references/cli-utilities/redis-cli/_index.md

DOC-2699
[Staged preview](https://docs.redis.com/staging/DOC-2699/rs/references/cli-utilities/redis-cli/#connect-over-tls)

RS: Copy certificate to client machine for redis-cli mTLS

---

content/rs/networking/multi-ip-ipv6.md
content/rs/references/cli-utilities/rladmin/node/addr.md

DOC-2565
[Staged preview](https://docs.redis.com/staging/DOC-2565/rs/networking/multi-ip-ipv6/#change-internal-ip-address)

RS: New change internal IP procedure

---

content/embeds/supported-platforms-embed.md
content/rs/references/supported-platforms.md

[Staged preview](https://docs.redis.com/staging/DOC-2750/rs/references/supported-platforms/)

RS: Copy supported platforms to references & update limitations

---

content/rdi/installation/install-k8s.md

As described in the [corresponding ticket](https://redislabs.atlassian.net/browse/RDSC-1514) - requested by clients.

RDSC-1514: Convert RDI CLI pod definition to deployment

---

content/embeds/k8s-admission-webhook-cert.md
content/kubernetes/delete_custom_resources.md
content/kubernetes/re-clusters/multi-namespace.md

- k8s-admission-webhook: add webhook.yaml file link
- update redb-role definition
- according to https://github.com/RedisLabs/redis-enterprise-k8s-docs/tree/master/multi-namespace-redb
- docs review
**The changes effect 6.4-build and master branch.**

docs review

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md

Staging link: https://docs.redis.com/staging/fix-k8s-notes/kubernetes/release-notes/7-2-4-releases/7-2-4-7/

K8s maint release in Oct instead of Sept

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md

Staging link: https://docs.redis.com/staging/fix-k8s-notes/kubernetes/release-notes/7-2-4-releases/7-2-4-7/

Fix RS build number in K8s release notes

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md

Staging link: https://docs.redis.com/staging/fix-k8s-notes/kubernetes/release-notes/7-2-4-releases/

K8s: Change Release note weights

---

content/rs/references/rest-api/requests/bdbs/stats/last.md

DOC-2746
[Staged preview](https://docs.redis.com/staging/DOC-2746/rs/references/rest-api/requests/bdbs/stats/last/)

RS: Fixed /bdbs/stats/last/uid endpoint

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md

https://docs.redis.com/staging/RN-warning-OS-upgrade/kubernetes/release-notes/7-2-4-releases/7-2-4-7/

K8s: add upgrade RHEL note

---

content/kubernetes/delete-custom-resources.md
content/kubernetes/delete_custom_resources.md
content/kubernetes/deployment/container-images.md
content/kubernetes/re-databases/db-controller.md

Jira: DOC-2772 DOC-2776
Staged preview: https://docs.redis.com/staging/DOC-2772/kubernetes/deployment/container-images/
https://docs.redis.com/staging/DOC-2772/kubernetes/delete-custom-resources/

K8s small doc bugs

---

content/rdi/reference/data-transformation-block-types/lookup.md
content/rdi/reference/debezium/oracle.md

This pull request updates the autogenerated docs.

RDSC-1550-change-value-of-property-log-mining-transaction-retention-ms: Auto generated

---

content/rs/references/cli-utilities/rladmin/tune.md

DOC-2771
[Staged preview](https://docs.redis.com/staging/DOC-2771/rs/references/cli-utilities/rladmin/tune/#tune-proxy)

RS: Value ranges for rladmin tune proxy parameters

---

content/rs/references/rest-api/encryption.md
content/rs/security/admin-console-security/_index.md

- [Encrypt REST API requests](https://docs.redis.com/staging/DOC-1153/rs/references/rest-api/encryption/)
- [Admin console security](https://docs.redis.com/staging/DOC-1153/rs/security/admin-console-security/)

RS: Reorg REST API encryption & admin console security edits

---

content/rdi/reference/config-yaml-reference.md

This pull request updates the autogenerated docs.

RDSC-1614 - Header appears twice in `config.yaml` reference document: Auto generated

---

content/kubernetes/reference/supported_k8s_distributions.md

DOC-2803
[Staged preview](https://docs.redis.com/staging/DOC-2803/kubernetes/reference/supported_k8s_distributions#rancher)

K8s: correct rancher table format

---

content/ri/_index.md

https://docs.redis.com/staging/DOC-2933-deprecate-RI/ri/

DOC-2933: mark RI pages as deprecated

---

content/rc/databases/migrate-databases.md

Staging link: https://docs.redis.com/staging/DOC-2769/rc/databases/migrate-databases/#sync-using-active-passive

DOC-2769: replica of between different SM account require open a support ticket 

---

content/embeds/supported-platforms-embed.md
content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md

- [Release notes](https://docs.redis.com/staging/release-rs-diablo-oct/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba/)
- [Supported platforms](https://docs.redis.com/staging/release-rs-diablo-oct/rs/references/supported-platforms/)

RS 6.4.2 October maintenance release

---

content/rc/changelog/november-2023.md

Staging link: https://docs.redis.com/staging/DOC-3029/rc/changelog/november-2023

DOC-3029: Add Heroku message to November changelog

---

content/rc/databases/back-up-data.md

https://redislabs.atlassian.net/browse/DOC-3002

DOC-3002 Docs Bash feedback.

---

content/rc/cloud-integrations/aws-marketplace/aws-bedrock/set-up-redis.md
content/ri/_index.md
content/rs/references/cli-utilities/redis-cli/_index.md

JIRA: https://redislabs.atlassian.net/browse/DOC-3111

DOC-3111: RC/RI/RS: fix broken links to redis.io

---

content/kubernetes/active-active/edit-rerc.md

Jira: DOC-2796
Staged preview: https://docs.redis.com/staging/DOC-2796/kubernetes/active-active/edit-rerc/

Add info to RERC description DOC-2796

---

content/kubernetes/active-active/create-reaadb.md

Jira: DOC-3054
Staging: https://docs.redis.com/staging/DOC-3054/kubernetes/active-active/create-reaadb/

K8s: Sharding disabled with 1 shard REAADB

---

content/rs/clusters/remove-node.md
content/rs/installing-upgrading/upgrading/upgrade-os.md
content/stack/install/add-module-to-cluster.md

[DOC-1173](https://redislabs.atlassian.net/browse/DOC-1173) [DOC-901](https://redislabs.atlassian.net/browse/DOC-901)
[Staged preview](https://docs.redis.com/staging/DOC-2800/rs/installing-upgrading/upgrading/upgrade-os/)
[DOC-1173]: https://redislabs.atlassian.net/browse/DOC-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-901]: https://redislabs.atlassian.net/browse/DOC-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS: OS rolling upgrade

---

content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md

[Staged preview](https://docs.redis.com/staging/fix-link/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64/#enhancements)

RS: Add anchor to cluster config REST API link

---

content/kubernetes/delete-custom-resources.md

Jira: DOC-3045
Staged preview: https://docs.redis.com/staging/DOC-3045/kubernetes/delete-custom-resources/

K8s: delete REDB before namespace

---

content/rc/cloud-integrations/pulumi/_index.md
content/rc/cloud-integrations/terraform/_index.md

DOC-3031
https://docs.redis.com/staging/DOC-3031/rc/cloud-integrations/terraform
https://docs.redis.com/staging/DOC-3031/rc/cloud-integrations/pulumi

DOC-3031: RC: Integrations - terraform - missing sources and resources

---

content/rc/accounts/_index.md

https://redislabs.atlassian.net/browse/DOC-2921

DOC-2921 Corrected link text on Accounts and settings landing page.

---

content/rc/cloud-integrations/prometheus-integration.md

https://redislabs.atlassian.net/browse/DOC-3085

DOC-3085 Update the Title to include Grafana.

---

content/rs/installing-upgrading/install/prepare-install/prepare-flash.md

https://redislabs.atlassian.net/browse/DOC-2827

DOC-2827 Corrected ROF to Auto Tiering.

---

content/rc/billing-and-payments.md

Staging link: https://docs.redis.com/staging/DOC-2906/rc/billing-and-payments/

DOC-2906: Bug Bash Billing and Payments changes

---

content/rdi/reference/cli/redis-di-scaffold.md

This pull request updates the autogenerated docs.

RDSC-1684-write-behind-should-support-db-2: Auto generated

---

content/rs/databases/import-export/import-data.md

DOC-2686
[Staged preview](https://docs.redis.com/staging/DOC-2686/rs/databases/import-export/import-data/#google-cloud-storage)

RS: Role/permissions example for importing data from Google Cloud storage

---

content/rs/references/rest-api/objects/module.md

DOC-3081
[Staged preview](https://docs.redis.com/staging/DOC-3081/rs/references/rest-api/objects/module/)

RS: Added capability_name field to module REST API object reference

---

content/rs/installing-upgrading/creating-support-package.md
content/rs/references/rest-api/requests/debuginfo/_index.md
content/rs/references/rest-api/requests/debuginfo/all/_index.md
content/rs/references/rest-api/requests/debuginfo/all/bdb.md
content/rs/references/rest-api/requests/debuginfo/node/_index.md
content/rs/references/rest-api/requests/debuginfo/node/bdb.md

[DOC-3040](https://redislabs.atlassian.net/browse/DOC-3040) [DOC-3039](https://redislabs.atlassian.net/browse/DOC-3039)
- [Create support package](https://docs.redis.com/staging/DOC-3040/rs/installing-upgrading/creating-support-package/#rest-api-method)
- Debuginfo REST API references:
- [Debuginfo requests index](https://docs.redis.com/staging/DOC-3040/rs/references/rest-api/requests/debuginfo/)
- [/debuginfo/all](https://docs.redis.com/staging/DOC-3040/rs/references/rest-api/requests/debuginfo/all)
- [/debuginfo/all/bdb](https://docs.redis.com/staging/DOC-3040/rs/references/rest-api/requests/debuginfo/all/bdb)
- [/debuginfo/node](https://docs.redis.com/staging/DOC-3040/rs/references/rest-api/requests/debuginfo/node)
- …

RS: Debug info REST API requests to create support packages

---

content/rs/databases/import-export/import-data.md

DOC-3158
[Staged preview](https://docs.redis.com/staging/DOC-3158/rs/databases/import-export/import-data/#local-mount-point)

RS: Added missing requirement for local mount point imports

---

content/rs/security/certificates/create-certificates.md

DOC-3093
[Staged preview](https://docs.redis.com/staging/DOC-3093/rs/security/certificates/create-certificates/#create-certificates)
Note: I will open similar PRs for 6.4 and 6.2 docs.

RS 7.2: Added example to sign private key with CA

---

content/rs/security/certificates/create-certificates.md

[DOC-3093](https://redislabs.atlassian.net/browse/DOC-3093)
[Staged preview](https://docs.redis.com/staging/DOC-3093-v6.2/rs/security/certificates/create-certificates/#create-certificates)
Note: I will open similar PRs for 7.2 and 6.4 docs.
[DOC-3093]: https://redislabs.atlassian.net/browse/DOC-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS 6.2: Added example to sign private key with CA

---

content/rs/databases/connect/_index.md

https://redislabs.atlassian.net/browse/DOC-3021
preview: https://docs.redis.com/staging/DOC-3021/rs/databases/connect/

DOC-3021 fixed white space in python example.

---

content/embeds/shard-placement-intro.md

https://redislabs.atlassian.net/browse/DOC-3020
Preview: https://docs.redis.com/staging/DOC-3020/rs/databases/configure/shard-placement/

DOC-3020 Fixed typo in rackzone awareness.

---

content/rs/databases/connect/test-client-connectivity.md

https://redislabs.atlassian.net/browse/DOC-3023
Preview: https://docs.redis.com/staging/DOC-3023/rs/databases/connect/test-client-connectivity/

DOC-3023 Fixed python example.

---

content/rs/databases/connect/test-client-connectivity.md

https://redislabs.atlassian.net/browse/DOC-3022
Preview: https://docs.redis.com/staging/DOC-3022/rs/databases/connect/test-client-connectivity/

DOC-3022 Removed white space in function call.

---

content/rs/databases/configure/database-persistence.md

https://redislabs.atlassian.net/browse/DOC-2965
Preview: https://docs.redis.com/staging/DOC-2965/rs/databases/configure/database-persistence/

DOC-2965 updated Redis on Flash reference.

---

content/embeds/cluster-setup.md

https://redislabs.atlassian.net/browse/DOC-2870

Added warning about cluster.local preventing DNS.

---

content/rs/installing-upgrading/uninstalling.md

https://redislabs.atlassian.net/browse/DOC-2865

DOC-2865 Added file locaation details for RS uninstall script.

---

content/embeds/supported-platforms-embed.md

https://redislabs.atlassian.net/browse/DOC-2822

DOC-2822 Removed duplicate content.

---

content/rs/installing-upgrading/install/plan-deployment/persistent-ephemeral-storage.md

https://redislabs.atlassian.net/browse/DOC-2823

DOC-2823 Fixed phrasing to improve clarity per docs bash feedback.

---

content/rs/databases/connect/troubleshooting-guide.md

https://redislabs.atlassian.net/browse/DOC-3025
preview: https://docs.redis.com/staging/DOC-3025/rs/databases/connect/troubleshooting-guide/

DOC-3025 added port, password, and host where missing in cli calls.

---

content/rs/databases/active-active/synchronization-mode.md
content/rs/databases/configure/proxy-policy.md
content/rs/databases/configure/replica-ha.md
content/rs/installing-upgrading/creating-support-package.md
content/rs/references/compatibility/resp.md

https://redislabs.atlassian.net/browse/DOC-3008
preview: 
https://docs.redis.com/staging/DOC-3008/rs/databases/active-active/synchronization-mode.md
https://docs.redis.com/staging/DOC-3008/rs/databases/configure/proxy-policy.md
https://docs.redis.com/staging/DOC-3008/rs/databases/configure/replica-ha/
https://docs.redis.com/staging/DOC-3008/rs/installing-upgrading/creating-support-package.md
https://docs.redis.com/staging/DOC-3008/rs/references/compatibility/resp/

DOC-3008 Fix consistency with db name and db id variables in examples.

---

content/rs/databases/configure/_index.md

https://redislabs.atlassian.net/browse/DOC-2947
preview: https://docs.redis.com/staging/DOC-2947/rs/databases/configure/#config-settings

DOC-2947 Corrected shard policy name.

---

content/rs/databases/configure/_index.md

https://redislabs.atlassian.net/browse/DOC-2946
Preview: https://docs.redis.com/staging/DOC-2946/rs/databases/configure/#config-settings

DOC-2046 Fixed RoF reference.

---

content/rs/databases/configure/replica-ha.md

https://redislabs.atlassian.net/browse/DOC-3007
Preview: https://docs.redis.com/staging/DOC-3007/rs/databases/configure/replica-ha/

DOC-3007 Corrected phrasing for clarity.

---

content/rs/databases/connect/troubleshooting-guide.md

https://redislabs.atlassian.net/browse/DOC-3024
Preview: https://docs.redis.com/staging/DOC-3024/rs/databases/connect/troubleshooting-guide/

DOC-3024 Addressed consistency with TLS use in commands.

---

content/rs/databases/configure/oss-cluster-api.md

https://redislabs.atlassian.net/browse/DOC-3035
preview: https://docs.redis.com/staging/DOC-3035/rs/databases/configure/oss-cluster-api/

Doc 3035 OSS Cluster API config clarity

---

content/rs/installing-upgrading/upgrading/upgrade-cluster.md
content/rs/installing-upgrading/upgrading/upgrade-database.md

Preview: https://docs.redis.com/staging/RS---bug-bash---upgrade-cluster/rs/installing-upgrading/upgrading/upgrade-cluster/
Includes: DOC-2932 DOC-2937 DOC-2934

RS: bug bash - upgrade cluster

---

content/rs/security/access-control/manage-users/add-users.md

[Staged preview](https://docs.redis.com/staging/fix-img-width/rs/security/access-control/manage-users/add-users/) - step 3 image

RS: Reduce image width

---

content/rs/clusters/configure/rack-zone-awareness.md

DOC-2882
[Staged preview](https://docs.redis.com/staging/DOC-2882/rs/clusters/configure/rack-zone-awareness/#node-layout-guidelines)

RS: Avoid node majority in one availability zone

---

content/rs/installing-upgrading/upgrading/upgrade-database.md

DOC-3155
[Staged preview](https://docs.redis.com/staging/DOC-3155/rs/installing-upgrading/upgrading/upgrade-database/#upgrade-prerequisites)

RS: Add note & link to RESP3 client prereqs from DB upgrade prereqs

---

content/rs/networking/port-configurations.md

DOC-3144
[Staged preview](https://docs.redis.com/staging/DOC-3144/rs/networking/port-configurations/#ports-and-port-ranges-used-by-redis-enterprise-software)

RS: Add port 9125 to metrics ports

---

content/rs/networking/port-configurations.md

DOC-3113
[Staged preview](https://docs.redis.com/staging/DOC-3113/rs/networking/port-configurations/#reserve-ports)

RS: Reserved ports rladmin & REST API examples

---

content/rs/references/cli-utilities/rladmin/status.md

DOC-3137
[Staged preview](https://docs.redis.com/staging/DOC-3137/rs/references/cli-utilities/rladmin/status/#status-modules)

RS: Add rladmin status modules reference & missing parameter for rladmin status endpoints

---

content/tas/_index.md

DOC-3190
preview: https://docs.redis.com/staging/DOC-3190/tas

TAS 6.2.1865 release notes

---

content/embeds/port-53.md

Preview: https://docs.redis.com/staging/RS-bug-bash-ubuntu-dns/rs/installing-upgrading/install/prepare-install/port-availability/
Includes: DOC-2826

DOC-2826 add a note

---

content/rc/databases/back-up-data.md

GCP backup procedure update

---

content/rs/security/encryption/tls/enable-tls.md

DOC-3095
[Staged preview](https://docs.redis.com/staging/DOC-3095/rs/security/encryption/tls/enable-tls/)

RS: Reconnect clients to apply TLS changes

---

content/kubernetes/release-notes/6-4-2-releases/6-4-2-8-dec23.md
content/kubernetes/release-notes/6-4-2-releases/6-4-2-8-nov23.md
content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md

DOC-3169
Staged preview: https://docs.redis.com/staging/DOC-3169/kubernetes/release-notes/6-4-2-releases/6-4-2-8-dec23/

K8s: 6.4.2-8 maint 2 release notes

---

content/rs/clusters/monitoring/nagios-plugin.md

DOC-2945 
[Staged preview](https://docs.redis.com/staging/DOC-2945/rs/clusters/monitoring/nagios-plugin/)
This PR replaces #2717, which was closed without merging due to merge conflicts.

RS: Banner - Nagios plugin is retired

---

content/rc/databases/migrate-databases.md
content/rc/subscriptions/upgrade-fixed-flexible.md
content/rs/databases/import-export/replica-of/create.md

Tickets: DOC-3201 DOC-3200
Staging link: 
https://docs.redis.com/staging/DOC-3201/rc/databases/migrate-databases/#general-active-passive-syncing-process
https://docs.redis.com/staging/DOC-3201/rs/databases/import-export/replica-of/create/#configure-replica-of

RC/RS: Active-Passive eviction/expiration limitation

---

content/rc/cloud-integrations/gcp-marketplace/team-management.md

Ticket: DOC-3216
Staging: https://docs.redis.com/staging/DOC-3216/rc/cloud-integrations/gcp-marketplace/team-management/

RC: Add editor role to 3pic management page

---

content/rc/changelog/december-2023.md

Staging link: https://docs.redis.com/staging/changelog-fix/rc/changelog/december-2023

Fix december changelog

---

content/embeds/k8s-admission-webhook-cert.md
content/kubernetes/deployment/quick-start.md
content/kubernetes/recommendations/node-selection.md

Update name of placeholder in all places, fix typo
Discovered while testing on GKE

K8s: OPERATOR_NAMESPACE placeholder

---

content/rs/databases/connect/_index.md
content/rs/databases/connect/test-client-connectivity.md
content/rs/installing-upgrading/quickstarts/docker-quickstart.md
content/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md

DOC-3199
- [Redis Enterprise Software quickstart](https://docs.redis.com/staging/DOC-3199/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart/)
- [Docker quickstart](https://docs.redis.com/staging/DOC-3199/rs/installing-upgrading/quickstarts/docker-quickstart/)
- [Databases > Connect index page](https://docs.redis.com/staging/DOC-3199/rs/databases/connect/)
- [Databases > Test connection](https://docs.redis.com/staging/DOC-3199/rs/databases/connect/test-client-connectivity/)

RS: Quickstart and test connection edits

---

content/rc/subscriptions/upgrade-fixed-flexible.md

Ticket: DOC-3235
Staging link: https://docs.redis.com/staging/DOC-3235/rc/subscriptions/upgrade-fixed-flexible/#migrate-databases

RC: Specify removing the source database in the upgrade from Fixed->Flexible docs

---

content/rc/databases/view-edit-database.md

Ticket: DOC-3267
Staging link: https://docs.redis.com/staging/DOC-3267/rc/databases/view-edit-database

RC: Verify which database settings can be changed and update edit database table

---

content/kubernetes/reference/supported_k8s_distributions.md

K8s: typo fix

---

content/kubernetes/active-active/_index.md

K8s: clarify wording REAADB limitation

---

content/rdi/installation/debezium-server-deployment.md
content/rdi/installation/install-k8s.md
content/rdi/installation/pacemaker.md

Server image.
pulling the image from quay instead of Docker

Add tags to all instances referencing the Debezium

---

content/rc/databases/delete-database.md

Ticket: DOC-3282
Staging link: https://docs.redis.com/staging/DOC-3282/rc/databases/delete-database/

RC: Remove incorrect sentence from Redis Cloud databases page

---

content/rs/clusters/configure/rack-zone-awareness.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md

DOC-3257
- [Rack-zone awareness](https://docs.redis.com/staging/DOC-3257/rs/clusters/configure/rack-zone-awareness/#enable-database-rack-zone-awareness)
- [7.2.4 Nov release notes](https://docs.redis.com/staging/DOC-3257/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92/#enhancements)

RS: Removed rack-zone awareness UI enhancement from 7.2.4

---

content/rs/databases/import-export/replica-of/_index.md

DOC-3290
[Staged preview](https://docs.redis.com/staging/DOC-3290/rs/databases/import-export/replica-of/#active-passive-replication-backlog)

RS: Fix DB replication backlog link in Replica Of doc

---

content/rc/subscriptions/view-fixed-subscription.md
content/rc/subscriptions/view-flexible-subscription.md

Staging link: https://docs.redis.com/staging/fix-view-titles/rc/subscriptions/

RC: Change titles of the view subscription pages

---

content/rs/release-notes/rs-7-4-2-releases/_index.md
content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-tba.md

DOC-2982 
[Staged preview](https://docs.redis.com/staging/DOC-2982/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-tba/)

RS: 7.4.2 Fuji release notes draft

---

content/kubernetes/re-clusters/cluster-recovery.md

change --force to --now to avoid force deleting pods. 
DOC-3198

K8s: change delete pods argument to avoid force delete

---

content/kubernetes/active-active/create-reaadb.md
content/kubernetes/active-active/global-config.md

DOC-3195
DOC-3197
https://docs.redis.com/staging/DOC-3195/kubernetes/active-active/global-config/
https://docs.redis.com/staging/DOC-3195/kubernetes/active-active/create-reaadb/

K8s: Fix REAAD links and tlsMode example

---

content/rc/cloud-integrations/aws-cloud-accounts/iam-resources/aws-console.md
content/rc/security/aws-transit-gateway.md

Ticket: DOC-2162
Staging link: https://docs.redis.com/staging/DOC-2162/rc/security/aws-transit-gateway/#prerequisites

RC: Update external account permissions for TransitGateway

---

content/tas/service-broker/_index.md
content/tas/service-broker/installing.md
content/tas/service-broker/release-notes.md

DOC-3191
Preview: https://docs.redis.com/staging/DOC-3191/tas/service-broker/
Final URL: 
- https://docs.redis.com/latest/tas/service-broker/
- https://docs.redis.com/latest/tas/service-broker/installing/
- https://docs.redis.com/latest/tas/service-broker/release-notes/

Tanzu service broker docs

---

content/rs/clusters/configure/sync-clocks.md

DOC-3320
[Staged preview](https://docs.redis.com/staging/DOC-3320/rs/clusters/configure/sync-clocks/#rhel-7)
New links were approved in Slack.

RS: Fix broken RHEL links

---

content/rs/references/rest-api/requests/bootstrap/_index.md

DOC-2654
[Staged preview](https://docs.redis.com/staging/DOC-2654/rs/references/rest-api/requests/bootstrap/#get-response)

RS: Add recovering_cluster state to bootstrap REST API reference

---

content/rc/databases/back-up-data.md

Ticket: DOC-982
Staging link: https://docs.redis.com/staging/DOC-982/rc/databases/back-up-data/#set-up-backup-storage-locations

RC: Backup data: Verify region support for cloud backups

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

DOC-3076
Staged preview: https://docs.redis.com/staging/DOC-3076-6.4/rs/

RS 7.4 version selector updates - 6.4-build branch

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

[DOC-3076](https://redislabs.atlassian.net/browse/DOC-3076)
Staged preview: https://docs.redis.com/staging/DOC-3076-6.2/rs/
[DOC-3076]: https://redislabs.atlassian.net/browse/DOC-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS 7.4 version selector updates - 6.2-build branch

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

[DOC-3076](https://redislabs.atlassian.net/browse/DOC-3076)
Staged preview: https://docs.redis.com/staging/DOC-3076-6.0/rs/
[DOC-3076]: https://redislabs.atlassian.net/browse/DOC-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS 7.4 version selector updates - 6.0-build branch

---

website.json

Removed a few old S3 redirects since we've reached the limit.

Removed a few old S3 redirects

---

content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md

Jira: DOC-3312
https://docs.redis.com/staging/DOC-3312/kubernetes/release-notes/6-4-2-releases/6-4-2-8/#known-limitations

K8s: Gears cluster recovery bug 

---

content/rc/changelog/february-2024.md

https://docs.redis.com/staging/DOC-3352-fix/rc/changelog/february-2024/

RC: Add more info for CIDR overlap

---

content/rc/compatibility.md

Staging link: https://docs.redis.com/staging/DOC-3164-fix/rc/compatibility/#resp-compatibility

RC: Point to edit flow for RESP compatibility

---

content/rs/installing-upgrading/quickstarts/docker-quickstart.md

[Staged preview](https://docs.redis.com/staging/fix-relrefs/rs/installing-upgrading/quickstarts/docker-quickstart/)

RS: Fixed broken relrefs

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

K8s swordfish version selector 7.2 build

---

layouts/404.html
layouts/partials/flex/body-beforecontent.html
layouts/partials/flex/scripts.html

K8s Swordfish version selector 7.4 for 6.4 build

---

content/kubernetes/re-clusters/multi-namespace.md

K8s: remove consumer-ns from RoleBinding

---

content/rc/changelog/february-2024.md

Tickets: DOC-3363 DOC-3364
Staging link: https://docs.redis.com/staging/DOC-3363/rc/changelog/february-2024/

RC: Feb 25th changelog changes

---

content/rs/clusters/configure/cluster-settings.md

DOC-3202
[Staged preview](https://docs.redis.com/staging/DOC-3202/rs/clusters/configure/cluster-settings/#set-time-zone)

RS: Clarify time zone description

---

content/embeds/supported-platforms-embed.md

[DOC-3475](https://redislabs.atlassian.net/browse/DOC-3475)
[Staged preview](https://docs.redis.com/staging/DOC-3475/rs/references/supported-platforms/) - adapted from Brad's draft
[DOC-3475]: https://redislabs.atlassian.net/browse/DOC-3475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS: Updated supported platforms & OS compatibility policy

---

content/rs/installing-upgrading/upgrading/upgrade-active-active.md

DOC-3356
[Staged preview](https://docs.redis.com/staging/DOC-3356/rs/installing-upgrading/upgrading/upgrade-active-active/)

RS: Clarify RS v5.4.2 & later use CRDB protocol version 1

---

content/rs/clusters/configure/license-keys.md

DOC-3471
[Staged preview](https://docs.redis.com/staging/DOC-3471/rs/clusters/configure/license-keys/#expired-cluster-license)

RS: Updates for expired cluster license

---

content/rs/installing-upgrading/install/customize-install-directories.md
content/rs/installing-upgrading/upgrading/upgrade-os.md

DOC-3232 
- [Upgrade operating system > Prerequisites step 3](https://docs.redis.com/staging/DOC-3232/rs/installing-upgrading/upgrading/upgrade-os/)
- [Customize installation directories](https://docs.redis.com/staging/DOC-3232/rs/installing-upgrading/install/customize-install-directories/)

RS: Upgrade OS with custom directories

---

content/kubernetes/release-notes/7-2-4-releases/7-2-4-12-03-24.md

Jira: DOC-3494
Preview: https://docs.redis.com/staging/kubernetes/release-notes/7-2-4-releases/7-2-4-12-03-24/

K8s: Roosevelt maint 1

---

content/kubernetes/networking/ingressorroutespec.md

Jira: DOC-3162
Staging: https://docs.redis.com/staging/DOC-3162/kubernetes/networking/ingressorroutespec/

K8s: correct ingress controller links

---

content/rs/references/rest-api/objects/cluster_settings.md

DOC-3489
[Staged preview](https://docs.redis.com/staging/DOC-3489/rs/references/rest-api/objects/cluster_settings/)

RS: Add persistent_node_removal to cluster settings REST API object

---

content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md

DOC-3497
- [6.4.2-43 resolved issues](https://docs.redis.com/staging/DOC-3497/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43/#resolved-issues)
- [7.2.4-52 resolved issues](https://docs.redis.com/staging/DOC-3497/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52/#resolved-issues)

RS: Moved resolved issue RS62552 to correct release notes

---

content/rs/references/rest-api/objects/module.md

DOC-3316
[Staged preview](https://docs.redis.com/staging/DOC-3316/rs/references/rest-api/objects/module/)

RS: Improve min_redis_pack_version & min_redis_version descriptions

---

content/rs/references/rest-api/objects/proxy.md
content/rs/references/rest-api/requests/proxies/_index.md

DOC-3491
[Staged preview](https://docs.redis.com/staging/DOC-3491/rs/references/rest-api/requests/proxies/)

RS: /v1/proxies REST API reference

---

content/rc/databases/_index.md

Ticket: DOC-3390
Staging link: https://docs.redis.com/staging/DOC-3390/rc/databases

RC New Packaging: Databases landing page

---

content/rc/subscriptions/maintenance/_index.md
content/rc/subscriptions/maintenance/set-maintenance-windows.md

DOC-3496
Staging link: https://docs.redis.com/staging/DOC-3496/rc/subscriptions/maintenance/

RC: Maintenance windows | update docs

---

content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md

DOC-3554
[Staged preview](https://docs.redis.com/staging/DOC-3554/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103/)

RS: Copy RS 6.4.2-103 release notes to 6.4 version branch

---

content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
content/rs/release-notes/rs-7-2-4-releases/_index.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
content/rs/security/certificates/ocsp-stapling.md

DOC-3543
- [All 7.2.4 release notes](https://docs.redis.com/staging/DOC-3543-7.2/rs/release-notes/rs-7-2-4-releases/)
- [6.4.2-103 release notes](https://docs.redis.com/staging/DOC-3543-7.2/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103/)

RS: Copy supported platforms snapshot release notes disclaimer to 7.2 version branch

---

content/kubernetes/release-notes/7-4-2-releases/7-4-2-03-24.md
content/kubernetes/release-notes/7-4-2-releases/7-4-2-2.md
content/kubernetes/release-notes/7-4-2-releases/_index.md

DOC-3359
- https://docs.redis.com/staging/DOC-3559/kubernetes/release-notes/7-4-2-releases/
- https://docs.redis.com/staging/DOC-3559/kubernetes/release-notes/7-4-2-releases/7-4-2-03-24/

K8s: swordfish maint 1

---

config.toml
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

Staged preview: https://docs.redis.com/staging/DOC-3539-staging-dev/
This PR is just to add the banner to the dev staged preview since I think we have links to it in the README and in the contribution guide. So only pushing it to `master` should handle this case.
Please do not push to `latest` though.

staging-dev: sitewide archived content banner

---

config.toml
layouts/partials/banner.html
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

Staged preview: https://docs.redis.com/staging/DOC-3539-6.0/

6.0: sitewide archived content banner

---

config.toml
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

Staged preview: https://docs.redis.com/staging/DOC-3539-rdi-preview/

rdi-preview: sitewide archived content banner

---

config.toml
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

Staged preview: https://docs.redis.com/staging/DOC-3539-6.2/

6.2: sitewide archived content banner

---

config.toml
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

Staged preview: https://docs.redis.com/staging/DOC-3539-6.4/

6.4: sitewide archived content banner

---

config.toml
layouts/partials/flex/body-beforecontent.html
static/theme-flex/style.css

DOC-3539
Staged preview: https://docs.redis.com/staging/DOC-3539-7.2/

7.2: sitewide archived content banner
