RedisLabs/redislabs-docs

- content/rs/references/cli-reference/rladmin.md
This is a first attempt. Some additional formatting is required.
> Attempt to copy rladmin help in to this doc

- .circleci/config.yml
Reverts RedisLabs/redislabs-docs#54
> Revert "Exclude "index.html" from AWS copy"

- static/theme-flex/style.css
> Make footer full width

- layouts/partials/navigation.html
Added Redis For Dummies, Move/changed the e-book from Community to Resources and named it Redis e-Book, added Licenses to Community, and added Compliance to Company
> Updated Menu links

- content/rv/how-to/creating-aws-user-redis-enterprise-vpc.md
Add ability to change password and add cloudwatch readonly permissions for monitoring.
> Update RV User IAM Policy - see RED-25041

- resources/_gen/assets/css/theme-flex/style.css_8848f55d07695b7ff7188138f23d69e3.json
- static/css/nucleus.css
- static/theme-flex/style.css
- themes/docdock/static/js/search.js
This adds a few words of context (3 before and 3 after the search term) for items displayed in the search results.
> Add context text for search results

- content/rs/installing-upgrading/upgrading.md
The section about multi proxy is confusing the customers, as they think to move to multi proxy configuration just for the upgrade purpose.
> multi proxy is confusing the customers

- content/rc/how-to/importing-dataset-redis-cloud.md
Adding instructions on how to import from GCP and Azure
> Adding back GCS and ABS instructions

- content/rs/administering/troubleshooting/cluster-recovery.md
update required rladmin options, font consistency, and general cleanup
> Add examples and missing parameters to cluster recovery

- content/rs/administering/security/ldap-integration.md
make the two example config files match
> Add ldap_bind_dn to example saslauthd.conf file

- static/theme-flex/custom.js
- static/theme-flex/style.css
This PR fixes the issue of header covering the title of the anchor link.
> Page anchor position

- content/rs/administering/designing-production/networking/port-configurations.md
Adding ports that are used for RS
> Add port 9081 to list of required ports

- content/rs/getting-started/docker/getting-started-docker.md
> Map port 9443 in Docker getting started

- content/rs/developing/crdbs/developing-lists-crdb.md
Added a couple of missing 't's
> Fixed minor typos in developing-lists-crdb.md

- content/rs/developing/modules/_index.md
Changed to four modules as detailed.
> Fix modules count on _index.md

- content/rc/securing-redis-cloud-connections.md
Updated filenames from garantia* to redislabs*
> Update to securing-redis-cloud-connections.md

- content/rv/how-to/importing-data-database.md
The rdb file path format lost hostname , i add "hostname" to it
> add "hostname" to URL format

- content/rs/administering/database-operations/administering-database-operations-importing-data.md
- content/rs/developing/crdbs/_index.md
- content/rs/developing/crdbs/strings.md
- content/rs/installing-upgrading/upgrading.md
Reverts RedisLabs/redislabs-docs#302
> Revert "RED-26845 Update for register-counter changes in 5.4.2"

- content/rs/administering/designing-production/security/client-connections.md
> Fix alias to redirect from /rs/administering/security/client-connections

- content/rs/developing/crdbs/_index.md
the  key result shoud on a new line, that looks like more clearly
> Move key result to new line

- layouts/partials/flex/scripts.html
- static/theme-flex/style.css
This fixess [issue #335](https://github.com/RedisLabs/redislabs-docs/issues/335).
> Fix version dropdown opening #335

- content/rs/administering/database-operations/create-crdb.md
-- https://<cluster_URL>:8080
8080 is HTTP CNM port. Should be 9443 for SSL
> create CRDB | Participant URL HTTPS port change

- content/rs/installing-upgrading/configuring-aws-instances.md
Ben, please check that the link indeed works before committing.
This resolves RED-28446
Thanks, Oren
> Configure AWS instance with only needed ports

- content/rs/administering/designing-production/security/client-connections.md
> Fix mistake in client connections

- content/rs/administering/database-operations/eviction-policy.md
Added  allkeys-lfu and volatile-lfu
> Added allkeys-lfu and volatile-lfu

- content/rs/administering/designing-production/hardware-requirements.md
https://redislabs.atlassian.net/browse/RED-25729
> Increase minimum RAM for development environments

- static/theme-flex/script.js
- static/theme-flex/style.css
These are the fixes for #365 and tweaks for few things in IE11.
> Tweak expand/collapse behavior

- content/rv/how-to/creating-aws-user-redis-enterprise-vpc.md
RED-19052 - Add warning about tampering with your AWS environment
> RED-19052 - Add warning about tampering with your AWS environment

- content/rs/installing-upgrading/upgrading.md
> Add parallel_shards_upgrade and preserve_roles to upgrade procedure

- layouts/partials/embeds/backup-locations.md
Added key file location for SFTP server configuration.
Added (lack of) backup rotation note for Local mount point.
> Add key file for SFTP and backup rotation note for mount point

- content/rs/administering/cluster-operations/maintenance-mode.md
Let's discuss this change... We will probably need to add a warning or such
> Fix line re: quorum loss check on maintenance mode

- layouts/partials/home/hero.html
- layouts/partials/home/options.html
- static/theme-flex/style.css
> Landing page search tweaks

- content/rs/administering/intercluster-replication/crdbs.md
Let's get @guybe7  approval for this change.
> 5.4.4- AOF improvements

- content/rs/administering/cluster-operations/updating-certificates.md
Added missing quotes around parameters in API command
> Add missing quotes in curl command for certificates

- content/rs/getting-started/creating-database/RedisBloom.md
RedisBloom is the official module name.
> Update and rename rebloom.md to RedisBloom.md

- content/rs/getting-started/creating-database/RedisJSON-quick-start.md
RedisJSON is the official module name.
> Update and rename rejson-quick-start.md to RedisJSON-quick-start.md

- .circleci/config.yml
- layouts/partials/breadcrumb.html
- layouts/partials/flex/head.html
- layouts/partials/flex/selectnavigation.html
- layouts/partials/language-selector.html
- layouts/partials/menu.html
- layouts/partials/next-prev-page.html
- layouts/partials/original/body-beforecontent.html
- layouts/partials/post-bottom.html
- layouts/shortcodes/allchildren.html
- layouts/shortcodes/children.html
- layouts/shortcodes/relref.html
This PR fixes errors reported by Hugo after upgarding to version 0.55.5.
> Hugo upgrade fixes

- layouts/partials/custom-head.html
- layouts/partials/flex/scripts.html
- static/js/search.js
GA enabled on staging for testing purposes. Will disable it before merge.
> Track search via GA events

- layouts/partials/flex/scripts.html
- static/js/search.js
Reverts RedisLabs/redislabs-docs#398
> Revert "Track search via GA events" but leave site search parameter

- content/rs/administering/cluster-operations/maintenance-mode.md
> minor grammar fixes and simplifications to maintenance-mode.md 

- content/platforms/kubernetes/_index.md
- content/platforms/pks/_index.md
* removed message about the guide being "unsuitable for production"
* updated generic k8s doc (still WIP - DO NOT PUBLISH).
* Draft PKS doc.
* created draft PKS getting, started an article for review
* Fixed typo
* Capitalization, missing command flag - PKS doc READY
> PKS Getting Started staged and ready, k8s still WIP

- content/platforms/kubernetes/_index.md
- content/platforms/pks/_index.md
Created draft PKS getting started an article for review
> PKS Getting Started

- content/rc/securing-redis-cloud-connections.md
> SSL/TLS support on Redis Cloud Essentials

- static/theme-flex/style.css
> Add margin between code snippet and note panel

- content/rs/administering/designing-production/security/ldap-integration.md
Minor update to fix a bug since the port has changed to a secure port for this.
This fixes #458
> Updating to fix LDAP API call Bug

- content/rv/concepts/data-persistence.md
Added that we have the ability to use append-only files every write. This is already in production.
> Minor update to reflect changes in RCP

- content/rs/administering/active-active.md
- content/rs/administering/database-operations/create-crdb.md
- content/rs/getting-started/getting-started-crdbs.md
@bmansheim & @Paz-Yanover - I struggled today to implement CRDB but ended up finding my way through it. I have some ideas on how we can improve how this is communicated but let's talk about those in person.
Updates below:
1. Updated to include the secure ports for use with CRDB instead of the insecure ports to help prevent insecure configurations
2. Updated to include instructions that would help fix a broken test case.
Thoughts?
> Secure ports usage

- content/rs/installing-upgrading/configuring/linux-swap.md
Remove reference to section below; it is on a different page.
> Remove unnecessary reference

- content/rs/installing-upgrading/configuring/cluster-name-dns-connection-management/_index.md
Add 3rd node to the example of DNS configuration.
> Complete example for 3 nodes

- content/contribution-guide.md
- content/rs/administering/designing-production/networking/port-configurations.md
- content/rs/administering/designing-production/security/account-management.md
This document several instructions using the unencrypted API and removes the unencrypted API from the documentation. I would like to incentivize secure configurations to minimize the support tickets for assistance reconfiguring calls to the API securely.
> Https all the things

- content/ri/installing/install-k8s.md
> RedisInsight k8s support

- content/rc/concepts/data-eviction-policies.md
> Add lfu eviction policies for RC Essentials

- content/rv/concepts/data-eviction-policies.md
Missing recently added *-lfu eviction policies
> Add lfu eviction policies for RC Pro

- content/rs/administering/cluster-operations/settings/alerts.md
Add the note in the relevant page
> Add note to receive notifications on node join and remove (alerts)

- content/rs/administering/database-operations/alerting.md
removed cluster alerts note from database alert doc
> Remove note to receive notifications on node join and remove (alerting)

- content/platforms/openshift/_index.md
Corrected the default value for uiServiceType
> Correct service type default for OpenShift

- content/rs/administering/troubleshooting/cluster-recovery.md
Added a reference for those looking at this cluster recovery article but have a Kubernetes deployment to point to the Kubernetes article.
> Added reference to K8s recovery

- content/platforms/faqs/_index.md
- content/platforms/openshift/_index.md
- content/platforms/pks/_index.md
- content/ri/installing/install-k8s.md
Consistent use of capitalization when referring to K8s (vs. k8s)
> Update K8s to Kubernetes in title, body

- content/platforms/pcf/_index.md
> Improve accuracy of PCF instructions

- README.md
👋 Just a small update to README.md to fix the link to the Markdown cheatsheet.
> Fix broken link to Markdown cheatsheet

- content/platforms/kubernetes/kubernetes-logs.md
> wording fix

- content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
add examples of retrieving operator id and sts name for novice users.
> Clarify kubectl command usage with examples

- content/rs/administering/troubleshooting/database-recovery.md
Added reference to the cluster recovery process in lines 11-15 as customers are getting confused.
> Added a bit of clarity to description in the beginning.

- content/rs/administering/_index.md
You can see the staging site at: https://docs.redislabs.com/staging/add-ref-to-rest-api-docs/rs/administering/
> Add reference to REST API docs

- content/ri/installing/install-redis-desktop.md
Add a bit more details about how to make the downloaded file executable and how to execute them on Linux.
> Update installing RedisInsight desktop for Linux

- content/rs/administering/database-operations/create-crdb.md
Added instruction to click the 'save' icon after adding a participating cluster. This caught me out at first and took me a few moments to figure out!
> Improve add participating clusters

- content/rs/administering/database-operations/create-crdb.md
Added two lines to document two fields (password and endpoint port number) that are in the UI but not these instructions
> Update options to match web UI for create CRDB

- content/rs/administering/database-operations/create-crdb.md
Clarified that the credentials required are the email address and password, not the service account name and password. That confused me for a little while!
> Specify credentials needed for creating CRDB

- content/ri/memory-optimizations/convert-to-list-instead-of-hash.md
Consider this will not work inside github pages (extension is missing) but will work properly on redislab docs.
> add relative link

- content/rs/installing-upgrading/file-locations.md
Some suggested changes to help clarify that some of these paths are fixed, and some can be configured during install, as per https://redislabs.atlassian.net/browse/DOC-99
> DOC-99 Specify data locations

- content/rs/installing-upgrading/upgrading.md
valentino@redislabs.com, @bmansheim - please review and approve
> Warn not to do global operations before upgrading all CRDBs

- content/ri/using-redisinsight/add-instance.md
> RedisInsight: Updated docs on connecting to ElastiCache.

- content/ri/installing/install-redis-desktop.md
> RedisInsight: Added documentation on supported desktop OS.

- content/platforms/kubernetes/_index.md
- content/platforms/kubernetes/cluster-recovery.md
- content/platforms/kubernetes/kubernetes-architecture.md
- content/platforms/kubernetes/kubernetes-logs.md
- content/platforms/kubernetes/kubernetes-with-operator.md
- content/platforms/kubernetes/sizing-kubernetes.md
- content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
- content/platforms/openshift/_index.md
- content/platforms/pcf/_index.md
https://docs.redislabs.com/staging/platforms-reorg/platforms/
> Re-organize platforms articles

- content/embeds/create-subscription-next-steps.md
- content/rc/administration/setup/create-subscription.md
- content/rc/administration/setup/customize-pro.md
- content/rc/quick-setup.md
Staging at: https://docs.redislabs.com/staging/RED-35288-simplified-cloud-signup-minimal/
> RED-35288 Simplified cloud signup changes

- content/rs/administering/active-active.md
Please verify if my proposed edit is technically correct, but I assume this is what the original sentence was trying to convey.
> Update active-passive syncer process

- content/platforms/kubernetes/kubernetes-persistent-volumes.md
include Storage Classes provided by main 3 public cloud providers (added Azure)
> expand on Storage Class

- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
> updated to reflect correct RS version

- content/rc/api/how-to/create-and-manage-subscriptions.md
Reported by HashedIn personnel
> Fix link to Swagger UI

- content/ri/using-redisinsight/memory-analysis.md
Mainly changes "s1" typo to "s3" and a few other readability improvements
> Multiple minor spelling and grammar fixes

- content/ri/using-redisinsight/memory-analysis.md
Giving more detail about the format of the s3 path
> Add syntax for s3 backup file

- content/ri/using-redisinsight/troubleshooting.md
Since this is the troubleshooting page, I think we should include the same 'note' and feedback email that's listed on the installation page (It took me a while to find the email for a customer of mine running into issues)
> Add feedback email for RedisInsight customers with questions

- content/rc/concepts/clustering.md
georeadiusbymember should be georadiusbymember (had extra "e)
> georeadiusbymember changed to georadiusbymember

- static/theme-flex/style.css
It's too hard to read the main page content on wide screens. Now the content is next to the vertical navigation.
> left-justify page content

- content/rs/concepts/terminology.md
There is only the concept of a singular endpoint now.
> Specify in terminology that there is only one endpoint

- content/ri/installing/configurations.md
> Spelling Typo

- content/rs/installing-upgrading/supported-platforms.md
Approved in https://github.com/RedisLabs/redislabs-docs/pull/633
> RED-34932 Support for RHEL7.7

- content/embeds/oss-cluster-api-intro.md
- content/rs/administering/active-active.md
- content/rs/administering/designing-production/networking/using-oss-cluster-api.md
- content/rs/concepts/data-access/oss-cluster-api.md
https://docs.redislabs.com/staging/RED-34404-OSS-cluster-UI/rs/concepts/data-access/oss-cluster-api
https://docs.redislabs.com/staging/RED-34404-OSS-cluster-UI/rs/administering/designing-production/networking/using-oss-cluster-api/
> RED-34404 Update for OSS cluster in the UI and CRDB

- content/rs/installing-upgrading/upgrading.md
@bmansheim was I right to push this to "next"?
> Upgrade to 5.6

- content/modules/upgrading-rs.md
> Update docs for upgrade module parameter changes

- layouts/partials/flex/body-beforecontent.html
- layouts/partials/flex/scripts.html
@HarunD Please review to make sure that's all that needs to be done.
> Add 5.6 to version menu

- content/rs/installing-upgrading/_index.md
> Remove extra note

- content/rs/administering/designing-production/networking/port-configurations.md
Easier reference for customers which ports should be open by Firewall in either Geo distribution, or simple Client / Server access.
> Add Connection Source column

- content/rs/administering/designing-production/persistent-ephemeral-storage.md
Additional details that explain to customers how to provision and connect external storage volumes for persistence.
> Expand on instructions on persistent storage in RS

- content/rs/installing-upgrading/upgrading.md
https://docs.redislabs.com/staging/RED-40655-upgrade-crdb-feature-set/rs/installing-upgrading/upgrading/
> Rewrite for feature set version

- content/ri/release-notes/v1.3.0.md
- content/ri/release-notes/v1.4.0.md
**Staging Env Link:** https://docs.redislabs.com/staging/redisinsight-1.4.0-release-notes/ri/release-notes/v1.4.0/
> Added release notes for RedisInsight 1.4.0

- content/rs/administering/product-lifecycle.md
…ment
This link leads to our Website Terms of Use as compared to our Redis Enterprise Software Subscription Agreement.
> Fix link to Redis Enterprise Software Subscription Agreement

- content/rs/administering/product-lifecycle.md
@Paz-Yanover WDYT - April to Oct or should we do May to Nov? I think we can do April since it was our official release
> 6.0 life cycle

- content/rs/administering/cluster-operations/removing-node.md
@bmansheim I guess my update here may require some editing.
> remove node using REST API

- content/rs/administering/database-operations/importing-data.md
@bmansheim - maybe we need this:
{{< embed-md "backup-locations.md" >}}
?
> Import page with s3-compatible

- content/platforms/pks/_index.md
Output format is required to get the actual values.
> PKS: Add output format and improve formatting

- content/rs/release-notes/rs-6-0-0-may-2020.md
Not sure I was able to correct the modules section which doesn't break lines
> remove x from 6.0.x and modules fixes

- content/platforms/openshift/getting-started-operatorhub.md
I added an section on preparing the cluster by installing the SCC. This is a necessary step.
> Added SCC section for OpenShift 4.x

- content/ri/release-notes/v1.5.0.md
Add release note for RedisInsight v1.5
> Add release note for RedisInsight v1.5

- content/platforms/release-notes/_index.md
- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
- content/platforms/release-notes/k8s-6-0-6-2-2020-05.md
Added the release notes for v6.0.6-2 of the operator.
> K8s release notes for v6.0.6 2

- content/rs/administering/designing-production/security/ldap-integration.md
@bmansheim - could we merge this ASAP. Its minor fixes but looks much better this way.
> LDAP Fixes

- content/platforms/kubernetes/stability.md
> replaced ampersand with 'and' in section title

- content/rc/administration/account-team-settings.md
typo/transposition on TOPT which should be TOTP
> fix typo/transposition

- content/rc/administration/account-team-settings.md
Update team management to reflect GCP marketplace
> Update team management to reflect GCP marketplace

- content/embeds/modules.html
There is no reference what this means externally.  Should be internal
> Removing redisjson preview

- layouts/partials/flex/body-beforecontent.html
- layouts/partials/footer.html
RedisEdge link text is not updated because the CSS doesn't support multi-line menu items
https://docs.redislabs.com/staging/Update-header-footer/
> DOC-269 Update header and footer of docs site to match redislabs.com

- content/rs/installing-upgrading/upgrading.md
Needed for novice Active/Active admins.
> Add explanation how to retrieve CRDB-GUID

- content/ri/using-redisinsight/auto-discover-databases.md
Not sure about how to build the links for pages that are inside our docs
cc @bmansheim
> Add links to RC documentation on how to get Account/Secret Key

- content/ri/release-notes/archive/_index.md
- content/ri/release-notes/v1.0.0.md
- content/ri/release-notes/v1.1.0.md
- content/ri/release-notes/v1.2.0.md
- content/ri/release-notes/v1.3.0.md
- content/ri/release-notes/v1.4.0.md
- content/ri/release-notes/v1.5.0.md
- content/ri/release-notes/v1.6.0.md
Add release note for 1.6 
add description to all previous release notes
> RI 1.6 - Release note

- content/ri/release-notes/v1.6.0.md
Add information about the new 1.6.1 release of RedisInsight
> RedisInsight: Update v1.6.0.md

- content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
Updated release tag and added latest fixes/enhancements.
> Update for release 6.0.6-6

- content/ri/release-notes/v1.6.0.md
Added additional features going into the release.
> Updated RedisInsight 1.6.1 release notes

- content/rs/administering/troubleshooting/testing-client-connectivity.md
> Change to the correct output

- content/ri/using-redisinsight/java-serialized-objects.md
Let's remove this sentence please. Not enterprise friendly.
> Remove unnecessary comment from RedisInsight

- content/embeds/tryout-redisai.md
- content/modules/redisai/_index.md
- content/modules/redisgears/release-notes/redisgraph-1.0-release-notes.md
- content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
- content/rs/developing/crdbs/developing-streams-crdb.md
- content/rs/getting-started/getting-started-docker.md
This changes shortcode tags from % to <>  in several places where _note_ shortcode was used but not rendering.
> Fix note rendering for several notes

- content/rs/installing-upgrading/configuring/linux-swap.md
There's a missing \ between # and 1
> Fix command to turn off swap

- content/rs/installing-upgrading/configuring/linux-swap.md
Reverts RedisLabs/redislabs-docs#917
Approved by @yorozen and @shkediy
> Revert "Fix command to turn off swap"

- content/rs/installing-upgrading/_index.md
> Fix typo in syntax

- content/ri/using-redisinsight/cluster-management.md
Add compatibility information for Cluster Management features
> Add compatibility information for Cluster Management features

- content/ri/release-notes/v1.6.0.md
Add release notes for 1.6.2 and 1.6.3
> Add release notes for 1.6.2 and 1.6.3

- content/ri/release-notes/v1.6.0.md
Typo in information about an improvement
> Update v1.6.0.md from typo

- content/ri/faqs.md
Link for RedisInsight Licence Terms document. is not working, gives 404 Page not found
> Fix RedisInsight license link

- content/ri/installing/install-redis-desktop.md
Add information about signing and notarization for windows/mac distribution.
> Add information about signing and notarization for windows/mac

- content/rs/developing/crdbs/developing-hll-crdb.md
- content/rs/developing/crdbs/developing-lists-crdb.md
- content/rs/developing/crdbs/developing-streams-crdb.md
- content/rs/developing/crdbs/strings.md
Changes to Active-Active documentation
* changed explanation for list concurrent update
* stream page minor command syntax corrections
* removed counter/string duality from string type
* Corrected result for HLL example
> Active-Active developer document changes

- content/ri/using-redisinsight/cluster-management.md
RedisInsight Cluster Management tool for TLS databases is not supported on Windows.
CC @slemeur @nishantgeorge
> Add RedisInsight cluster management tool for TLS databases Windows info

- content/rs/concepts/terminology.md
Original docs stated there could be more than one proxy per node - this isn't correct!
> Updated proxy section

- content/rs/administering/designing-production/networking/port-configurations.md
Reverts RedisLabs/redislabs-docs#821
> Revert "Add ports for encrypted communication"

- content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
- content/platforms/release-notes/k8s-6-0-6-24-2020-08.md
Added release notes for version 6.0.6-24 and changed 6.0.6-23 notes to not say "latest".
> release notes for v6.0.6-24

- content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
@K-Jo I made some edits here. Please have a look before I merge in.
> Redisearch 2.0 release notes

- content/ri/installing/configurations.md
Reverts RedisLabs/redislabs-docs#1032
> Revert "[RedisInsight] Add information about log level"

- content/ri/installing/install-k8s.md
Also document about the environment variable conflict.
CC: @slemeur @nishantgeorge
> [RI-508] Add RedisInsight k8s deployment with service example.

- content/rs/administering/creating-databases/create-active-active.md
need to verify the database was created on all participating cluster
> Add Active-Active create step to verify participating clusters

- content/platforms/kubernetes/pod-scheduling.md
Clarified that the given string is the label, not the actual value
> Minor change to pod-scheduling.md

- content/ri/release-notes/v1.7.0.md
Add ReleaseNote for v1.7.0 of RI
> Add ReleaseNote for v1.7.0 of RI

- content/rs/installing-upgrading/upgrading.md
> Fix link to upgrade nodes

- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
- content/platforms/release-notes/k8s-6-0-6-11-2020-07.md
- content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
- content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
- content/ri/release-notes/v1.2.0.md
https://docs.redislabs.com/staging/DOC-348-change-subheadings-to-bullets/platforms/release-notes/k8s-6-0-6-23-2020-08/
> Formatting changes to change K8s RN subheadings to bullets

- content/rs/administering/adding-node.md
https://redislabs.atlassian.net/browse/RED-46876
This can get to doc right away.
>  join nodes concurrently to a cluster

- content/rs/administering/designing-production/performance/shard-placement.md
Small corrective change that may be useful for people unfamiliar with typical rladmin usage
> Corrected command syntax for tuning placement

- content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
- content/platforms/release-notes/k8s-6-0-8-1-2020-10.md
Release notes for v6.0.8-1 (same as GitHub & confluence)
> Release notes for v6.0.8-1

- content/platforms/openshift/getting-started-cli.md
Line 58, Broken link
https://github.com/RedisLabs/redis-enterprise-k8s-docs/tree/master/examples
> Broken link pointed to K8s examples folder

- content/rs/administering/cluster-operations/replacing-node.md
the word Down is not properly formatted
> tiny formattting

- content/rs/administering/designing-production/networking/using-oss-cluster-api.md
This PR replaces https://github.com/RedisLabs/redislabs-docs/pull/1068.
The comments there about making the style of the instructions less formal will be considered across the docs.
> Improve enable and disable OSS Cluster API

- content/rs/references/client_references/client_ioredis.md
Adds a page describing how to get up and running with ioredis.
> Adds a client page for Node.js with ioredis

- content/rc/api/how-to/create-and-manage-subscriptions.md
paymentMethodId and cloudAccountId values in case of GCP Marketplace
> Added clarification for GCP Marketplace customers.

- content/ri/release-notes/v1.8.0.md
> Add RedisInsight v1.8 release notes

- content/platforms/kubernetes/managing-images.md
Added section about managing container image source with a notes about dockerhub rate limiting
> Added "Managing Container Images" section (DockerHub rate limiting)

- content/embeds/tryout-redisearch-2.md
According to comment in https://github.com/RedisLabs/redislabs-docs/pull/1016
> Remove note to add index name as tag in RCE

- content/rs/installing-upgrading/configuring/cluster-lba-setup.md
Draft for specifying how to setup Redis Enterprise behind a Load Balancer.
> Setting Up a Cluster Behind a Load Balancer

- content/rs/references/client_references/client_ioredis.md
- content/rs/references/client_references/client_nodejs.md
Staging site: https://docs.redislabs.com/staging/fix-node-formatting
> Fix ioredis and node_redis code fences

- content/platforms/kubernetes/cluster-options.md
The link specified next to the field names leads to 404 not found page.
Need to update with the correct link.
I just added "<<Need URL Update>>" next to each URL to point to it.
Remove that string once the URL is updated.
> Update K8s URLs

- content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
- content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
- content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
> Update RediSearch 2.0, RedisTimeSeries 1.4 and RedisGraph 2.2 release notes

- content/rs/administering/designing-production/supported-clients-browsers.md
No further version will be available
> Internet Explorer is EOL

- content/rc/api/how-to/using-curl.md
- layouts/shortcodes/embed-code2.html
Per JIRA-DOC-419, this PR fixes visual glitches for an example on the "Using the API" page in the RC docs.
> Update to fix sample glitch in 'Using the API'

- content/ri/release-notes/v1.8.0.md
> Added release notes for RedisInsight v1.8.2.

- content/rc/concepts/clustering.md
We need some English proofing there. I only made changes to the beginning.
> Writing style review on clustering

- content/embeds/cluster-setup.md
- content/rs/references/crdb-cli-reference.md
- content/rs/release-notes/legacy-release-notes/rs-5-2-june-2018.md
- content/rs/release-notes/rs-6-0-12-january-2021.md
https://docs.redislabs.com/staging/DOC-442-add-6.0.12-release-notes/rs/release-notes/rs-6-0-12-january-2021/
> DOC-442 Add 6.0.12 release notes

- content/rs/concepts/high-availability/clustering.md
Corrected spelling mistake. And added space to keep the doc in a similar format
> Spelling Correction of GEORADIUSBYMEMBER command

- content/rs/administering/access-control/password-rotation.md
> Fix warning formatting

- content/rc/administration/_index.md
> Rewrite of RC Administration landing page

- content/rs/administering/designing-production/security/client-connections.md
Issue 261 (https://github.com/RedisLabs/redislabs-docs/issues/261) - I have added back ticks for all the commands where it needed.
> Fix : Command segments formatting

- content/rs/administering/cluster-operations/updating-certificates.md
Need to add a comment to restart the application to use the new certificate. Otherwise, the currently connected clients will still use the old certificates.
> Restart client after updating certificates

- content/ri/memory-optimizations.md
This page will be revised further with the rest of the RI content. For now, this particular section is less confusing.
> DOC-340 clarified default compression depth

- content/rc/administration/configuration/backups.md
Used links to Microsoft in order to reduce mistakes
> Updated microsoft blobs

- content/rs/_index.md
Rewriting to remove RS as an abbreviation.
> Removing abbreviation.

- content/rs/_index.md
> Fixing an abbreviation that got away earlier.

- content/rc/api/_index.md
- content/rc/api/how-to/enable-your-account-to-use-api.md
Cleans up the API intro page and emphasizes the availability of the API.
> Update to clarify API availability

- content/rs/installing-upgrading/upgrading.md
This should allow us to close https://github.com/RedisLabs/redislabs-docs/issues/463
> Fix update notice

- content/rs/administering/import-export/importing-data.md
Updating intros to match corresponding service.
> DOC 605: Intro sentence doesn't reflect service described in section.

- static/css/redis-sitesearch-overrides.css
- static/js/search.js
Pass the current URL to the search service to boost hits in the same section.
Also includes a larger search box and a few mobile CSS tweaks.
Staging URL: https://docs.redislabs.com/staging/boost-current-section
**[ NOTE ]**: Please ping me before you merge, so I can change the search index this PR uses. It's pointing at a staging search index.
> Pass the current URL to the search service to boost hits in the same section

- content/ri/release-notes/v1.10.0.md
> Added release notes for RedisInsight 1.10.0

- content/rc/_index.md
The sentence as is isn't correct, but I'm not sure if my correction aligns with the intended meaning. If I could get some clarity on what the writer meant, I can suggest a different edit, of course!
> Fixing a typo

- content/ri/using-redisinsight/add-instance.md
> RedisInsight: Added section about supported Redis versions.

- content/platforms/kubernetes/getting-started/quick-start.md
Added the list of platforms the guide applies to at the beginning.
> Enumerate platforms in K8s quick start guide

- content/rs/installing-upgrading/upgrading.md
Reverts RedisLabs/redislabs-docs#1266
> Revert "Update upgrading.md"

- robots.txt
Removing out-of-date content from spiders.
> JIRA DOC-624: Block spiders access to out-of-date content

- content/rs/administering/creating-databases/create-active-active.md
- content/rs/administering/database-operations/eviction-policy.md
> no-AA-eviction-RoF.md

- content/rc/security/database-security/encryption-at-rest.md
> DOC-639: Broken images in "Encryption at rest" article.

- content/rs/security/passwords-users-roles.md
I thought it is worth mentioning :) 
Not urgent, and can be merged to master when ready
> ACLs-on-Active-Active

- content/rc/security/database-security/network-security.md
Initial update to change plan names.
> Jira DOC-637 - RC: Update plan names for Network security article.

- content/rs/administering/creating-databases/create-active-active.md
> DOC-662: Creating Active Active Geo DB page has broken relref links

- content/embeds/backup-locations.md
- content/rs/administering/import-export/_index.md
- content/rs/administering/import-export/database-backup.md
- content/rs/administering/import-export/exporting-data.md
- content/rs/administering/import-export/flush-db-crdb.md
- content/rs/administering/import-export/importing-data.md
Initial check-in of Azure SAS support notes; also includes high level edits for new style guidelines.
> Jira DOC-399: Document support for Azure SAS authentication

- content/rc/databases/back-up-data.md
- content/rc/databases/import-data.md
- content/rc/databases/view-edit-database.md
- content/rc/rc-quickstart.md
- content/rc/security/_index.md
- content/rc/subscriptions/_index.md
- content/rc/subscriptions/create-flexible-subscription.md
- content/rc/subscriptions/view-fixed-subscription.md
Several minor issues were introduced with PR #1231.
This PR addresses them.
> Follow-up to PR #1231; fixing assorted minor issues 

- content/rc/databases/back-up-data.md
- content/rc/databases/import-data.md
- content/rc/databases/view-edit-database.md
- content/rc/rc-quickstart.md
- content/rc/security/_index.md
- content/rc/subscriptions/_index.md
- content/rc/subscriptions/create-flexible-subscription.md
- content/rc/subscriptions/view-fixed-subscription.md
- content/rs/release-notes/rs-6-0-20-april-2021.md
Initial draft for release notes
> RS v6.0.20 release notes

- content/rc/databases/back-up-data.md
SAVE and BGSAVE commands are not supported directly in our products. DMC will not allow those commands.
> remove SAVE and BGSAVE recommendation

- content/rs/security/ldap/enable-role-based-ldap.md
- content/rs/security/ldap/map-ldap-groups-to-roles.md
- content/rs/security/ldap/update-database-acls.md
> DOC-673: Broken images in RS: LDAP docs

- content/rs/installing-upgrading/_index.md
Also performed a quick copyedit to fix typos and apply update style guidelines.  
A full dev edit will be performed later.
> Jira doc 672: Fix rendering glitches

- content/rs/administering/database-operations/memory-limit.md
- content/rs/concepts/high-availability/replication.md
Changing the note shortcode to warning, per ticket.
(Both articles need a dev edit, which is not part of this work item.  A light copy edit for style has been performed)
> DOC-114: Change "note" to "warning"

- content/rc/security/vpc-peering.md
Added note to new VCP peering doc.
> DOC-611: RC - VPC Peering: Add a note clarifying plan support.

- content/rs/administering/troubleshooting/disabling-services.md
This reverts commit a21d50ae77428b6d18310b937afc07e0894c5b1f.
> Revert "Update disabling-services.md (#1233)"

- content/rs/installing-upgrading/upgrading.md
can we also push to latest quickly? thanks
> upgrade-to-6-0-20

- content/rc/databases/back-up-data.md
Updating links to Azure portal and doc resources.
> Jira DOC-358: Update links to Azure portal and doc resources

- content/rs/installing-upgrading/_index.md
Reordering notes and removing extraneous links.
> Jira DOC-634: RS - Reorder notes to support the commands and remove extraneous links creating confusion.

- content/rs/references/crdb-cli-reference.md
The doc incorrectly suggested using --no-force
> To remove an unreachable instance, we need to use the --force flag

- content/ri/release-notes/v1.10.0.md
@K-Jo Please review.
@kaitlynmichael I'm build the code, so I'm unable to provide the screenshot. I have created an issue for the same: https://github.com/RedisLabs/redislabs-docs/issues/1354#issue-871309754
> Add Redisinsight 1.10.1 release notes

- content/rc/databases/back-up-data.md
Rewrote Google Cloud storage section to match current UX and to include a note about the retention policy.
> JIRA DOC-691: RC Data backup article is missing a step for GCS

- content/rs/faqs/_index.md
> fixed relref

- content/modules/redisgears/redisgears-quickstart.md
> Fix typo in getting started

- content/rc/databases/high-availability.md
> RC: Fix TOC glitch in high-availability article

- content/rs/administering/cluster-operations/updating-certificates.md
Updating macros to render correctly.
> Jira DOC-719: RS: "Updating certificates" doc includes malformed macros.

- content/rs/administering/troubleshooting/disabling-services.md
- content/rs/references/rladmin.md
> DOC-684 add cluster config services to disabling services

- content/glossary/_index.md
> Doc-590 correct/add glossary links

- content/rs/concepts/intercluster-replication.md
Creating new PR because merging was blocked on #1388 due to "/" in branch name.
> update a-a links via PR#1388

- content/rs/administering/database-operations/updating-configurations.md
@lanceleonard @kaitlynmichael please review my english, wording etc :) I assume we will iterate (a bit) on it
> Replication backlog [doc-680]

- content/rs/references/rladmin.md
> DOC-729 remove 'endpoint' and 'shards_to_endpoint' options

- content/rs/administering/designing-production/supported-clients-browsers.md
- content/rs/getting-started/_index.md
- content/rs/getting-started/getting-started-active-active.md
- content/rs/getting-started/getting-started-docker.md
- content/rs/getting-started/getting-started-redis-flash.md
- content/rs/getting-started/memtier-benchmark.md
- Initial draft.  Also includes minor edits for style in related topics.
> Jira DOC-721: Separate browser support info from connection info

- content/rs/administering/product-lifecycle.md
@lanceleonard @kaitlynmichael before merging let's just get @amiramm ack please.
@adisht fyi
> RS 6.0 support extension

- content/rs/release-notes/legacy-release-notes/redis-enterprise-5.md
- content/rs/release-notes/legacy-release-notes/redis-pack-4-5-0-may-2017.md
- content/rs/release-notes/legacy-release-notes/release-notes-redis-enterprise-software-v5-0-2.md
- content/rs/release-notes/legacy-release-notes/rlec-0-99-5-11-january-2015.md
- content/rs/release-notes/legacy-release-notes/rlec-0-99-february-2015.md
- content/rs/release-notes/legacy-release-notes/rlec-4-0-june-2015.md
- content/rs/release-notes/legacy-release-notes/rlec-4-2-october-2015.md
- content/rs/release-notes/legacy-release-notes/rlec-4-3-aug-2016.md
- content/rs/release-notes/legacy-release-notes/rlec-4-4-dec-2016.md
- content/rs/release-notes/legacy-release-notes/rs-5-2-2-august-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-2-june-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-3-beta-july-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-10-december-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-14-february-2020.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-2-april-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-4-june-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-6-july-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-december-2018.md
- content/rs/release-notes/rs-5-5-preview-april-2019.md
- content/rs/release-notes/rs-5-6-0-april-2020.md
- content/rs/release-notes/rs-6-0-12-january-2021.md
- content/rs/release-notes/rs-6-0-20-april-2021.md
- content/rs/release-notes/rs-6-0-8-september-2020.md
- content/rs/release-notes/rs-6-0-may-2020.md
Removes line breaks and duplicated content from the TOC control; should improve navigation.
> Jira DOC-758: RS: Update release note link titles 

- content/platforms/release-notes/_index.md
- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
- content/platforms/release-notes/k8s-6-0-12-5-2021-02.md
- content/platforms/release-notes/k8s-6-0-20-4-2021-05.md
- content/platforms/release-notes/k8s-6-0-20-4.md
- content/platforms/release-notes/k8s-6-0-6-11-2020-07.md
- content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
- content/platforms/release-notes/k8s-6-0-6-24-2020-08.md
- content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
- content/platforms/release-notes/k8s-6-0-8-1-2020-10.md
- content/platforms/release-notes/k8s-6-0-8-20-2020-12.md
> Doc-759 k8s release notes link titles

- content/rc/databases/back-up-data.md
Removing a previously-removed note.
> Remove note

- content/rs/release-notes/rs-6-0-20-april-2021.md
Please hold the merge due to a critical bug
> 6-0-20-95-build-rn-updates

- content/rs/references/developing-for-active-active/_index.md
- content/rs/references/developing-for-active-active/developing-hashes-active-active.md
- content/rs/references/developing-for-active-active/developing-hll-active-active.md
- content/rs/references/developing-for-active-active/developing-lists-active-active.md
- content/rs/references/developing-for-active-active/developing-sets-active-active.md
- content/rs/references/developing-for-active-active/developing-sorted-sets-active-active.md
- content/rs/references/developing-for-active-active/developing-streams-active-active.md
- content/rs/references/developing-for-active-active/developing-strings-active-active.md
- content/rs/references/developing-for-active-active/region-application-failover-active-active.md
- content/rs/references/memtier-benchmark.md
> Jira DOC-793: RS: Link in Active-active entry page points to wrong article.

- content/rc/faqs/_index.md
Fixing typos and incorrect links in RC FAQs
Staged version with fixes:
[FAQs](https://docs.redislabs.com/staging/DOC-790/rc/faqs/)
> Fixing typos and incorrect links in RC FAQs

- content/rs/security/admin-console-security/user-security.md
Updating LDAP section to point to the new content added in v6.0.20.  
Also applied other minor edits for style and readability.
> Jira DOC-791: RS: The LDAP section of "Authentication & authorization" is out-of-date

- content/modules/redisgears/release-notes/_index.md
> Update stale link redirect

- content/rs/installing-upgrading/_index.md
We have multiple customers inquiring about permission levels. This change adds information about how our tools binaries are permissioned.
> Update Installation Guide

- content/rc/api/examples/audit-system-logs.md
- content/rc/api/examples/back-up-and-import-data.md
- content/rc/api/examples/create-database.md
- content/rc/api/examples/dryrun-cost-estimates.md
- content/rc/api/examples/manage-cloud-accounts.md
- content/rc/api/examples/manage-subscriptions.md
- content/rc/api/examples/view-account-information.md
- content/rc/api/get-started/_index.md
- content/rc/api/get-started/enable-the-api.md
- content/rc/api/get-started/manage-api-keys.md
- content/rc/api/get-started/manage-tasks.md
- content/rc/api/get-started/process-lifecycle.md
- content/rc/api/get-started/use-rest-api.md
- content/rc/how-to/creating-iam-resources/_index.md
- content/rc/how-to/creating-iam-resources/creating-aws-user-redis-enterprise-vpc.md
- content/rc/how-to/creating-iam-resources/terraform.md
- content/rc/how-to/multiple-accounts.md
- content/rc/how-to/view-edit-cloud-account.md
Fixing typos in RC REST API and How Tos
Staged versions with fixes:
[REST API](https://docs.redislabs.com/staging/DOC-790/rc/api/)
[How Tos](https://docs.redislabs.com/staging/DOC-790/rc/how-to/)
> Fixing typos in RC REST API and How Tos

- content/rs/security/tls-ssl.md
Add mTLS certificate expiration date validation options
> Add mTLS certificate expiration date validation

- content/glossary/_index.md
DOC-776 added several k8s terms to glossary
> DOC-776 k8s glossary terms

- content/rc/how-to/creating-iam-resources/cloudformation.md
Adds AWS cli commands showing how to get the outputs
> Fixes doc_749

- content/modules/_index.md
- content/rc/databases/create-database.md
Detailed the modules supported by Redis Enterprise Cloud.
> Jira DOC-713: Clarify RC module support

- content/platforms/release-notes/k8s-6-0-20-12-2021-07.md
> K8s july release notes 6.0.20-12

- content/platforms/release-notes/_index.md
- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
- content/platforms/release-notes/k8s-5-4-14-2-2020-03.md
new links to index page, linktitles
> K8s release notes edits 

- content/rc/how-to/view-edit-cloud-account.md
- content/rc/security/database-security/network-security.md
Quick edits to rework plan names.
(Note: these articles are being updated separately; this PR simply updates the plan names.)
> Jira DOC-807: RC - Update references to out-of-date plan names.

- content/glossary/_index.md
Added a few security terms and links to the glossary.
[Staged version](https://docs.redislabs.com/staging/jira-doc-642/glossary/)
> Added security terms and links to the glossary

- content/platforms/kubernetes/concepts/persistent-volumes.md
changes to warn customers about persistent volume size via DOC-767
> added warning for persistent volume size

- content/platforms/kubernetes/reference/supported_k8s_distributions.md
DOC-775 using support matrix in K8s-docs README file. Will need to be updated with each release.
> DOC-775 K8s support matrix, new article

- content/embeds/backup-locations.md
- content/rs/administering/import-export/database-backup.md
- content/rs/administering/import-export/exporting-data.md
Support for SWIFT was removed a while ago
> Support for SWIFT was removed a while ago

- content/rs/installing-upgrading/customize-install-directories.md
Consolidate 2 consecutive notes
> Consolidate 2 consecutive notes

- content/modules/add-module-to-cluster.md
> Fix a typo

- content/rs/administering/database-operations/_index.md
- content/rs/security/_index.md
> Jira DOC-834: RS - Fix 404 error in Database maintenance page

- content/rc/administration/_index.md
- content/rc/how-to/_index.md
- content/ri/faqs.md
- content/rs/faqs/_index.md
> Jira DOC-843: Remove {{expands}} from RS & RI FAQs

- changelog.md
> Changelog:  July 2021 updates

- content/rs/security/admin-console-security/user-security.md
not bounded to version, can be merged to latest once approved
> Updating admin password on Clusters with CRDB

- content/rc/databases/import-data.md
> Jira DOC-852: RC - Import Data is missing a redirect

- content/rs/release-notes/rs-6-0-20-april-2021.md
Needs to go live (latest) asap. thanks!
These are two bugs we must inform the field about in the release notes.
> [Urgent] 6.0.20 known limitation - 2 critical bugs

- content/rs/release-notes/rs-6-0-20-april-2021.md
@amiramm fyi
PR should go also as soon as we can to latest. thanks
> CRDB - add known limitation red-61114

- content/rc/databases/configuration/high-availability.md
> Jira DOC-864: Use of "region" and "zone" is confusing.

- layouts/404.html
- layouts/partials/flex/body-beforecontent.html
Reapplied these RS 6.2 version dropdown changes.
> Updated RS version dropdown for RS 6.2.x release series

- content/rs/installing-upgrading/configuring/mdns.md
merge only when we add rhel8 support
> update mDNS for rhel8

- content/rs/administering/product-lifecycle.md
> adding RS 6.2 to product lifecycle

- content/rs/installing-upgrading/configuring/mdns.md
Reverts RedisLabs/redislabs-docs#1416
> Revert "update mDNS for rhel8"

- changelog.md
> Update changelog for August 2021

- content/platforms/kubernetes/tasks/internode-encryption.md
- content/platforms/kubernetes/tasks/set-up-ingress-controller.md
This feature is for the Galactica release
> DOC-885 K8s enable internode encryption

- content/platforms/release-notes/k8s-6-0-20-4-2021-05.md
> typo in Openshift

- content/platforms/release-notes/k8s-6-2-4-1-2021-09.md
> Found new known limitation and added it

- content/rs/references/rladmin.md
[Staged version](https://docs.redis.com/staging/jira-doc-770/rs/references/rladmin/#verify)
> Added more detail to rladmin verify commands

- changelog.md
> Changelog: Updates for September 2019

- content/platforms/kubernetes/deployment/openshift/_index.md
- content/platforms/kubernetes/deployment/openshift/openshift-cli.md
- content/platforms/kubernetes/deployment/openshift/openshift-operatorhub.md
> DOC-930 update aliases to correct 404

- content/ri/release-notes/v1.11.0.md
**NOTE: MERGE ONLY AFTER APPROVAL FROM @ollopaci**
> Add RedisInsight v1.11 release notes

- content/rs/references/client_references/_index.md
- content/rs/references/client_references/client_c.md
- content/rs/references/client_references/client_csharp.md
- content/rs/references/client_references/client_drupal.md
- content/rs/references/client_references/client_ioredis.md
- content/rs/references/client_references/client_java.md
- content/rs/references/client_references/client_nodejs.md
- content/rs/references/client_references/client_php.md
- content/rs/references/client_references/client_python.md
- content/rs/references/client_references/client_ruby.md
[Staged preview](https://docs.redis.com/staging/jira-doc-872/rs/references/client_references/)
> Initial Redis client reference edits

- changelog.md
- Initial draft for October 2021 changes.
> Changes for October 2021

- content/kubernetes/deployment/tanzu/_index.md
- content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
> Update abbreviation TKGIE to TKGI

- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
> DOC-965 correct image name in release notes

- content/rs/administering/cluster-operations/maintenance-mode.md
- content/rs/references/rest-api/requests/nodes/actions.md
[Staged preview](https://docs.redis.com/staging/jira-doc-966/rs/administering/cluster-operations/maintenance-mode/)
> Edited RS maintenance mode article

- content/rs/administering/logging/_index.md
- content/rs/administering/logging/rsyslog-logging/_index.md
- content/rs/administering/logging/rsyslog-logging/bdb-events.md
- content/rs/administering/logging/rsyslog-logging/cluster-events.md
- content/rs/administering/logging/rsyslog-logging/node-events.md
- content/rs/administering/logging/rsyslog-logging/user-events.md
[Staged preview](https://docs.redis.com/staging/jira-doc-952/rs/administering/logging/rsyslog-logging/)
> Edited rsyslog logging, events, and alerts

- content/kubernetes/release-notes/_index.md
- content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
> K8S: Updating RN index page and removing TBD from filename.

- content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
> Release note for 2.0.13

- content/rs/release-notes/_index.md
- content/rs/release-notes/legacy-release-notes/_index.md
- content/rs/release-notes/rs-5-6-0-april-2020.md
- content/rs/release-notes/rs-6-0-12-january-2021.md
- content/rs/release-notes/rs-6-0-20-april-2021.md
- content/rs/release-notes/rs-6-0-8-september-2020.md
- content/rs/release-notes/rs-6-0-may-2020.md
- content/rs/release-notes/rs-6-2-4-august-2021.md
- content/rs/release-notes/rs-6-2-8-october-2021.md
- layouts/shortcodes/table-children.html
[Staged preview](https://docs.redis.com/staging/jira-doc-979/rs/release-notes/)
> Allow custom front matter fields in table-children shortcode

- content/rs/references/client_references/client_php.md
> Jira DOC-983: Predis client connection SSL statement is out-of-date

- config.toml
- layouts/partials/pdf-prep-recursive.html
- layouts/partials/pdf-prep-single.html
- layouts/partials/post-bottom.html
- layouts/partials/recursive-children.html
- static/theme-flex/style.css
[Staged preview](https://docs.redis.com/staging/jira-doc-989/rs/)
> Added article last updated date

- content/embeds/supported-platforms-embed.md
> RHEL8 support

- content/ri/installing/configurations.md
> RedisInsight v1: Add default hostname note for Windows, Mac and Linux.

- content/ri/using-redisinsight/api.md
> [RedisInsight] Add note about CA cert and verifyServerCert flag.

- content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1015/modules/redisgears/release-notes/redisgears-1.0-release-notes/)
> Added RedisGears v1.0.8 release notes

- config.toml
- layouts/partials/banner.html
- layouts/partials/flex/body-beforecontent.html
- layouts/partials/home/hero.html
- static/theme-flex/style.css
[Staged home page](https://docs.redis.com/staging/jira-doc-1023/)
[Staged article](https://docs.redis.com/staging/jira-doc-1023/rs/)
> Added re:invent banner

- content/rs/getting-started/getting-started-active-active.md
from internal conversation - https://redislabs.slack.com/archives/C4UN38JAJ/p1638374789072200
> AA-Unique-fqdn

- static/theme-flex/style.css
[Staged preview](https://docs.redis.com/staging/jira-doc-1037/rs/)
> Bug fix for header hides top of TOC

- content/ri/installing/install-k8s.md
I am of the opinion that showing how to to spin up redis insights in k8s with ephemeral storage only is not that useful. This is the solution I came up and is working well for me.
> Example for using a persistent volume claim

- content/modules/redisgraph/redisgraph-quickstart.md
The embed caused the duplicated content.
[Staged preview](https://docs.redis.com/staging/jira-doc-942/modules/redisgraph/redisgraph-quickstart/)
> Removed duplicate RedisGraph quick start example

- content/kubernetes/deployment/openshift/openshift-cli.md
DOC-870
Staging site: https://docs.redis.com/staging/jira-doc-870/kubernetes/deployment/openshift/openshift-cli/
> K8s: revise openshift cli getting started 

- config.toml
[Staged preview](https://docs.redis.com/staging/banner-text-edit/)
> Updated re:Invent banner text

- content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisjson-release-notes/modules/redisjson/release-notes/redisjson-2.0-release-notes/)
> Added RedisJSON v2.0.6 release notes

- content/modules/modules-quickstart.md
- content/modules/redisearch/redisearch-quickstart.md
[Main modules quick start](https://docs.redis.com/staging/jira-doc-1049/modules/modules-quickstart/)
[RediSearch quick start](https://docs.redis.com/staging/jira-doc-1049/modules/redisearch/redisearch-quickstart/)
> Revised RediSearch quick start

- content/_header.md
- layouts/404.html
- layouts/partials/flex/body-beforecontent.html
- layouts/partials/footer.html
- layouts/partials/navigation.html
I updated redislabs.com URLs to redis.com URLs in the header and footer. I also fixed some outdated/broken social media URLs in the footer (to match the ones on redis.com).
[Staged preview](https://docs.redis.com/staging/update-header-url/)
> Updated home page URLs

- content/rc/databases/configuration/data-eviction-policies.md
- content/rs/administering/database-operations/eviction-policy.md
Update policy descriptions to match UX
> Jira DOC-1010: Update eviction policy descriptions

- content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisgraph-release-notes/modules/redisgraph/release-notes/redisgraph-2.4-release-notes/)
> Added RedisGraph v2.4.13 release notes

- changelog.md
> Changelog updates for December 2021

- content/kubernetes/release-notes/_index.md
- content/kubernetes/release-notes/k8s-5-4-10-8-january-2020.md
- content/kubernetes/release-notes/k8s-5-4-14-2-2020-03.md
- content/kubernetes/release-notes/k8s-6-0-12-5-2021-02.md
- content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
- content/kubernetes/release-notes/k8s-6-0-20-4-2021-05.md
- content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
- content/kubernetes/release-notes/k8s-6-0-6-23-2020-08.md
- content/kubernetes/release-notes/k8s-6-0-6-24-2020-08.md
- content/kubernetes/release-notes/k8s-6-0-6-6-2020-06.md
- content/kubernetes/release-notes/k8s-6-0-8-1-2020-10.md
- content/kubernetes/release-notes/k8s-6-0-8-20-2020-12.md
- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
- content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
https://docs.redis.com/staging/jira-doc-1071/kubernetes/release-notes/
> DOC-1071 refactor K8s release note page

- content/kubernetes/re-clusters/create-aa-database.md
- content/kubernetes/re-databases/ingress_routing_with_istio.md
Jira: DOC-1092
Staging: https://docs.redis.com/staging/jira-doc-1092/kubernetes/re-clusters/create-aa-database/#using-ingress-controller
> DOC-1092 adding Istio section to K8s AA article

- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-6-2-8-10-2022-01.md
Jira: DOC-1091
Staging: https://docs.redis.com/staging/jira-doc-1091/kubernetes/release-notes/k8s-6-2-8-10-2022-01/
> DOC-1091 Intrepid release notes

- content/kubernetes/deployment/quick-start.md
> DOC-993 added private repo link to quick start prereq

- content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisgears-release-notes/modules/redisgears/release-notes/redisgears-1.0-release-notes/)
> Added RedisGears v1.0.9 release notes

- content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisearch-release-notes/modules/redisearch/release-notes/redisearch-2.2-release-notes/)
> Added RediSearch v2.2.6 release notes

- content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
> K8s 6.2.8-11 RN update about upgrade failure

- content/rs/installing-upgrading/_index.md
> DOC-1118: RS-Add command-line options to install doc.

- changelog.md
> Changelog update January 2022

- content/embeds/cluster-dns-embed.md
- Updating link and cleaning up the language.
> DOC-1134: RS "Configure Cluster DNS" includes a malformed link

- content/kubernetes/faqs/_index.md
> DOC-1137 fix broken link

- content/rs/references/rest-api/requests/modules/_index.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1111/rs/references/rest-api/requests/modules/)
> Added /v2/modules requests to RS REST API

- content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisearch-release-notes/modules/redisearch/release-notes/redisearch-2.2-release-notes/)
> Added RediSearch v2.2.7 release notes

- content/ri/release-notes/v2.0.2.md
Added information about 2.0.4 (available starting from Feb 9).
> Added information about 2.0.4

- content/rc/security/vpc-peering.md
Hi reviewers,
I create a minimal PR to fix typo in `content/rc/security/vpc-peering.md` file.
Please help to review, thanks!
Alex
> Fix typo for vpc-perring.md document

- content/rs/release-notes/rs-6-2-10-february-2022.md
- content/rs/release-notes/rs-6-2-8-october-2021.md
* Initial draft
* Editorial updates.
* Update rs-6-2-10-february-2022.md
* Update rs-6-2-10-february-2022.md
@lanceleonard @adisht fyi
* Update rs-6-2-10-february-2022.md
* Update rs-6-2-10-february-2022.md
* Update rs-6-2-10-february-2022.md
* Update content/rs/release-notes/rs-6-2-10-february-2022.md
Co-authored-by: Alon Magrafta <50071256+AlonMagrafta@users.noreply.github.com>
* Update content/rs/release-notes/rs-6-2-10-february-2022.md
Co-authored-by: Alon Magrafta <50071256+AlonMagrafta@users.noreply.github.com>
* Adding MD5 checksums and other minor edits.
* More tweaks; fewer
* Deal with layout quirks
Co-authored-by: adisht <36517802+adisht@users.noreply.github.com>
Co-authored-by: Alon Magrafta <50071256+AlonMagrafta@users.noreply.github.com>
> DOC-1131: RS - Arbel release note updates. (#1778)

- content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisgears-release-notes/modules/redisgears/release-notes/redisgears-1.2-release-notes/)
> Added RedisGears v1.2 release notes

- content/kubernetes/re-clusters/connect-prometheus-operator.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-6-2-10-4-2022-03.md
Staging: 
- https://docs.redis.com/staging/release-k8s-jolly-roger/kubernetes/re-clusters/connect-prometheus-operator/
- https://docs.redis.com/staging/release-k8s-jolly-roger/kubernetes/reference/supported_k8s_distributions/
- https://docs.redis.com/staging/release-k8s-jolly-roger/kubernetes/release-notes/k8s-6-2-10-4-2022-03/
> Release k8s jolly roger

- content/rs/concepts/memory-performance/persistence.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1208/rs/concepts/memory-performance/persistence/)
> Updated RS DB persistence to use replica

- config.toml
- layouts/partials/banner.html
[Staged preview](https://docs.redis.com/staging/jira-doc-1212/)
> Changed banner for RedisDays event

- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[Staged preview](https://docs.redis.com/staging/graph-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added RedisGraph v2.8.9 release notes

- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-6-2-10-4-2022-03.md
Added to supported distro page and release notes for 6.2.10-4
> DOC-1216 add Rancher 2.6 support

- content/rs/references/rest-api/requests/cluster/services_configuration.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1163/rs/references/rest-api/requests/cluster/services_configuration#example-json-body-1)
> Fixed example JSON for PUT /cluster/services_configuration request

- content/modules/redisgears/installing-redisgears.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1204/modules/redisgears/installing-redisgears/#install-redisgears-and-dependencies)
> Specify node for install RedisGears REST API request

- content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisearch-release-notes/modules/redisearch/release-notes/redisearch-2.2-release-notes/)
> Added RediSearch v2.2.10 release notes

- content/ri/release-notes/v2.0.2.md
Should be reviewed by @K-Jo before merge.
> Release notes for 2.0.5

- content/modules/modules-quickstart.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1236/modules/modules-quickstart/)
> Updated module quick start to use Redis Stack

- content/kubernetes/re-clusters/create-aa-database.md
- content/kubernetes/re-clusters/delete_custom_resources.md
- content/kubernetes/re-clusters/upgrade-redis-cluster.md
DOC-941
Based off https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/topics.md#custom-resource-deletion 
https://docs.redis.com/staging/jira-doc-941/kubernetes/re-clusters/delete_custom_resources/
> DOC-941 K8s delete custom resources

- content/rs/_index.md
> DOC-1221 fix broken links

- README.md
Windows users might encounter error when attempting to build the site.  This change updates README with a known fix.
> README: Update for build error on Windows

- content/rc/security/single-sign-on.md
Here are some possible additions to the SAML docs.
[Staged preview](https://docs.redis.com/staging/jira-doc-1143/rc/security/single-sign-on#saml-single-sign-on)
> Updated SAML onboarding for Redis Cloud

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisearch-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)
> Added RediSearch v2.4 GA release notes

- config.toml
[Staged preview](https://docs.redis.com/staging/remove-banner/)
> Turned RedisDays banner off

- content/embeds/supported-platforms-embed.md
- content/rs/release-notes/rs-6-2-10-february-2022.md
> RS - DOC-1231: RHEL 8.5 support

- content/embeds/new-cluster-embed.md
Staging link: https://docs.redis.com/staging/jira-doc-1296/rs/administering/new-cluster-setup/
Added a single parenthesis to embed the link in the article.
> RS - DOC-1296: Link to DNS instructions on "Setting up a new cluster" showing as plain text

- content/rs/references/rest-api/objects/crdb/health_report/_index.md
- content/rs/references/rest-api/objects/crdb/health_report/health_report_configuration.md
- content/rs/references/rest-api/requests/crdbs/health_report.md
- content/rs/references/rest-api/requests/crdbs/updates.md
- content/rs/release-notes/rs-6-2-10-february-2022.md
New RS REST API request:
[health_report](https://docs.redis.com/staging/jira-doc-1141/rs/references/rest-api/requests/crdbs/health_report/)
New RS REST API objects:
[health_report](https://docs.redis.com/staging/jira-doc-1141/rs/references/rest-api/objects/crdb/health_report/)
[health_report_configuration](https://docs.redis.com/staging/jira-doc-1141/rs/references/rest-api/objects/crdb/health_report/health_report_configuration/)
> Added CRDB health_report request to RS REST API

- content/rs/release-notes/rs-6-2-10-february-2022.md
> RS - DOC 1298: Update 6.2.10 release notes with fixes for build 96

- content/kubernetes/re-databases/set-up-ingress-controller.md
DOC-1283
Staged preview: https://docs.redis.com/staging/jira-DOC-1283/kubernetes/re-databases/set-up-ingress-controller/
> DOC-1283 update apiversion

- content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/gears-release-notes/modules/redisgears/release-notes/redisgears-1.2-release-notes/)
> Added RedisGears v1.2.3 release notes

- content/rs/administering/product-lifecycle.md
Staging link: https://docs.redis.com/staging/jira-doc-1311/rs/administering/product-lifecycle/
Changed the subscription link to the forever link provided in the ticket.
> DOC-1311 - RS: Changed subscription agreement link to forever link

- content/rc/security/database-security/tls-ssl.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1331/rc/security/database-security/tls-ssl/)
> RC Fixed subscription supports TLS

- content/rs/references/rest-api/requests/bdbs/_index.md
> Jira DOC-660: Update REST API sample parameter value

- content/rs/references/cli-utilities/rladmin/help.md
- content/rs/references/cli-utilities/rladmin/info.md
rladmin help: https://docs.redis.com/staging/jira-doc-1317/rs/references/cli-utilities/rladmin/help/
rladmin info: https://docs.redis.com/staging/jira-doc-1317/rs/references/cli-utilities/rladmin/info/
> DOC-1317 - RS: CLI Utitilites Reorg rladmin help and rladmin info commands

- content/rs/references/rest-api/objects/state-machine.md
- content/rs/references/rest-api/requests/actions.md
Staging Links: 
Actions endpoint: https://docs.redis.com/staging/jira-doc-1160/rs/references/rest-api/requests/actions/
State Machine object: https://docs.redis.com/staging/jira-doc-1160/rs/references/rest-api/objects/state-machine/
Draft of the /actions and /actions/{uid} GET requests.
> DOC-1160 - RS API: Document v1 /actions/ API request.

- content/modules/_index.md
- content/modules/modules-lifecycle.md
- content/modules/redis-stack.md
- content/modules/redisai/_index.md
- content/modules/redisbloom/_index.md
- content/modules/redisearch/_index.md
- content/modules/redisgears/_index.md
- content/modules/redisgraph/_index.md
- content/modules/redisjson/_index.md
- content/modules/redistimeseries/_index.md
- static/tables/redisbloom-lifecycle.csv
- static/tables/redisearch-lifecycle.csv
- static/tables/redisgears-lifecycle.csv
- static/tables/redisgraph-lifecycle.csv
- static/tables/redisjson-lifecycle.csv
- static/tables/redistimeseries-lifecycle.csv
> Modules: Update module lifecycle and add links

- content/rs/references/cli-utilities/rladmin/status.md
Staging: https://docs.redis.com/staging/jira-doc-1319/rs/references/cli-utilities/rladmin/status/
> DOC-1319 - RS Utilities Reorg: rladmin status page

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
[Staged preview](https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)
> Added RediSearch v2.4.5 release notes

- content/rs/references/cli-utilities/rladmin/failover.md
Staging link: https://docs.redis.com/staging/jira-doc-1323/rs/references/cli-utilities/rladmin/failover/
> DOC-1323 - RS CLI Utilities Reorg: rladmin failover command

- content/rs/concepts/high-availability/_index.md
Basic overview of high availability and durability features in RS, with links to more info.
Jira ticket: DOC-1065
Staging link: https://docs.redislabs.com/staging/jira-doc-1065/rs/concepts/high-availability/
> DOC-1065 durability and availability article

- content/rs/references/cli-utilities/rladmin/placement.md
Staging Link: https://docs.redis.com/staging/jira-doc-1326/rs/references/cli-utilities/rladmin/placement/
> DOC-1326 - RS CLI Utilities Reorg: rladmin placement command

- content/rs/references/cli-utilities/rladmin/restart.md
Staging Link: https://docs.redis.com/staging/jira-doc-1328/rs/references/cli-utilities/rladmin/restart/
> DOC-1328 - RS CLI Utilities Reorg: rladmin restart page

- content/modules/_index.md
- content/modules/enterprise-capabilities.md
- content/modules/redis-stack.md
> Modules: Clarify Redis Stack support

- content/kubernetes/reference/db-options.md
DOC-1361
enforceClientAuthentication is no longer a valid option for REDB.
> DOC-1361 remove old REDB option

- content/kubernetes/reference/db-options.md
DOC-1350
Staged Preview: https://docs.redis.com/staging/jira-doc-1350/kubernetes/reference/db-options/#redisversion/
> DOC-1350 add redisVersion to db-options page

- content/modules/redisjson/redisjson-quickstart.md
Staging link: https://docs.redis.com/staging/jira-doc-1050/modules/redisjson/redisjson-quickstart/
> DOC-1050: RedisJSON Quick Start Rewrite

- content/rs/references/cli-utilities/rladmin/suffix.md
Staging link: https://docs.redis.com/staging/jira-doc-1321/rs/references/cli-utilities/rladmin/suffix/
> DOC-1321: RS CLI Utilities - rladmin suffix

- content/connect/_index.md
- layouts/404.html
- layouts/partials/home/options.html
- layouts/partials/menu.html
- static/theme-flex/img/ico-blank-icon.svg
- static/theme-flex/img/ico-connect.svg
- Initial interim draft to checkpoint progress
> DOC-1382: Connect - Preview

- content/rs/references/cli-utilities/rladmin/migrate.md
Staging link: https://docs.redis.com/staging/jira-doc-1324/rs/references/cli-utilities/rladmin/migrate/
> DOC-1324: RS CLI Reorg - rladmin migrate page

- content/rs/references/cli-utilities/rladmin/node/_index.md
- content/rs/references/cli-utilities/rladmin/node/addr.md
- content/rs/references/cli-utilities/rladmin/node/enslave.md
- content/rs/references/cli-utilities/rladmin/node/external-addr.md
- content/rs/references/cli-utilities/rladmin/node/maintenance-mode.md
- content/rs/references/cli-utilities/rladmin/node/recovery-path.md
- content/rs/references/cli-utilities/rladmin/node/remove.md
- content/rs/references/cli-utilities/rladmin/node/snapshot.md
Staging link: https://docs.redis.com/staging/jira-doc-1325/rs/references/cli-utilities/rladmin/node/
Still working on the individual command pages.
> DOC-1325: RS CLI Reorg: rladmin node

- content/rs/references/cli-utilities/rladmin/upgrade.md
Staging link: https://docs.redis.com/staging/jira-doc-1327/rs/references/cli-utilities/rladmin/upgrade/
> DOC-1329: RS CLI Utilites Reorg - rladmin upgrade command page

- content/rs/databases/configure/edit-delete-db.md
Jira: DOC-1406
Staged preview: https://docs.redis.com/staging/jira-doc-1406/rs/databases/configure/edit-delete-db/
> DOC-1406 correct internal links 

- content/modules/redistimeseries/redistimeseries-quickstart.md
Staging Link: https://docs.redis.com/staging/jira-doc-1055/modules/redistimeseries/redistimeseries-quickstart/
> DOC-1055: RedisTimeSeries Quick Start

- content/rs/references/cli-utilities/_index.md
[Staged preview](https://docs.redis.com/staging/jira-doc-761/rs/references/cli-utilities/)
> Added more info to the CLI landing page

- content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/gears-release-notes/modules/redisgears/release-notes/redisgears-1.2-release-notes/)
> Added RedisGears v1.2.4 release notes

- content/rs/release-notes/rs-6-2-10-february-2022.md
> Update rs-6-2-10-february-2022.md - build 121

- content/ri/installing/configurations.md
- content/ri/release-notes/v1.11.0.md
- content/ri/release-notes/v1.12.0.md
> Ri v1.12.0 release notes & auth prompt environment variables

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
[Staged preview](https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)
> Added RediSearch v2.4.6 release notes

- content/glossary/_index.md
- content/rs/release-notes/rs-6-0-20-april-2021.md
- content/rs/release-notes/rs-6-2-4-august-2021.md
- content/rs/security/ldap/_index.md
- content/rs/security/ldap/cluster-based-ldap-authentication.md
- content/rs/security/ldap/migrate-to-role-based-ldap.md
> DOC-1341: RS - Update LDAP docs to reflect changes

- content/rs/release-notes/rs-6-2-10-february-2022.md
> Update rs-6-2-10-february-2022.md with OL8

- content/rs/databases/import-export/import-data.md
> DOC-1432 - RS: Swift is no longer an option for import

- content/rs/references/cli-utilities/crdb-cli/crdb/list.md
Staging link: https://docs.redis.com/staging/jira-doc-1371/rs/references/cli-utilities/crdb-cli/crdb/list/
> DOC-1371: RS CRDB-CLI reorg - crdb-cli crdb list command

- content/rs/references/cli-utilities/crdb-cli/crdb/create.md
[Staging Link](https://docs.redis.com/staging/jira-doc-1368/rs/references/cli-utilities/crdb-cli/crdb/create/)
> DOC-1368: crdb-cli create command

- content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
Staged preview: https://docs.redis.com/staging/k8s-kraken-warning/kubernetes/release-notes/k8s-6-2-10-34-2022-05/
> K8s: added warning to 6.2.10-34 RN

- content/rs/references/cli-utilities/crdb-cli/crdb/health-report.md
Staging link: https://docs.redis.com/staging/jira-doc-1376/rs/references/cli-utilities/crdb-cli/crdb/health-report/
> DOC-1376: crdb-cli crdb health-report page

- content/kubernetes/re-clusters/upgrade-redis-cluster.md
Add same upgrade warning from RN to upgrade doc.
> K8s: add upgrade warning DOC-1441

- content/rs/references/cli-utilities/crdb-cli/crdb/delete.md
Staging link: https://docs.redis.com/staging/jira-doc-1369/rs/references/cli-utilities/crdb-cli/crdb/delete/
> DOC-1369: crdb-cli crdb delete page

- content/rs/references/cli-utilities/crdb-cli/crdb/add-instance.md
Staging link: https://docs.redis.com/staging/jira-doc-1373/rs/references/cli-utilities/crdb-cli/crdb/add-instance/
> DOC-1373: crdb-cli crdb add-instance page

- content/rs/references/cli-utilities/crdb-cli/crdb/purge-instance.md
- content/rs/references/cli-utilities/crdb-cli/crdb/remove-instance.md
Staging link: https://docs.redis.com/staging/jira-doc-1375/rs/references/cli-utilities/crdb-cli/crdb/purge-instance/
> DOC-1375: crdb-cli purge-instance page

- content/embeds/hardware-requirements-embed.md
Changed recommended minimum NIC size from ">100Kbps" to ">100Mbps"
> Corrected typo in hardware-requirements-embed.md

- content/rs/references/cli-utilities/crdb-cli/crdb/flush.md
Staging link: https://docs.redis.com/staging/jira-doc-1370/rs/references/cli-utilities/crdb-cli/crdb/flush/
> DOC-1370 - crdb-cli crdb flush page

- content/rs/references/cli-utilities/crdb-cli/crdb/get.md
Staging Link: https://docs.redis.com/staging/jira-doc-1377/rs/references/cli-utilities/crdb-cli/crdb/get/
> DOC-1377: crdb-cli crdb get command

- content/modules/redisjson/active-active.md
- content/rs/databases/active-active/_index.md
[Initial preview](https://docs.redis.com/staging/jira-doc-1427/modules/redisjson/active-active/)
> RedisJSON conflict resolution

- content/rs/release-notes/rs-6-2-10-february-2022.md
hi Lance, please review this change concerning https://redislabs.atlassian.net/browse/RED-78364. Thanks!
> Adding a known issue - important

- content/modules/redisgears/jvm/classes/gearsbuilder/register.md
- content/modules/redisgears/jvm/classes/readers/keysreader.md
- content/modules/redisgears/register-events.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1358/modules/redisgears/register-events/)
> Added RedisGears register events doc

- content/rs/databases/create-database.md
This is the link that I added an alias for: https://docs.redis.com/staging/jira-doc-1454/rs/administering/creating-databases
> Added create-database alias
