RedisLabs/redislabs-docs

- content/rs/release-notes/_index.md
- content/rs/release-notes/rs-5-2-2-august-2018.md
- content/rs/release-notes/rs-5-3-beta-july-2018.md
Please change the order of the first two lines as it was in the original doc.
I.e. the correct order is:
Redis Enterprise Software 5.2.2 (August 2018) 
Redis Enterprise Software Release Notes 5.3 BETA (July 2018)
> Change weights to put in chronological order

- content/rs/getting-started/creating-database/crdbs.md
Original code was getting the key from rp1 when the point of the exercise is to get the key you set in rp1 from rp2. Also added spaces to improve formatting.
> Fix python code in crdb example

- content/rs/administering/monitoring-metrics/prometheus-integration.md
indentation is important for prometheus.yml. without the indentation, the prometheus.yml does not work.
> fix prometheus.yml indenting

- content/rs/getting-started/k8s-openshift.md
rbac.yaml and sb_rbac.yaml have been changed to relieve the need to manually edit the target namespace from sb_rbac.yaml.
Additional improvements to the article have been made to provide code readability and usability.
> sb_rbac no longer requires namespace definition

- layouts/partials/flex/head.html
This change reverts the import of the main style file (style.css) to the standard way, ie. without Hugo's fingerprinting.
> Import style.css the standard way

- resources/_gen/assets/css/theme-flex/style.css_8848f55d07695b7ff7188138f23d69e3.json
- static/theme-flex/style.css
- themes/docdock/static/js/search.js
* Reduce line spacing around code snippets
* Add context text to search results
* Prepend and append three dots to context of search result
* Do not show search result context if there is only one word.
Add vertical scroller to search results.
* Tweak regex pattern for search term matching to include more characters
> Add context text for search results (#147)

- content/rs/release-notes/rs-5-4-december-2018.md
we specify that the module version should be upgraded. Customers don't know at which level the upgrade of the module needs to be done i.e. just at the cluster level or at the DB level as well. So just added that details and also a link on how to upgrade a module.
> added more detail upgrade of module

- static/theme-flex/style.css
- themes/docdock/static/js/search.js
* Reduce line spacing around code snippets
* Add context text to search results
* Prepend and append three dots to context of search result
* Do not show search result context if there is only one word.
Add vertical scroller to search results.
* Tweak regex pattern for search term matching to include more characters
> Add context text for search results

- content/rs/concepts/memory-architecture/redis-flash.md
The metrics link at the bottom of the page leads to a 404 (not found) error.
Need to check what is the proper link for it and update the page accordingly.
> Update link in redis-flash.md

- content/rs/administering/monitoring-metrics/prometheus-integration.md
A customer pointed out that they see two node metrics (node_free_memory & node_available_memory) that show almost the same details but only one is mentioned in the documentation, node_free_memory.
They can't tell the difference between the two.
Can we add the missing metric to the page and add explanation that will cover the differences between the two metrics?
Here's the snippet provided by the customer showing the metrics:
node_free_memory{cluster="pcfrdssbx.isus.emc.com",node="1"} 5972951040.0 
node_free_memory{cluster="pcfrdssbx.isus.emc.com",node="2"} 5309752206.222 
node_free_memory{cluster="pcfrdssbx.isus.emc.com",node="3"} 13918007751.111
node_available_memory{cluster="pcfrdssbx.isus.emc.com",node="1"} 5383443201.778 
node_available_memory{cluster="pcfrdssbx.isus.emc.com",node="2"} …
> node_available_memory not documented for prometheus

- content/rs/administering/cluster-operations/maintenance-mode.md
keep_slave_shards => dont_migrate_slave_shards
skip_shards_restore => dont_restore_shards
snapshot_name => restore_from_snapshot
Possible on/off options
rladmin> node 4 maintenance_mode off
dont_restore_shards   Do not restore shards to the node
restore_from_snapshot Choose specific snapshot to restore from
<eol>                 Turn maintenance mode off for this node
rladmin> node 4 maintenance_mode on
dont_migrate_slave_shards Skip migrating slave shards out of node
<eol>                     Turn maintenance mode on for this node
> maintenance-mode.md |

- content/rs/installing-upgrading/downloading-installing.md
There is no need to add path for the socket files during the installation. By default, 5.4.2 will place the socket files in "/var/opt/redislabs/run" (and not as specified here anyway). /tmp was the default socket files path in RedisLabs versions 'lower' than 5.2.2.
> Remove installation flag for sockets location

- content/rs/administering/designing-production/networking/port-configurations.md
** I didn't make modifications to the page **
The page is missing TCP port 1968 which seems to be used internally by the DMC management thread.
It's not clear if it's used only locally within the node or also between nodes in the cluster. It doesn't look like it is accessed externally.
I think it should be added to the page.
Please confirm the use with R&D.
> TCP port 1968 missing from ports list

- .circleci/config.yml
- content/rs/administering/designing-production/security/account-management.md
- content/rs/installing-upgrading/downloading-installing.md
- layouts/partials/breadcrumb.html
- layouts/partials/flex/head.html
- layouts/partials/flex/selectnavigation.html
- layouts/partials/language-selector.html
- layouts/partials/menu.html
- layouts/partials/next-prev-page.html
- layouts/partials/original/body-beforecontent.html
- layouts/partials/post-bottom.html
- layouts/shortcodes/allchildren.html
- layouts/shortcodes/children.html
- layouts/shortcodes/expand.html
- layouts/shortcodes/relref.html
This PR fixes issues that occured with **expand** shortcode after upgrading Hugo to 0.55.5.
It also upgrades Hugo to the latest available version - 0.55.6.
> Fix expand shortcode after upgrade

- content/platforms/openshift/_index.md
`kubectl get deployment`  goes unnoticed as it is not highlighted properly.
> kubectl get deployment command highlighted

- content/rs/administering/database-operations/importing-data.md
Added clarifications on how to use mount point import.
These are required in order to use that option.
> Add detail to mount point backup explanation

- content/rs/administering/cluster-operations/maintenance-mode.md
do not backport to 5.4, as these flags were not updated in 5.4.2.
> fix maintenance_mode flag names.

- content/rs/administering/designing-production/networking/port-configurations.md
@bmansheim - I remember that we discussed this line with Yossi-
"| TCP | 9081 | For CRDB management |"
I understand that this port is used internally (in the node) and it should not be exposed outside the node. If it's correct, why did we decide to add it to this list? Do you remember?
> RED-26867 Clearly mark internal ports

- static/theme-flex/style.css
This change makes scrollbar on code snippets thinner so it does not display over the the content of the snippet. #427
> Fix scrollbar on code snippets [Fix #427]

- content/rs/administering/cluster-operations/updating-certificates.md
This pull request updates our certificate update procedure to use rladmin instead of the rest API. This makes the procedure cleaner and easily consumable for users. 
Changes include:
1. Update certificate instructions now reference rladmin
2. REST API method moved to the previous version, however, is still available.
> New cert update method through RLADMIN

- content/rc/how-to/importing-dataset-redis-cloud.md
Sharechat Confirmed that using update file permissions for the bucket to user service@redislabs-prod-clusters.iam.gserviceaccount.com instead of service@garantiadata.com solved the issue: https://redislabs.zendesk.com/agent/tickets/50675
"Seems that service@garantiadata.com is the old user and that doc on site is not updated or got overwritten. IIRC it should say service@redislabs-prod-clusters.iam.gserviceaccount.com."
> Use gserviceaccount.com account for bucket instead of garantiadata.com

- content/rs/administering/designing-production/supported-platforms.md
For customers looking for orchestration and cloud platforms, as highlighted by the SA team:
Hey all - I noticed that there is nothing on this page about K8s platform support: https://docs.redislabs.com/latest/rs/administering/designing-production/supported-platforms/
Amiram Mizne 11:20 AM
The term “platform” is probably not the best in this context but in the intended context, K8s is not a “platform”. PCF isn’t mentioned either. This isn’t the place we chose to list these orchestration/operational environments that we operate in.
This is our “platforms” landing page https://docs.redislabs.com/latest/platforms/
new messages
Jane Paek 2:07 PM
@Amiram can we still add a link to the "Platforms" landing page from our "supported-platforms" page? If I were a customer, I wouldn't know to …
> Added link to Platforms docs landing

- content/rs/installing-upgrading/upgrading.md
Suggesting a change to the wording on the note about the impact of a restart to upgraded database without replication but with persistence as it was a bit confusing.
> Downtime during persistence restore

- content/rs/administering/designing-production/security/client-connections.md
The process to update the proxy's certificate no longer require manual replacement of the certificate and a proxy restart.
It should utilize the API/rladmin capabilities.
Added a link to the detailed step for updating certificates.
Also, the common name for the certificate was incorrect so updated "redis-*.redislabs.com" to "*.redislabs.com".
> Improve certificate procedures

- content/platforms/pcf/_index.md
Warning users not to check the recovery checkbox unless conducting cluster recovery.
> Added note about cluster recovery checkbox

- content/platforms/faqs/_index.md
- content/platforms/kubernetes/kubernetes-persistent-volumes.md
FAQ now correctly reflects security enhancements:
NET_RAW capability is no longer required by PSP.
allowPrivilegeEscalaltion is set to 'false' by PSP.
Added note about the impact on ping.
Addressed RED-33428: Document spec default persistence behavior
> Reflect NET_RAW and priv. escalation change, persistence default behavior

- static/code/rs/database.json
IOPS is confusing. This panel is only applicable for RedisOnFlash and relates to IOs. Customers who don't see any data and who expect the metrics to show instantaneous operations per second are wondering why the graph as no data. Changing the title to indicate that 1) it is for RoF, and 2) it is disk I/Os seems like a good change.
> Changed the title of the IOPS panel

- content/rc/administration/configure/security.md
I suggest changing the link to the SIP limit per plan as the current link (https://redislabs.com/pricing), doesn't have the information.
In the following link, you can change the plan and see how many SIPs are supported - 
https://redislabs.com/redis-enterprise-cloud/essentials-pricing/
> Update link to SIP limits

- content/rs/administering/designing-production/networking/using-oss-cluster-api.md
Changed the multi-key disclaimer as the former was very wrong.
> Update multi-key limitation for OSS cluster API

- content/rs/administering/monitoring-metrics/prometheus-integration.md
the same change should be applied on all acc_latency metrics (read/write/other).
and should also be put in other docs we have about this metrics (rest api?).
also note that the acc_latency_max metric is completely useless IMHO, since the second with the highest latency is not necessarily the one with the highest response time, so any division attempt to get the real latency would be wrong.
not sure if we should mention that it is useless, or trim it from the docs.
> improve description of accumulated latency

- content/platforms/kubernetes/_index.md
- content/platforms/pks/_index.md
- content/rc/quick-setup-redis-cloud.md
- content/ri/memory-optimizations/reclaim-expired-keys-memory-faster.md
- content/rs/administering/monitoring-metrics/prometheus-integration.md
- content/rs/getting-started/creating-database/redis-flash.md
- content/rs/getting-started/creating-database/redistimeseries.md
- content/rs/getting-started/docker/getting-started-docker.md
- content/rs/getting-started/getting-started-crdbs.md
- content/rs/getting-started/quick-setup.md
- content/rs/installing-upgrading/configuring-aws-instances.md
- content/rs/installing-upgrading/downloading-installing.md
- content/rs/installing-upgrading/offline-installation.md
- content/rs/references/memtier-benchmark.md
- content/rs/release-notes/rs-5-5-preview-april-2019.md
- layouts/partials/flex/scripts.html
"Setup" is one word when used as a noun and two words when used as a verb ("set up"). This commit fixes all the cases I could find where the single-word form ("setup") was being used as a verb.
> Fix misuse of the word 'setup'

- content/rs/concepts/high-availability/replication.md
Changed the term 'node' to 'shard' to clarify that a) this is the data path that we're talking about and b) that this really is shards which are masters and slaves! Although a cluster does indeed have a 'master' node this node is in the control path, not the data path.
> Clarify that replication applies to shards

- content/rs/administering/designing-production/supported-platforms.md
It's not clear from the documentation that Amazon Linux 2 is not supported, according to #RED-34971
> Amazon Linux 2 is not supported

- content/platforms/kubernetes/kubernetes-logs.md
from kubectl exec -it   busybox -c <pod-name>   tail home/logs/supervisord.log tokubectl exec -it  <pod-name> -c busybox  tail home/logs/supervisord.log
> RED-36193 Fix the kubectl example commands

- content/rs/administering/designing-production/supported-platforms.md
@bmansheim - in addition, we need to check (probably with Alon, maybe Uri) whether Oracle Linux also "requires at least "Minimal Install" configuration _[- what does it mean????]_, OpenSSL 1.0.2, and firewall configuration." _[- maybe it's relevant only for the Oracle Linux 7 installations....?]_
> RED-36146 Support for Oracle Linux 7.6

- content/embeds/force-delete-pods.md
- content/platforms/kubernetes/cluster-recovery.md
- content/platforms/kubernetes/kubernetes-cluster-recovery.md
- content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
- content/rs/administering/troubleshooting/cluster-recovery.md
I think that the known limitation should be added to this page and moved out of the 5.4.10 release notes. This is not an issue that pertains to 5.4.10 and customers who are going to do a recovery are more likely to check the recovery documentation than the release notes.
I copied the text straight from the 5.4.10 release notes (and I left it there but I don't like duplicate information since it's hard to maintain. We should remove the next from the release notes IMO).
> Add k8s cluster recovery workaround to cluster recovery article

- content/rs/getting-started/quick-setup.md
This is a great 'getting started' guide for a basic deployment of Redis Enterprise. As folks might start here and then jump to the full installation instructions (including the required ports, etc), it would be great if there were a link on this page to the full installation instructions (rather than having to find it).
Note: Don't need to take my wording EXACTLY but something along those lines would be beneficial IMO
> Add a link to the full installation

- content/rs/administering/logging/rsyslog-logging.md
Issue reported by the customer Charter Communications (Spectrum) in ZD 55573
Jonathan DeLanders -
I'm not sure if this was intentional or not but from my perspective it looks wrong. The rsyslog template appears to be missing the : ( colon ) separator between host, syslog tag and time generated. This leads to a log line where the host is mashed inbetween the syslogtag and the time and would make it difficult to parse the values.
Example from the documentation.
daemon.warning:Jun1414:49:20node1event_log[3464]:{"storage_util": 90.061643120001,"global_threshold":"70″,"object":"node:1″,"state": true,"time":1434282560,"type":"ephemeral_storage"}
You can see, "node1" is between event_log and an arbitrary time. Making it difficult to extract.
This is the suggested template from the documentation …
> Correct syslog template

- content/rs/release-notes/rs-5-4-14-february-2020.md
Redisearch release notes link should be https://docs.redislabs.com/latest/modules/redisearch/release-notes/redisearch-1.4-release-notes/#redisearch-1-4-25  or maybe no need to mention the 1-4-25 but the general link only
The reference to the other modules also doesn't work
> Update module release notes links

- content/rs/installing-upgrading/file-locations.md
Socket files are not getting listed in "File Locations" (https://docs.redislabs.com/latest/rs/installing-upgrading/file-locations/) docs and cen be found only in the document about how to change the default location for socket files (https://docs.redislabs.com/latest/rs/installing-upgrading/configuring/change-location-socket-files/)
> Proposing to reference location for socket files in "File Locations"

- content/ri/using-redisinsight/troubleshooting.md
It's not immediately obvious that you can customize redisInsight to change things like the default port. If I were a customer, I would look under 'troubleshooting' for how to do this. Therefore, I think a link should be added to the 'configuring RedisInsight' page. I've now had several customers ask if this was possible so I think this would be a great addition!
> Add a link to the configuration page

- content/rs/release-notes/rs-5-6-0-april-2020.md
The link to the download location at the top of the page gives a 404 (not found) response.
Please update the link to the proper location.
> Update download link in rs-5-6-0-april-2020

- content/modules/redisearch/release-notes/v1.4/_index.md
- content/platforms/faqs/_index.md
- content/rc/faqs/_index.md
- content/ri/faqs.md
- content/rs/faqs/_index.md
- layouts/shortcodes/expand-control.html
- layouts/shortcodes/expand.html
- static/theme-flex/script.js
- static/theme-flex/style.css
- Added a new _expand-control_ shortcode which can be used along with existing _expand_ shortcode to show "Expand/Collapse All" button (like in the left side menu).
- Example added on _rc/faqs_ page.
> Add expand/collapse all shortcode for FAQ pages

- content/rs/administering/cluster-operations/updating-certificates.md
Link to 1.0.2 man pages instead of the master docs (which does not exist anymore).
> Fix broken link to OpenSSL docs

- content/ri/installing/install-redis-desktop.md
Added instructions explaining how to open Redisinsight even when Mac OS X (Catalina) won't open it up because its from an unidentified developer.
> Extended Apple installation instructions

- content/rs/concepts/data-access/persistence.md
The [persistence](https://redislabs.com/redis-features/persistence) URL (in multiple places) leads to an non-existing page.
Not sure exactly what that page was, but I believe the most suitable new URL will be - https://redislabs.com/redis-enterprise/technology/durable-redis-2/
> Non-existing page for persistence

- content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
Unless I misunderstand something, the services rigger is upgraded with the REC, not when applying the bundle.
> Remove Services Rigger from Kubernetes upgrade

- content/rc/api/how-to/using-curl.md
Using Swagger examples as-is for POST / PUT operations will  generate an error.
Modified an info message into a warning message.
> Add warning on using Swagger examples as-is

- content/ri/using-redisinsight/api.md
I have to manage several instances of Redis/RedisInsight with dynamically uris and wanted to have the process of adding the Redis instances to RedisInsight automated through the api. I drove me crazy that it didn' work like described in the docs. In the end I checked the normal workflow in the RI frontend and the history of the docs page. It stated out that instead of `/api/db/` you have to call `/api/instance/`. So in hope to help other SRE/DevOps with this
> Fix url for adding database programmatically

- .circleci/config.yml
Hugo features since 0.48:
- https://gohugo.io/content-management/archetypes/#directory-based-archetypes
- https://gohugo.io/hosting-and-deployment/hugo-deploy/
- https://gohugo.io/hugo-modules/
- Cascading Front Matter, Alphabetical Sorting, Resources Loading from Assets with Wildcards - https://github.com/gohugoio/hugo/releases/tag/v0.57.0
- .Page home will from 0.58 only return its immediate children (sections and regular pages) - https://github.com/gohugoio/hugo/releases/tag/v0.57.2
- https://gohugo.io/content-management/image-processing/#exif
- https://gohugo.io/content-management/image-processing/#image-processing-options
- https://gohugo.io/variables/pages/
- https://gohugo.io/getting-started/configuration-markup/
- https://gohugo.io/getting-started/configuration-markup/#markdown-ren …
> Upgrade to Hugo 71.1

- config.toml
- content/ri/installing/install-docker.md
RedisInsight docker container from `v1.6.0` starts with non-root user by default and redisinsight users who are migrating from previous versions should be notified on how to proceed.
Fix: https://github.com/RedisLabs/redislabs-docs/issues/886
CC: @slemeur @nishantgeorge
> Add redisinsight docker volume helper info.

- content/modules/redisearch/_index.md
Since `FT.ADDHASH` is not supported in Redis Enterprise
* I have removed the reference to FT.ADDHASH in the first section
* Add a small note at the end of the page about Commands
> FT.ADDHASH is not supported in Redis Enterprise

- content/rs/installing-upgrading/_index.md
In Pre-Requisites, added a new bullet with a recommendation for setting the OS local port usage as we had few tickets where Redis services couldn't start due to port conflict.
As a result, customers asked why this is not showing in our documentation.
Rlcheck which runs post-installation also checks for the configured port range but it doesn't do more than a warning that can easily be overlooked.
I thought this page would be the best place but if there's a better place, we can move it there.
Please verify that I added it as a bullet and didn't mess up the page's formatting.
> Prevent OS from using Redis ports

- content/rs/installing-upgrading/upgrading.md
Fixed typo in 'active-active' section on word 'active'
> Fixed Typo

- content/platforms/kubernetes/db-controller.md
The values don't quite match what is used internally.
> Fixed for persistence values in db controller

- content/platforms/kubernetes/db-controller.md
- content/platforms/openshift/getting-started-cli.md
- content/platforms/openshift/getting-started-operatorhub.md
- content/platforms/openshift/quick-start.md
Minor adjustments to make sure it is clear that you can install via the CLI for OpenShift 4.x
> Openshift 4 via the CLI

- layouts/partials/flex/body-beforecontent.html
- layouts/partials/flex/scripts.html
This dropdown is so that customers can select between the 6.x version of the docs which is the latest and the 5.x version of the docs that is in /5.6.
I tried just re-using the RS dropdown but it didn't work for me.
> Add dropdown for Platforms

- layouts/partials/flex/body-beforecontent.html
- layouts/partials/flex/scripts.html
This change hides the current version as an option in Platforms version dropdown and simplifies the version dropdown code a bit.
> Tweak platforms version selector

- content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
Changed weight so it will appear at the top, being the latest.
Added Rancher upstream K8s note around 1.18 limitations
Added link to generic Replica Of description
Added link to TLS spec docs
> Updates to latest 6.0.6-23 release notes

- content/rs/concepts/compatibility.md
Adding a few commands that aren't supported with Redis 6. This PR corrects the following
- STRALGO LCS - last minute addition to Redis 6 and not yet supported.
- ACL blocked commands
- Corrects spelling mistake in replicaof
> Updating with new commands from Redis 6

- content/modules/redisgears/installing-redisgears.md
The version integer format for modules is listed as "xxyyzz", but for major versions < 10, the format is actually "xyyzz".
> Clarification of version_integer format

- content/embeds/modules.html
https://docs.redislabs.com/staging/DOC-343-specify-RC-support/modules/
The quick start pages state that you need RS to run AI and Gears so I think we just need to specify on the landing page that they are RS only.
> DOC-343 Specify on landing page that AI and Gears are RS only

- content/rs/release-notes/rs-6-0-8-september-2020.md
- New RediSearch 2.0
- Removed the signed packages as it didn't get out for a bug (will get back in 6.0.12 or 6.2, I'll follow up on that)
- Changed modules order to match https://redislabs.com/redis-enterprise/modules/ per Pieter's request
> 6.0.8-build28

- content/ri/installing/configurations.md
This PR updates `configuration.md` to include information about the environment variable ( `REDISINSIGHT_LOG_LEVEL` ) that is used to configure the log level of the application.
**This functionality ( i.e. ability to configure log level ) will be available in RedisInsight > 1.7.0**
> [RedisInsight] Add information about log level

- content/embeds/backup-locations.md
Added clarifications for Google Cloud Storage setup as it's missing a lot of steps needed in order to configure it.
> Update backup instructions for GCP

- content/ri/using-redisinsight/troubleshooting.md
This note is relevant to all previous versions of RedisInsight as well. It can be merged after it is approved, no need to wait for the next release.
> RedisInsight: Added note about using RI with a reverse proxy.

- static/js/search.js
Currently, an empty result set is cached for queries with zero results. That means you'll see the 'no results' message once, but if you type the query a second time, you won't see the 'no results' message.
This change caches the fake document that powers the 'no results' message, so that you see it again if you type the same query.
> Cache the no results document for queries with 0 results

- content/rc/administration/configuration/backups.md
The URL is not required in the backup path syntax
> Remove the - *url:*

- content/rs/administering/designing-production/networking/using-oss-cluster-api.md
The last command is *not* executed in rladmin - so the previous description is misleading.
> change wording "rladmin" to Active-active

- content/rs/administering/designing-production/active-active.md
Under 'Active-Active database current limitations' point 3 (i.e. Active-Active databases do not support Redis modules) is outdated - 
a) I think we already support RediGears & RediSearch 2.0 (and maybe ReJSON?)
b) The link to 'Redis modules' doesn't seem to work.
I didn't make changes, just added '>>> OUTDATED <<<' on the relevant line
> Update support for modules on Active-Active

- content/embeds/tryout-redisearch-2.md
Changing the score field name in the FT.CREATE example to something else than the reserved `WEIGHT`.
Currently, the following error is returned:
```
(error) Bad arguments for weight: Could not convert argument to expected type
```
Added an example for document scoring.
> Fix FT.CREATE example and add example for document scoring

- content/platforms/openshift/getting-started-openshift-crdb.md
Removed outdated crdb/active-active document using the unsupported service broker
> Disabled outdated doc on CRDB/Active-Active for K8s

- content/rc/administration/setup/edit-subscription.md
Need to make sure its clear from docs that VPC peering is not available on Essentials
> Specify VPC peering not for Essentials

- content/rs/administering/creating-databases/_index.md
Added clarification about password definition when using a default user.
> Clarify need for default password

- content/rs/installing-upgrading/_index.md
Update recommended restriction for the ports used by the OS.
Due to RED-49152.
To start from 40k instead of 30k
> OS ports restriction recommendation

- content/rs/references/client_references/client_nodejs.md
This pull request updates the `node_redis` client page for Node.js with the following additions and improvements:
* Generally overhauls the code to modern JavaScript, fixes previous syntax errors
* Adds section for using promises and async/await
* Adds section for connecting to Redis with an ACL user
* General tidy up of the prose
I propose to keep this page as is and open another pull request to add a second page as a sibling for it to cover the `ioredis` client... then have the first paragraph of this page reference `ioredis` as an alternative and the `ioredis` page reference this one as an alternative too... saves having a generic Node.js landing page I think?
> Refreshes the node_redis client page.

- content/rs/administering/monitoring-metrics/prometheus-metrics-definitions.md
I think there's a typo in the description of 'bdb_egress_bytes' and 'bdb_egress_bytes_max'.
Since it's outgoing traffic, it would make sense that it's traffic from the DB and not to the DB.
Please verify first that my understanding is correct.
> Verify bdb_egress description

- content/rs/installing-upgrading/uninstalling.md
On the current docs, we show 3 options to find the uninstall script. The script is located in /opt/redislabs/bin and we should only provide 1 option for users to find this script
> Proper directory for uninstall script

- content/platforms/release-notes/k8s-6-0-8-20-2020-12.md
Customers who need to specify the Bootstrapper image in their YAML need to understand what that image is.
> It is important to specify what is the image for the Bootstrapper

- content/rs/concepts/data-access/consistency-durability.md
WAIT command is no longer "new" in Redis or Redis Enterprise. Removing this reference brings more official state to the doc.
> Remove reference to "new" in mentioning WAIT

- content/rs/concepts/data-access/persistence.md
remove misleading reference to "db:" where DB name or ID is needed
> Fix reference to DB in rladmin command line

- content/platforms/kubernetes/tasks/cluster-recovery.md
- content/platforms/kubernetes/tasks/ldap-on-k8s.md
- content/platforms/kubernetes/tasks/replica-of-k8s.md
- content/platforms/kubernetes/tasks/upgrading-with-operator.md
- content/platforms/kubernetes/tasks/using-kustomnize.md
Merged from #1008 for style review
> DOC-440 K8s guides for 'Developer Guides'

- content/modules/add-module-to-cluster.md
This image link is broken in https://docs.redislabs.com/latest/modules/add-module-to-cluster/
https://docs.redislabs.com/latest/images/rs/update_available-1.png
It should be:
https://docs.redislabs.com/latest/images/rs/update_available.png
> Fixes the broken image update_available

- content/rc/how-to/importing-data.md
In the import from a Redis server, fixed a typo indicating that a user should put RDB details to source DB details [see edited line].
Another point is that the section mentions "import a dataset from any publicly available Redis server" but this is not accurate.
As far as I know, import from a Redis Labs DB is not allowed. I'm not sure if there are other restrictions.
Need to check with PM to clarify that point.
I tried importing from both RS and Essentials (both publicly available) and I couldn't.
> Fix typo for importing data from Redis

- content/rs/references/client_references/client_csharp.md
StackExchange.Redis now uses stackexchange.github.io for documentation instead of the Github markdown files.
Updated two links to point to this site, one to fix a 404 and one to make it one less click for a user to get to the right page.
> Updated links to StackExchange.Redis documentation

- content/rs/administering/designing-production/networking/port-configurations.md
This port is used by envoy to push config changes and it is actively used but not mentioned. Thus this pull request
```
tcp        0      0 127.0.0.1:3343          0.0.0.0:*               LISTEN      112        27741      1707/envoy_control_ 
```
> add port 3343

- static/css/search.css
- static/js/search.js
Use a less aggressive mechanism for escaping unsafe HTML, so that we don't show users percent signs for new query syntax like `@`.
After:
> Use a friendly HTML escaping function

- static/css/search.css
My last PR applied a `li:last-child` style without scoping it to a specific class, causing many list items to get extra padding. 😅
> Fix list CSS by scoping padding correctly

- content/rc/api/how-to/enable-your-account-to-use-api.md
- layouts/shortcodes/image.html
- static/tables/redisgraph-lifecycle.csv
Extended the {{image}} shortcode to support a width parameter (and alt text).  This allows writers to control the size of the image displayed in content.
Here, the image is displayed at 75% original size.
(A future update will do this by default.)
> Update image shortcode to accept width parameter (and alt text).

- content/platforms/kubernetes/tasks/ldap-on-k8s.md
without mentioning the absolute path the command results in an error `ERROR: invalid token 'saslauthd.conf'`
> mention path in rladmin command

- static/js/search.js
The search frontend should pass the production site URL to target the right index.
> Use production search index

- static/js/search.js
With the current code, we can fill up localStorage, which results
in an exception on subsequent writes. Now we handle the exception,
and we also switch to sessionStorage, which clears at the end of
a "session," i.e. typically the life of a tab.
> Use sessionStorage instead of localStorage

- content/embeds/compatible-with-oss.md
Note: There is a plan to support MODULE LIST but it's not clear when it will be supported so better say it's not supported now and then we can remove it.
> Adding the MODULE commands to the list of blocked commands

- content/rs/getting-started/_index.md
Updating 'Creating a database' instructions to include setting the port number used in the next section.
> JIRA DOC-613: RS Getting Started doesn't show setting the DB port number

- content/rs/installing-upgrading/upgrading.md
Some CRDB customers just miss and important rule to remember: Typical upgrade for a non-CRDB cluster is to first install.sh and then rladmin upgrade DB's.
For CRDB clusters you must first install.sh all nodes on all clusters and only then rladmin upgrade db (you must not rladmin upgrade DB before all clusters are upgraded via install.sh).
> Strictly write the procedure to upgrade CRDB's

- content/platforms/kubernetes/tasks/upgrading-with-operator.md
Introduced pulling a version tag rather than cloning the repo.
TODO: add a user check for valid upgrade paths
> Update to upgrade procedure

- content/platforms/kubernetes/tasks/upgrading-with-operator.md
Using GKE, the "kubectl get deployments -l name=redis-enterprise-operator" command was resulting in nothing coming back. Changed the syntax slightly.
> changed get deployment command

- content/ri/using-redisinsight/memory-analysis.md
The rsnap doesn't actually leave the system/server where RI installed.
> Fix incorrect info about rsnap in memory analysis section. 

- content/rs/concepts/compatibility.md
- content/rs/faqs/_index.md
Some wording changes in the compatibility article. I removed the embed on the FAQ and linked it to the compatibility article instead.
> DOC-630 "upgrade" FAQ article around OSS compatibility into full article

- content/platforms/kubernetes/tasks/upgrading-with-operator.md
Formatting of list of steps for upgrade was broken, fixed that.
Clarified how to get the Redis Enterprise image tag using a newer version of Operator release notes. In addition, the old version linked to Redis Enterprise release notes which no longer exist, resulting in 404.
> fixed formatting and clarify image tag for upgrade

- content/rc/subscriptions/_index.md
There was an extra set of parentheses in the source doc; these have been removed.
> Jira-DOC-700: RC: "Manage subscriptions" page: "Delete subscription" link doesn't work.

- content/modules/add-module-to-cluster.md
There is no explanation that the v2/module endpoint only exists for RS v6.0.12 and above. I added clarification to this when adding a module via the REST API
> Added a note about the /v2/module endpoint for RS

- content/rs/administering/cluster-operations/updating-certificates.md
It's not showing as a note
{note}
Redis Enterprise Software doesn't support Diffie–Hellman key exchange (`DHE-`) ciphers.
{/note}
> Cipher configuration

- content/platforms/kubernetes/getting-started/openshift/_index.md
- content/platforms/kubernetes/getting-started/openshift/getting-started-openshift-crdb.md
Adding redirects to manage the 404 error, which was caused when the previous content was hidden, rather than being updated.
> Jira DOC-683: Openshift link on main site generates a 404

- content/rs/release-notes/rs-6-0-20-april-2021.md
Added note to reflect that Redis Enterprise isn't impacted by the found and fixed CVE on Redis opensource.
@K-Jo @AlonMagrafta FYI.
> Updated release notes around CVE-2021-32625

- content/platforms/kubernetes/concepts/managing-images.md
I am not sure where to add this or how to make it as a "warning note", but it is very important that customers will use the exact same version tags as the ones we have on dockerhub. This might apply only to the main RS image, and not the others, but better make this a good practice.
We have has multiple customer issues because they used version tags that were custom and that the operator could not parse.
> Need to add a very important note about images version tag

- content/platforms/release-notes/k8s-6-0-20-4.md
DOC-737 K8s release notes for 6.0.20-4 
pulled from: https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.0.20-4
> DOC-737 K8s 6.0.20-4 release notes

- content/rs/administering/database-operations/updating-configurations.md
@kaitlynmichael @lanceleonard
1. Happy to get another review now :) Thanks
2. What do you think about moving all these "replication backlogs" to be under [concepts / high availability] instead of here? and maybe reference from here to there? my "cons" for this move is that this is "DB configuration" section which makes more sense.
> replication backlogs update

- content/platforms/release-notes/k8s-5-4-14-2-2020-03.md
> 5.4.14-2 k8s release notes

- content/rc/rc-quickstart.md
In the RC quick start doc:
1. fixed some typos
2. updated the python module installation instruction and python script output
3. changed the capitalization of link text under more info to use sentence case
4. fixed the path of the security link under more info so that it no longer redirects back to the quick start doc
> Fixing typos and an incorrect more info link in RC quick start

- content/modules/modules-quickstart.md
- content/rc/api/examples/audit-system-logs.md
- content/rc/api/get-started/_index.md
- content/rc/api/get-started/process-lifecycle.md
- content/rc/faqs/_index.md
- content/rc/how-to/aws-zone-mapping.md
- content/rc/security/shared-responsibility-model.md
Targeted updates to update old plan names to reflect latest plans.
Includes targeted editorial fixes; however, each of these should be scheduled for a full dev edit/review.
> Update references to old plan names

- content/rs/administering/designing-production/networking/port-configurations.md
@lanceleonard @kaitlynmichael if I can kindly ask you to review me.
@guyco-redis FYI and thanks!
This is how Guy described it: (for more context)
> Starting version 6.0.12, automatic HTTP to HTTPS redirection is disabled.
> This means that if you want to poll metrics from metrics exporter, or access the CM, you’ll need to explicitly use https in your request, instead of relying on the RS old mechanism that automatically redirected all http requests to https for these services.
>  HTTP to HTTPS redirection

- content/rs/release-notes/legacy-release-notes/rs-5-2-2-august-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-2-june-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-3-beta-july-2018.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-10-december-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-14-february-2020.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-2-april-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-4-june-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-6-july-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-4-december-2018.md
- content/rs/release-notes/rs-6-0-12-january-2021.md
- content/rs/release-notes/rs-6-0-20-april-2021.md
- content/rs/release-notes/rs-6-0-8-september-2020.md
1. Replaced hard-coded internal URLs in RS release notes with relref shortcodes.
2. Added some aliases for RS release notes that were moved from /release-notes to /release-notes/legacy-release-notes at some point.
[Staged version](https://docs.redislabs.com/staging/jira-doc-677/rs/release-notes/)
> Jira DOC-677: RS replace hard-coded internal URLs in release notes

- content/rc/databases/high-availability.md
- content/rc/how-to/view-edit-cloud-account.md
- content/rc/security/database-security/network-security.md
> Jira DOC-814: RC - Clarify high-availability article

- content/rc/security/database-security/encryption-at-rest.md
Right now, the image paths on https://docs.redislabs.com/latest/rc/security/database-security/encryption-at-rest/ are broken:
Because they point to https://docs.redislabs.com/latest//images/rc/persistent-storage-encryption.png instead of https://docs.redislabs.com/latest/images/rc/persistent-storage-encryption.png.
> Fix image paths for "Encryption at rest" page

- content/platforms/faqs/_index.md
- Initial draft, plus very minor edits.  Additional review/updates needed.
> Jira DOC-784: Remove {{expand}} from K8s FAQs

- content/rs/administering/import-export/exporting-data.md
- content/rs/concepts/_index.md
- content/rs/installing-upgrading/_index.md
- content/rs/installing-upgrading/configuring/_index.md
- content/rs/installing-upgrading/configuring/centos-rhel-7-firewall.md
- content/rs/installing-upgrading/configuring/configuring-aws-route53-dns-redis-enterprise.md
- content/rs/installing-upgrading/file-locations.md
- content/rs/installing-upgrading/supported-platforms.md
- content/rs/installing-upgrading/uninstalling.md
- content/rs/installing-upgrading/upgrading.md
- content/rs/technology-behind-redis-enterprise.md
> Jira DOC-826: RS - Assorted typos/glitches in (and near) "Install and setup"

- content/platforms/release-notes/k8s-6-0-20-12-2021-07.md
We've certified on 1.18; 1.19 was written in error (my bad)
> Fixed an error in EKS supported version

- content/rs/references/client_references/_index.md
- content/rs/references/client_references/client_c.md
- content/rs/references/client_references/client_csharp.md
- content/rs/references/client_references/client_drupal.md
- content/rs/references/client_references/client_ioredis.md
- content/rs/references/client_references/client_java.md
- content/rs/references/client_references/client_nodejs.md
- content/rs/references/client_references/client_php.md
- content/rs/references/client_references/client_python.md
- content/rs/references/client_references/client_ruby.md
- layouts/shortcodes/table-children.html
1. Cleaned up the RS clients index page
2. Added link titles to the client pages
3. Added a shortcode to automatically generate a table from child pages
[Staged version](https://docs.redislabs.com/staging/jira-doc-812/rs/references/client_references/)
> Cleaned up RS clients index page and added an auto-generating table shortcode

- content/platforms/kubernetes/concepts/manage_REC_credentials.md
Composed based off document from R&D attached to DOC-781
> Doc 781 Manage REC credentials procedure

- layouts/404.html
- layouts/partials/flex/body-beforecontent.html
Removed the v5.2 option from the version dropdown list since that version reached end-of-life in December 2019.
[Staged version](https://docs.redislabs.com/staging/jira-doc-819/rs/)
> RS: Removed v5.2 from version dropdown

- content/rs/release-notes/rs-6-0-may-2020.md
Dynatrace agent installed on the cluster nodes can hamper the working on Envoy process leading to failure of UI and REST API. Prior upgrading we recommed removing Dynatrace completely or try upgrading to newer versions.
> Add dynatrace issue RED-54704 to upgrade notes

- content/platforms/faqs/_index.md
DOC-822
Main content edits lines 34-37
Other edits are for clarity/style
> Updated info on REC password and editorial changes

- content/rs/references/developing-for-active-active/_index.md
@lanceleonard @kaitlynmichael I probably need rewording here.
The underlying issue is the number of bit allocated for expiration in A/A vs regular Redis DB (49 in A/A , 64 in Redis).
Once ready - can be merged to latest
> Active Active expiration values

- content/platforms/kubernetes/tasks/run-log-collector-script.md
DOC-851 
suggested by Vikram Moule in #ask-k8s channel 8/12/2021
Staging link: https://docs.redis.com/staging/DOC-851/platforms/kubernetes/tasks/run-log-collector-script/
> Doc 851 log-collector script instructions

- content/platforms/kubernetes/concepts/node-selection.md
- content/platforms/kubernetes/concepts/sizing-on-kubernetes.md
- content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
- content/platforms/kubernetes/getting-started/openshift/quick-start.md
- content/platforms/kubernetes/getting-started/quick-start.md
- content/platforms/kubernetes/getting-started/tanzu/_index.md
- content/platforms/kubernetes/reference/cluster-options.md
- content/platforms/kubernetes/tasks/replica-of-k8s.md
also minor copy edits I spotted along the way
> DOC-871 fix broken links 

- content/platforms/kubernetes/getting-started/openshift/openshift-cli.md
Removed another reference to service broker spec.
Fix redisEnterpriseImageSpec reference to correct format, updated to latest versionTag (@kaitlynmichael I wonder if we can use a variable here to automatically retrieve the latest version number?)
> remove service broker ref, update version tag

- content/rs/administering/designing-production/networking/port-configurations.md
9081 is internal only. Active-Active management goes via reverse proxy (port 9443) and redirected to 9081.
> 9081 is internal only

- content/platforms/kubernetes/tasks/connect-to-admin-console.md
DOC-804 How to connect the rec-ui service to the admin console using port forwarding. Source: https://github.com/RedisLabs/redis-enterprise-k8s-docs#Connect-to-Redis-Enterprise-Software-web-console
> Doc-804 K8s connect to the admin console

- content/platforms/kubernetes/concepts/db-controller.md
DOC-882 Updates include making RedisEnterpriseClustername optional in REDB file, changing `service_name` to `service_names`, clarifying content and grammar.
> Doc-882 Revise Manage Databases

- content/platforms/kubernetes/reference/supported_k8s_distributions.md
- content/platforms/release-notes/k8s-6-2-4-1-2021-09.md
- content/platforms/release-notes/k8s-6-2-4-tbd-2021-09.md
DOC-818 
updated supported distros
> DOC-818 K8s Galactica release changes

- content/rs/references/developing-for-active-active/region-application-failover-active-active.md
On the 'Failback Decision' section of the 'Active-Active region application failover' docs, a comment is being rendered as valid content. [Link to section](https://docs.redis.com/latest/rs/references/developing-for-active-active/region-application-failover-active-active/#failback-decision)
This PR removes the comment
> Remove comment being displayed Active-Active region application failover 

- layouts/shortcodes/table-children.html
Example of shortcode with page description field:
{{< table-children columnNames="Name,Description" columnSources="LinkTitle,Description" enableLinks="LinkTitle" >}}
> Updated table-children shortcode to handle page description

- content/platforms/kubernetes/getting-started/openshift/_index.md
- content/platforms/kubernetes/getting-started/openshift/openshift-cli.md
- content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
Removed mention of 3.x version (deprecated) and updated links. Content needs a heavy dev edit, but that's out of the scope of this work item.
> Doc-545 Update K8s Openshift links

- content/embeds/supported-platforms-embed.md
- content/rs/administering/cluster-operations/updating-certificates.md
> Jira DOC-769: Update TLS support statement for TLS.

- content/kubernetes/reference/supported_k8s_distributions.md
Reference: 
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid-Integrated-Edition/index.html
> Updated the abbreviation for Tanzu Kubernetes Grid Integrated Edition

- content/kubernetes/reference/cluster-options.md
- content/kubernetes/reference/db-options.md
> Doc-935 add redisUpgradePolicy to REC options

- content/kubernetes/reference/db-options.md
> Doc-919 add databasePort to database options

- changelog.md
- content/kubernetes/deployment/tanzu/_index.md
- content/kubernetes/deployment/using-kustomize.md
- content/kubernetes/re-clusters/cluster-recovery.md
- content/kubernetes/re-clusters/upgrade-redis-cluster.md
- content/kubernetes/reference/cluster-options.md
- content/kubernetes/reference/db-options.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
- content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
- content/kubernetes/release-notes/k8s-6-2-8-tbd-2021-11.md
K8s release notes and supported distro update. 
Files changed: content/kubernetes/release-notes/k8s-6-2-8-tbd-2021-11.md and content/kubernetes/reference/supported_k8s_distributions.md
> Doc-900 K8s Heart of gold release updates

- content/rc/subscriptions/create-flexible-subscription.md
Virtual PC is not the correct term/expansion of VPC. VPC stands for Virtual Private Cloud. 
Microsoft has software called Virtual PC, and our customers may get confused with it. See https://support.microsoft.com/en-us/topic/description-of-windows-virtual-pc-262c8961-90e5-1125-654f-d87cd5ba16f8.
> Incorrect term for VPC

- content/embeds/modules.html
- layouts/partials/home/options.html
- static/theme-flex/script.js
- static/theme-flex/style.css
This change should prevent users from accidentally expanding the card icon images when they try to navigate via the cards on the home page.
[Home page preview](https://docs.redis.com/staging/jira-doc-991/)
[Modules preview](https://docs.redis.com/staging/jira-doc-991/modules/)
> Fixed card icon and title links

- content/modules/_index.md
- content/modules/enterprise-capabilities.md
- content/rc/databases/create-database.md
This PR:
- Updates several links to point to matrix showing RC support for Redis modules.
- Other minor edits.
Staged preview of the affected files are available:
- [Redis modules home page](https://docs.redis.com/staging/jira-doc-1039/modules/)
- RC:Create database, [General section](https://docs.redis.com/staging/jira-doc-1039/rc/databases/create-database/#general-section)
> Jira DOC-1039: Clarify RC support for modules

- layouts/shortcodes/embed-replace.html
The embed-replace shortcode allows you to replace all instances of a string that occurs within an embedded document.
**embed-md example:**
{{\<embed-replace oldString="redis" newString="Redis">}}
{{<embed-md "discovery-clients.md">}}
{{\</embed-replace>}}
This example replaces all occurrences of lowercase "redis" with the properly capitalized "Redis".
**embed-html example:**
{{\<embed-replace oldString="embed" newString="embed replacement">}}
{{<embed-html "sample.html">}}
{{\</embed-replace>}}
In this example, the original text "this is a sample embed test" becomes "this is a sample embed replacement test".
> Added embed-replace shortcode

- content/kubernetes/re-databases/set-up-ingress-controller.md
The link was incorrect as it referred to a different product.
The Getting Started link is correct and it turns out that the Getting Started page is also the installation page, so all we have to do is simply keep the Getting Started link and get rid of the Installation link.
> Removed the HAproxy Ingress installation link

- content/rc/subscriptions/create-flexible-subscription.md
- static/theme-flex/style.css
- Adding shard descriptions & other minor edits
> DOC-1044: RC - Add shard descriptions to Create Flexible topic

- content/embeds/supported-platforms-embed.md
Removed references to the platforms we stopped supporting in 2020.
Updated the naming of "Platforms" to "Redis Enterprise Software on Kubernetes" to reflect the change in documentation structure.
> Removed platforms no longer supported

- content/kubernetes/re-databases/set-up-ingress-controller.md
It was set to 443, and this is not correct. The port to use here is the port of the database service.
> Database port was wrong in the ingress

- content/rs/administering/database-operations/eviction-policy.md
the `volatile-random` was duplicated on table.
> Remove duplicated eviction policy on table

- content/ri/release-notes/v2.0.2.md
commit ca7aa538f3c47d11a404f78bd2d47531d212aab9 from https://github.com/RedisLabs/redislabs-docs/blob/release-ri-v2.0/content/ri/release-notes/v2.0.2.md needs to be on master as well.
> RI 2.0.3 changes from commit ca7aa53 on 2.0 release branch

- content/kubernetes/re-databases/ingress_routing_with_istio.md
DOC-994
Staging: https://docs.redis.com/staging/jira-doc-994/kubernetes/re-databases/ingress_routing_with_istio/
based off: https://redislabs.atlassian.net/wiki/spaces/K8s/pages/3199008780/Istio+as+an+Ingress+controller+-+Installation+configuration+and+accessing+a+Redis+Enterprise+database+from+outside+the+K8S+cluster
> DOC-994 Istio ingress configuration

- content/kubernetes/deployment/openshift/_index.md
- content/kubernetes/deployment/openshift/openshift-cli.md
- content/kubernetes/deployment/quick-start.md
- content/kubernetes/re-clusters/create-aa-database.md
- content/kubernetes/re-databases/ingress_routing_with_istio.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/_index.md
- content/kubernetes/release-notes/k8s-5-4-10-8-january-2020.md
- content/kubernetes/release-notes/k8s-5-4-14-2-2020-03.md
- content/kubernetes/release-notes/k8s-6-0-12-5-2021-02.md
- content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
- content/kubernetes/release-notes/k8s-6-0-20-4-2021-05.md
- content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
- content/kubernetes/release-notes/k8s-6-0-6-23-2020-08.md
- content/kubernetes/release-notes/k8s-6-0-6-24-2020-08.md
- content/kubernetes/release-notes/k8s-6-0-6-6-2020-06.md
- content/kubernetes/release-notes/k8s-6-0-8-1-2020-10.md
- content/kubernetes/release-notes/k8s-6-0-8-20-2020-12.md
- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
- content/kubernetes/release-notes/k8s-6-2-8-10-2022-01.md
- content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
- content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Updated pages: 
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/release-notes/
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/deployment/openshift/_index/
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/deployment/openshift/openshift-cli/
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/re-clusters/create-aa-database/
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/re-databases/ingress_routing_with_istio/
- https://docs.redis.com/staging/release-k8s-intrepid/kubernetes/release-notes/_index/
Jiras:
DOC-994
DOC-1071
DOC-1091
DOC-995
DOC-1092
> K8s Intrepid release

- content/rc/security/vpc-peering.md
While this documentation gives all of the relevant details on setting up VPC peering, it should also include a note (possibly highlighted or in a section that draws the eyes of the user) that the application connection string needs to be altered to point to the internal endpoint now. While this might seem obvious, there have been a couple of cases where customers enabled VPC peering, but didn't switchover the endpoints. This has led to these customers incurring large network costs due to the egress traffic traversing public internet. Again, this is in rare cases where there is high egress traffic, but it's easy enough to add the note and will likely prevent these future issues.
> Add flag that advises using the internal endpoint

- content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
[Staged preview](https://docs.redis.com/staging/redistimeseries-release-notes/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes/)
> Added RedisTimeSeries v1.4.14 release notes

- .circleci/config.yml
- content/embeds/modules.html
- content/modules/enterprise-capabilities.md
- content/modules/redisai/_index.md
- content/modules/redisbloom/_index.md
- content/modules/redisearch/_index.md
- content/modules/redisgears/_index.md
- content/modules/redisgraph/_index.md
- content/modules/redisjson/_index.md
- content/modules/redistimeseries/_index.md
This change reorders the modules in the hero list, the TOC, and the enterprise capabilities doc (for consistency).
> DOC-1030: Reorder modules in TOC and other lists

- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[Staged preview](https://docs.redis.com/staging/redisgraph-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added RedisGraph v2.8 GA release notes

- content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
[Staged preview](https://docs.redis.com/staging/redistimeseries-release-notes/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes/)
> Added release notes for RedisTimeSeries v1.6.9

- content/rs/references/rest-api/requests/cluster/ldap.md
In the example JSON body, the `starttls` entry is boolean, so I fixed the documentation to use `false` instead of `"disabled"`
> Fixed parameter type for starttls entry in example JSON body

- content/modules/enterprise-capabilities.md
- content/modules/redisearch/_index.md
- content/rs/administering/designing-production/networking/using-oss-cluster-api.md
- content/rs/concepts/data-access/oss-cluster-api.md
Staged previews of the updates:
[RS: Use the OSS Cluster API](https://docs.redis.com/staging/jira-doc-1171/rs/administering/designing-production/networking/using-oss-cluster-api/)
[Modules: Enterprise feature compatibility](https://docs.redis.com/staging/jira-doc-1171/modules/enterprise-capabilities#footnotes)
[Modules: RediSearch landing page](https://docs.redis.com/staging/jira-doc-1171/modules/redisearch/)
> Documented that OSS Cluster API + RediSearch is not supported

- content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
- content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
[RediSearch 2.2.9 release notes](https://docs.redis.com/staging/modules_release_notes/modules/redisearch/release-notes/redisearch-2.2-release-notes/)
[RedisJSON 2.0.7 release notes](https://docs.redis.com/staging/modules_release_notes/modules/redisjson/release-notes/redisjson-2.0-release-notes/)
> Added release notes for RediSearch and RedisJSON

- content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
[Staged preview](https://docs.redis.com/staging/bloom-release-notes/modules/redisbloom/release-notes/redisbloom-2.2-release-notes/)
> Added RedisBloom v2.2.14 release notes

- utilities/local_pdf.sh
Run this script to create a PDF of a Redis doc on demand.
Prerequisites: 
- Local Hugo server is running.
- Installed wkhtmltopdf command-line utility.
Example commands: 
1) Create a PDF in the current directory: 
`./local_pdf.sh /content/rc/rc-quickstart.md` 
2) Create a PDF in the current directory and specify the PDF name: 
`./local_pdf.sh /content/rc/rc-quickstart.md rc-quick.pdf` 
3) Create a PDF in a different directory: 
`./local_pdf.sh /content/rc/rc-quickstart.md <destination_filepath>/rc-quick.pdf`
> Added a script to create a PDF locally

- content/kubernetes/deployment/openshift/openshift-operatorhub.md
New supported domain is https://raw.githubusercontent.com because https://raw.githubuser.com is no longer secure. This was the only two instances of the incorrect link I found in our repo.
> DOC-1232 update link to raw.githubusercontent.com

- content/kubernetes/reference/cluster-options.md
Integrated redisEnterpriseNodeResources notes into main text. I also clarified that both limits and requests are integer values.
> DOC-1239 integrate cluster option notes

- utilities/shortcode_checker/local_check.sh
This script searches the content files and outputs file paths and line numbers for suspected broken shortcodes.
To run the shortcode checker locally:
```sh
$ cd utilities/shortcode_checker
$ ./local_check.sh
```
> Added script to verify shortcodes locally

- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[Staged preview](https://docs.redis.com/staging/graph-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added RedisGraph v2.8.10 release notes

- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[Staged preview](https://docs.redis.com/staging/graph-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added RedisGraph v2.8.11 release notes

- content/kubernetes/deployment/quick-start.md
- content/kubernetes/re-clusters/delete_custom_resources.md
Three changes that came out of our 3/31/22 sync: 
- add mention of separate bundle for OpenShift
- add more info that finalizer only fails when operator isn't working right
- when deleting from a specific namespace, must edit the webhook
- moved troubleshooting section to bottom of article
[Staged Preview](https://docs.redislabs.com/staging/jira-doc-941-rev/kubernetes/re-clusters/delete_custom_resources/)
> Review feedback Doc-941

- content/rs/security/admin-console-security/user-security.md
Staging link: https://docs.redis.com/staging/jira-doc-1266/rs/security/admin-console-security/user-security/
Changed username to user email for the rladmin password reset command.
> DOC-1266 RS - Change username to user email for password reset command

- content/rs/references/rladmin.md
This PR fixes `cluster create` input on the RS rladmin page from user name to user email, as specified in [DOC-1129](https://redislabs.atlassian.net/browse/DOC-1129).
[Preview](https://docs.redis.com/staging/jira-doc-1129/rs/references/rladmin/#cluster-create)
> RS: rladmin page should clarify that username must be a mail

- content/kubernetes/re-databases/set-up-ingress-controller.md
Staging link: https://docs.redis.com/staging/jira-doc-1292/kubernetes/re-databases/set-up-ingress-controller/
- Used markdown \``` to show code instead of tabs. 
- Changed formatting of big JSON output at the end. 
- Changed "If you choose to use a previously created database" title to "Use a previously created database".
> DOC-1292 K8s: "Copy to clipboard" button scrolls with text in code snippet

- content/rs/concepts/data-access/discovery-service.md
- content/rs/connections/_index.md
- content/rs/connections/supported-clients-browsers.md
- content/rs/connections/testing-client-connectivity.md
This PR adds a **Connections** section to RS and moves two topics from **Administering** (**Supported client browsers** and **Testing client connectivity**), as specified in [DOC-1229](https://redislabs.atlassian.net/browse/DOC-1229). 
[Preview](https://docs.redis.com/staging/jira-doc-1229b/rs/connections/)
> RS reorg: Connections section

- content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
Staging link: https://docs.redis.com/staging/jira-doc-1307/modules/redisjson/release-notes/redisjson-2.0-release-notes/
Added the [RedisJSON v. 2.0.8 release notes](https://github.com/RedisJSON/RedisJSON/releases/tag/v2.0.8).
> DOC-1307 - Modules: RedisJSON v. 2.0.8 Release notes

- content/modules/redisearch/redisearch-2-upgrade.md
Updated **Upgrade a database to RediSearch 2.x** article:
1. Removed -l option from RediSearch_Syncer.py syntax
2. First round of copy edits
3. Fixed some outdated links
[Staged preview](https://docs.redis.com/staging/jira-doc-1334/modules/redisearch/redisearch-2-upgrade/)
> Edits for upgrade RediSearch 1.x DB to 2.x

- content/rs/references/cli-utilities/rladmin/cluster/_index.md
- content/rs/references/cli-utilities/rladmin/cluster/certificate.md
- content/rs/references/cli-utilities/rladmin/cluster/config.md
- content/rs/references/cli-utilities/rladmin/cluster/create.md
- content/rs/references/cli-utilities/rladmin/cluster/debug_info.md
- content/rs/references/cli-utilities/rladmin/cluster/join.md
- content/rs/references/cli-utilities/rladmin/cluster/recover.md
- content/rs/references/cli-utilities/rladmin/cluster/reset_password.md
- content/rs/references/cli-utilities/rladmin/cluster/running_actions.md
- content/rs/references/cli-utilities/rladmin/cluster/stats_archiver.md
- layouts/shortcodes/table-children.html
[Staged preview](https://docs.redis.com/staging/jira-doc-1316/rs/references/cli-utilities/rladmin/cluster/)
This PR also includes an update to the `table-children` shortcode. This change allows you to limit which child pages appear in a generated table.
For example, I added either `tags: ["configured"]` or `tags: ["non-configured"]` to the front matter of each `rladmin cluster` command page.
To generate a table that only includes commands that are tagged as "configured," I used this shortcode on the `rladmin cluster` index page and set the new optional field `limitTags` to "configured":
```sh
{{<table-children columnNames="Command,Description" columnSources="linkTitle,Description" enableLinks="linkTitle" limitTags="configured">}}
```
> Reorg rladmin cluster commands

- content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
- content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
[RedisBloom release notes](https://docs.redis.com/staging/modules-release-notes/modules/redisbloom/release-notes/redisbloom-2.2-release-notes/)
[RedisTimeSeries release notes](https://docs.redis.com/staging/modules-release-notes/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes/)
> Added release notes for RedisBloom 2.2.15 and RedisTimeSeries 1.6.10

- content/rs/references/cli-utilities/rladmin/recover.md
Staging link: https://docs.redis.com/staging/jira-doc-1327-actual/rs/references/cli-utilities/rladmin/recover/
Still waiting on a couple of things:
- I haven't been able to figure out how to get databases into recovery mode, so I haven't been able to run `rladmin recover` commands on the databases in my cluster. 
- Awaiting feedback from Alon or Amiram about the import from s3 feature - not sure if this is something we want to document or not.
> DOC-1327: RS CLI Utilities - rladmin recover page

- content/rs/references/cli-utilities/rladmin/cluster/join.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1413/rs/references/cli-utilities/rladmin/cluster/join/)
> Removed name option from rladmin cluster join

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
- content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
[RediSearch preview](https://docs.redis.com/staging/module-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)
[RedisGraph preview](https://docs.redis.com/staging/module-release-notes/modules/redisgraph/release-notes/redisgraph-2.4-release-notes/)
> Added release notes for RediSearch v2.4.8, RedisGraph v2.4.14

- content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
- content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
[RedisJSON release notes](https://docs.redis.com/staging/module-release-notes/modules/redisjson/release-notes/redisjson-2.0-release-notes/)
[RedisTimeSeries release notes](https://docs.redis.com/staging/module-release-notes/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes/)
> Added release notes for RedisJSON v2.0.9, RedisTimeSeries v1.6.13

- content/embeds/supported-platforms-embed.md
We should have a section in this page: https://docs.redis.com/latest/rs/installing-upgrading/upgrading/
that explains OS upgrade.
Meanwhile I figured the OS page is the most OK one to mention this limitation.
> RHEL upgrade modules limitations

- content/rs/references/cli-utilities/crdb-cli/crdb/remove-instance.md
Staging link: https://docs.redis.com/staging/jira-doc-1374/rs/references/cli-utilities/crdb-cli/crdb/remove-instance/
The purge-instance PR is #1977. This one needs to be merged before that one.
> DOC-1374: crdb-cli crdb remove-instance page

- content/kubernetes/re-clusters/connect-to-admin-console.md
Tiny fix to the default port (8843 --> 8443) used to access the RE admin console via a Kubernetes service port.
> Fix default port for admin console via Kubernetes

- content/kubernetes/re-databases/set-up-ingress-controller.md
pathType is now mandatory; provided a default of Prefix.
serviceName has been replaced by service.name
servicePort has been replaced by service.port.number
> Changes in Ingress spec in Kubernetes 1.19

- content/rs/clusters/maintenance-mode.md
- content/rs/clusters/optimize/turn-off-services.md
- content/rs/clusters/remove-node.md
- content/rs/databases/import-export/flush-db-crdb.md
- content/rs/security/access-control/manage-users/login-lockout.md
- content/rs/security/access-control/manage-users/manage-passwords.md
- content/rs/security/certificates/updating-certificates.md
Duplicate of #1938. Opening a new PR here because of the RS Reorg stuff that has been merged to master - there were too many merge conflicts and too much of a possibility for merge mistakes that it would be easier to start fresh.
Staging Links:
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/clusters/maintenance-mode/
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/clusters/optimize/turn-off-services/
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/clusters/remove-node/
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/databases/import-export/flush-db-crdb/
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/security/access-control/manage-users/login-lockout/
https://docs.redis.com/staging/jira-doc-1415-with-reorg/rs/security/access-control/ …
> DOC-1415: Identify existing REST API Examples in RS docs and simplify the presentation

- content/kubernetes/re-clusters/upgrade-redis-cluster.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-6-2-10-45-2022-07.md
Jira: DOC-1498
Staging pages:
-  https://docs.redis.com/staging/jira-doc-1498/kubernetes/release-notes/k8s-6-2-10-45-2022-07/
- https://docs.redis.com/staging/jira-doc-1498/kubernetes/reference/supported_k8s_distributions/
> K8s 6.2.10-45 Lucy release notes and distro changes 

- content/rs/release-notes/rs-6-2-10-february-2022.md
I've added the known limitations from 6.2.8 that are still relevant to 6.2.10. I've also reworded how we refer to previously fixed limitations from 6.2.4.
> updated known limitations

- content/rs/references/client_references/client_nodejs.md
The npm package redis had changed params of redis.createClient, the params in the article were wrong, and will result in default behavior(connecting to 127.0.0.1:6379).
> Fix legacy connection params.

- content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
[Staged preview](https://docs.redis.com/staging/timeseries-release-notes/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes/)
> Added RedisTimeSeries v1.6.17 release notes

- content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[RedisBloom](https://docs.redis.com/staging/module-release-notes/modules/redisbloom/release-notes/redisbloom-2.2-release-notes/)
[RedisGraph](https://docs.redis.com/staging/module-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added release notes for RedisBloom v2.2.18 and RedisGraph v2.8.16

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[RedisGraph](https://docs.redis.com/staging/module-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
[RediSearch](https://docs.redis.com/staging/module-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/)
> Added release notes for RedisGraph v2.8.17, RediSearch v2.4.10

- content/rs/monitoring-metrics/prometheus-integration.md
https://redislabs.atlassian.net/browse/DOC-607
Updated the language for 'Getting started' on the [Prometheus integration](https://docs.redis.com/latest/rs/monitoring-metrics/prometheus-integration/) page to be less confusing for users.
These changes are only helpful for docker, and since this is RS specific this only works for users not on windows or m1.
> clarifying getting 'getting started' for prometheus integration

- content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md
Changed RedisJSON v2.2 release notes to a draft to hide them from the ToC for now.
[Staged preview](https://docs.redis.com/staging/json-release-notes/modules/redisjson/release-notes/)
> Change RedisJSON v2.2 release notes to a draft

- content/modules/redisjson/redisjson-quickstart.md
Updated RedisJSON quick start:
- Updated examples to use JSONPath instead of legacy path
- Streamlined/clarified examples
- Fixed reported bugs (DOC-1515)
- Copy edits
- Added links for commands and JSON path syntax
[Staged preview](https://docs.redis.com/staging/jira-doc-1540/modules/redisjson/redisjson-quickstart/)
> Updated RedisJSON quick start

- content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
[Staged preview](https://docs.redis.com/staging/graph-release-notes/modules/redisgraph/release-notes/redisgraph-2.8-release-notes/)
> Added RedisGraph v2.8.19 release notes

- content/modules/redisjson/_index.md
[Staged preview](https://docs.redis.com/staging/jira-doc-1601/modules/redisjson/)
> JSON: Key name rules only apply to legacy path syntax

- layouts/partials/footer.html
- static/theme-flex/style.css
Steps to reproduce/see fix:
Go to [RediSearch quick start](https://docs.redis.com/latest/modules/redisearch/redisearch-quickstart/)  in incognito mode to see the cookies banner.
Scroll down the page until the Copy to clipboard button from a code example appears on top of the cookies banner.
Go to the [Staging version of the Quick Start](https://docs.redis.com/staging/jira-doc-1297/modules/redisearch/redisearch-quickstart/) in incognito mode to see that the copy to clipboard button no longer appears on top of the banner.
> DOC-1297: Copy to clipboard button overlaps the cookies banner

- content/kubernetes/deployment/quick-start.md
The existing documentation includes a command to verify the operator deployment is running, which uses a label selector for a label that isn't set on the operator deployment. This PR fixes the command to address the deployment by its name.
> Avoid label selector in operator deployment verification

- content/rs/release-notes/rs-6-2-18.md
- content/rs/security/audit-events.md
- content/rs/security/internode-encryption.md
* Initial draft
* Update rs-6-2-18.md
Removed RHEL 8.6 (its from 6.2.12)
Added MD5 values
Changed the audit (we do not track historical events only real time, but the data is kept and allows admin to analyze it later) Changed the "breaking change" notice a bit to reflect that this is not a common or desired situation
* Update rs-6-2-18.md
* Update rs-6-2-18.md
* Update rs-6-2-18.md
* Updating audit events article
* Additional updates/edits
* Moar edits/fixes
Co-authored-by: adisht <36517802+adisht@users.noreply.github.com>
> RS - DOC-1616: v6.2.18 release notes and supporting docs (#2156)

- content/kubernetes/reference/supported_k8s_distributions.md
Update supported distros to current 6.2.12-1 release values.
> K8s: update supported distros

- content/kubernetes/re-clusters/create-aa-database.md
Updated ingress annotation for creating Active-Active database on K8s. 
Jira: DOC-1625
Staged preview: https://docs.redis.com/staging/jira-doc-1625//kubernetes/re-clusters/create-aa-database/#using-ingress-controller
> DOC-1625 fix HAproxy ingress annotations 

- content/rs/databases/import-export/export-data.md
- content/rs/databases/import-export/schedule-backups.md
Changed the AWS S3, GCP Storage, and Azure Blob sections of the backup and export database articles to better reflect the procedure for Software. Both pages are very similar - so you can make any suggestions for one and I'll carry them over onto the other one.
https://docs.redis.com/staging/jira-doc-1628/rs/databases/import-export/export-data/#aws-simple-storage-service
https://docs.redis.com/staging/jira-doc-1628/rs/databases/import-export/schedule-backups/#aws-simple-storage-service
> DOC-1628: Wrong documentation for DB backup & export on RS

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
Staging link: https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/
> Added Redisearch 2.4.15 release notes

- content/rs/clusters/monitoring/_index.md
Staging link: https://docs.redis.com/staging/jira-doc-1703/rs/clusters/monitoring/#sending-alerts-by-email
The last two links in the article were pointing to pages that are no longer there.
> DOC-1703: Fixed 404s in Monitoring entry page

- content/rs/installing-upgrading/customize-user-and-group.md
Hi, I've edited to reflect that custom install is supported for both RHEL 7 & RHEL 8 (and not just RHEL 7). I'd like Alon Shmueli to confirm before we change.
> Custom install platform support

- content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
Staging link: https://docs.redis.com/staging/search-release-notes/modules/redisearch/release-notes/redisearch-2.4-release-notes/
> RediSearch 2.4.16 Release Notes

- content/rs/references/client_references/client_csharp.md
References in the sample code to redis OSS default 6379. Reference to running Redis server with TLS to redis OSS docs changed to enterprise TLS reference.
> Fix references to OSS

- content/kubernetes/security/manage-rec-certificates.md
- content/rs/references/cli-utilities/rladmin/cluster/certificate.md
- content/rs/references/rest-api/requests/cluster/certificates/_index.md
- content/rs/references/rest-api/requests/cluster/update-cert.md
- content/rs/security/certificates/_index.md
- content/rs/security/certificates/create-certificates.md
- content/rs/security/certificates/updating-certificates.md
Initial RS certificates updates:
- Created a certificates table intended to be the source of truth for self-signed certificate names in RS.
- Added a more detailed description for each certificate.
- Replaced repeated certificate lists scattered throughout the docs with links to the main certificates table.
[Staged preview](https://docs.redis.com/staging/jira-doc-1807/rs/security/certificates/)
> RS certificates table

- content/rs/installing-upgrading/upgrading.md
- content/rs/references/rest-api/objects/node.md
- content/rs/references/rest-api/requests/nodes/status.md
- content/rs/release-notes/rs-6-2-18.md
- New [`/nodes/status` reference](https://docs.redis.com/staging/jira-doc-1704/rs/references/rest-api/requests/nodes/status/)
- Mentioned `/nodes/status` in [upgrade cluster prerequisites](https://docs.redis.com/staging/jira-doc-1704/rs/installing-upgrading/upgrading/#upgrade-prerequisites)
- Linked to `/nodes/status` reference in [v6.2.18 release notes](https://docs.redis.com/staging/jira-doc-1704/rs/release-notes/rs-6-2-18/#enhancements-added-in-6218-49-october-release)
> RS /nodes/status REST API requests

- changelog.md
- content/embeds/supported-platforms-embed.md
- content/glossary/_index.md
- content/kubernetes/_index.md
- content/kubernetes/architecture/_index.md
- content/kubernetes/architecture/operator.md
- content/kubernetes/deployment/_index.md
- content/kubernetes/deployment/deployment-options.md
- content/kubernetes/deployment/openshift/_index.md
- content/kubernetes/deployment/openshift/openshift-cli.md
- content/kubernetes/deployment/openshift/openshift-operatorhub.md
- content/kubernetes/deployment/quick-start.md
- content/kubernetes/deployment/using-kustomize.md
- content/kubernetes/faqs/_index.md
- content/kubernetes/memory/node-selection.md
- content/kubernetes/old-index.md
- content/kubernetes/re-clusters/connect-prometheus-operator.md
- content/kubernetes/re-databases/db-controller.md
- content/kubernetes/re-databases/set-up-ingress-controller.md
- content/kubernetes/reference/_index.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/k8s-5-4-10-8-january-2020.md
- content/kubernetes/release-notes/k8s-6-0-6-6-2020-06.md
- content/kubernetes/security/_index.md
- content/kubernetes/security/manage-rec-credentials.md
- content/rs/security/access-control/ldap/cluster-based-ldap-authentication.md
Corrected product name to "Redis Enterprise for Kubernetes" as well as removed the word operator when it was actually referring to the whole product. 
Staged Preview: https://docs.redis.com/staging/jira-doc-1772/latest/kubernetes/
Jira: DOC-1772
> K8s product name cleanup

- layouts/_default/baseof.html
- layouts/partials/banner-article.html
- layouts/partials/flex/body-beforecontent.html
- layouts/shortcodes/banner-article.html
- static/theme-flex/style.css
There are now 2 methods to add an in-page banner to articles (appears beneath the article title).
Shortcode method (single page only):
- Add the `banner-article` shortcode directly after the front matter of a Markdown file
- The banner only appears on the page where you added the `banner-article` shortcode
- You can adjust the banner's color with the optional shortcode param `bannerColor`
```Markdown
---
Title: The article's title
<other front matter>
---
{{<banner-article bannerColor="#fff8dc">}}
This is preview content. See the [latest version](https://docs.redis.com/latest/) of the site.
{{</banner-article>}}
The main text of your article starts here...
```
Front matter method (single or multi page):
- Add `bannerText` and optionally `bannerLink` and/or `bannerChildren` to a Markdown …
> New in-page banner shortcode & partial

- content/kubernetes/deployment/quick-start.md
Separate shell script from output so copy/paste can be used.
> Separate shell script

- website.json
Added a redirect so selecting the latest (v6.x) k8s version from the version dropdown list redirects you to latest (v6.2) instead of the 6.0 snapshot.
> Redirect k8s v6.x to latest

- content/kubernetes/release-notes/k8s-6-2-18-41-jan-2023.md
- content/kubernetes/release-notes/k8s-6-2-18-41.md
- Added support for 6.2.18-72 images
- Separated the OpenShift specific images from the other images 
- Added the name of the OLM bundle
[6.2.18-41 Jan 2023](https://docs.redis.com/staging/jira-doc-1859/kubernetes/release-notes/k8s-6-2-18-41-jan-2023/)
[6.2.18-41 Dec 2022]((https://docs.redis.com/staging/jira-doc-1859/kubernetes/release-notes/k8s-6-2-18-41/))
> K8s: 6.2.18-41 Jan 2023 release notes

- content/rs/databases/durability-ha/_index.md
Staging link: https://docs.redis.com/staging/jira-doc-1720/rs/databases/durability-ha
> DOC-1720: Edit down descriptions for databases/durability-ha index page

- content/kubernetes/re-clusters/multi-namespace.md
Jira: DOC-1827
Staged preview: https://docs.redis.com/staging/jira-doc-1827/kubernetes/re-clusters/multi-namespace/
SME: @zcahana 
I removed the ServiceAccount entry for the admission controller in the RoleBinding yaml example.
> DOC-1827 Remove ServiceAccount for admission

- content/rs/databases/create.md
The UI enforces that the following for the database name: "Database name must be up to 63 characters long, include only letters, digits, or hyphen ('-'), start with a letter or digit, and end with a letter or digit."
This edit makes the docs consistent with the create criteria
> Update create.md to fix database naming criteria

- content/rs/references/metrics/active-active.md
- content/rs/references/metrics/database-operations.md
- content/rs/references/metrics/redis-on-flash.md
- content/rs/references/metrics/resource-usage.md
https://docs.redis.com/staging/jira-doc-1835/rs/references/metrics/redis-on-flash/
https://docs.redis.com/staging/jira-doc-1835/rs/references/metrics/database-operations/
https://docs.redis.com/staging/jira-doc-1835/rs/references/metrics/resource-usage/
> DOC-1835 and DOC-1836: Metrics Reference: Redis on Flash and Active-Active metrics

- content/rc/security/database-security/tls-ssl.md
The PEM bundle does not contain the GlobalSign Intermediate CA (only the root)
> Fix PEM bundle contents

- content/embeds/supported-platforms-embed.md
- content/rs/databases/import-export/import-data.md
- content/rs/networking/port-configurations.md
- content/rs/references/cli-utilities/rladmin/node/remove.md
- content/rs/references/rest-api/objects/bdb/_index.md
- content/rs/references/rest-api/objects/cluster/_index.md
- content/rs/release-notes/legacy-release-notes/_index.md
- content/rs/release-notes/legacy-release-notes/rs-5-5-preview-april-2019.md
- content/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
- content/rs/release-notes/rs-6-4-2.md
- content/rs/security/tls/enable-tls.md
- [Release notes](https://docs.redis.com/staging/release-rs-diablo-m1/rs/release-notes/rs-6-4-2/)
- [Supported platforms](https://docs.redis.com/staging/release-rs-diablo-m1/rs/installing-upgrading/supported-platforms/#supported-platforms) and [Ubuntu 20](https://docs.redis.com/staging/release-rs-diablo-m1/rs/installing-upgrading/supported-platforms/#ubuntu-20-rejects-sha1-certificates)
- [mTLS full subject](https://docs.redis.com/staging/release-rs-diablo-m1/rs/security/tls/enable-tls/#client) updates - allow multiple Organizational Unit (OU) values
> DOC-1921 RS v6.4.2-43 March release notes and docs

- content/rc/cloud-integrations/_index.md
- content/rc/cloud-integrations/aws-cloud-accounts/_index.md
- [Cloud integrations](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/) - hid archived docs so they no longer appear in the main ToC
- Archived content:
- [AWS cloud accounts](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/aws-cloud-accounts/)
- [Create IAM resources](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/aws-cloud-accounts/iam-resources/)
- [AWS console](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/aws-cloud-accounts/iam-resources/aws-console/)
- [CloudFormation](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/aws-cloud-accounts/iam-resources/cloudformation/)
- [Terraform](https://docs.redis.com/staging/jira-doc-1876/rc/cloud-integrations/aws-cloud-accounts/iam-re …
> Archived self-managed AWS account docs

- content/rc/databases/monitor-performance.md
Staging link: https://docs.redis.com/staging/jira-doc-1879/rc/databases/monitor-performance
> DOC-1879: Add metrics reference links to Redis Cloud monitor documentation

- content/kubernetes/networking/external-routing.md
The istio link is wrong and is misleading users, causing them to incorrectly create Gateway and Virtual service which is exactly the opposite of what is needed.
> The istio link points to the wrong page

- content/rs/references/rest-api/objects/crdb/database_config.md
Added missing REST API object fields for CRDB creation, cherry-picked from PR #2451.
[Staged preview](https://docs.redis.com/staging/crdb-api-patch/rs/references/rest-api/objects/crdb/database_config/)
> Added missing fields for CRDB creation

- static/code/rs/cluster.json
- static/code/rs/database.json
- static/code/rs/node.json
This PR replaces the preconfigured dashboards provided in Step 6 of the [Prometheus integration with Redis Enterprise Software](https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-integration/)
The current json configurations:
- `database.json`
- `node.json`
- `cluster.json`
Use a variable `${DS_PROMETHEUS1}`, however, this causes Grafana to Report a Templating error `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS1} was not found` and the dashboards will not load.
See [Support dashboard variables in dashboard provisioning](https://github.com/grafana/grafana/issues/10786#top)
#10786] specifically [workaround comment](https://github.com/grafana/grafana/issues/10786#issuecomment-383931147) and [explanation comment](https://github.com/grafana/grafana/issues/10786#issue …
> Workaround to Grafana Datasource issue

- content/kubernetes/faqs/_index.md
Remove mentions of pod security policy (deprecated)
> K8s: remove pod security policy DOC-533

- content/kubernetes/deployment/openshift/openshift-cli.md
- content/kubernetes/deployment/quick-start.md
DOC-1839
Replace kubectl commands in the OpenShift CLI guide with the oc command. 
Staged preview: https://docs.redis.com/staging/DOC-1839/kubernetes/deployment/openshift/openshift-cli/
> DOC-1839 replace kubectl with oc

- content/rs/clusters/optimize/optimization.md
- content/rs/references/cli-utilities/rladmin/tune.md
- content/rs/references/rest-api/objects/cluster_settings.md
- content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba.md
- [rladmin tune cluster](https://docs.redis.com/staging/DOC-2225/rs/references/cli-utilities/rladmin/tune/)
- [REST API cluster settings object](https://docs.redis.com/staging/DOC-2225/rs/references/rest-api/objects/cluster_settings/)
- [Cluster environment optimization](https://docs.redis.com/staging/DOC-2225/rs/clusters/optimize/optimization/)
- [Deprecation notice](https://docs.redis.com/staging/DOC-2225/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba/#deprecations)
> RS: Deprecated watchdog_profile & added failure_detection_sensitivity

- content/rc/security/access-control/saml-sso/saml-integration-google.md
Staging link: https://docs.redis.com/staging/DOC-2234/rc/security/access-control/saml-sso/saml-integration-google/
> DOC-2234: URLs for ACS and Entity ID interchanged/incorrect for SAML SSO configuration

- content/ri/using-redisinsight/api.md
api.md missing `username` info in ACL authentication, which is mandatory for Redis Cluster.
I've confirm I can add Redis Cluster (ElastiCache ACL & MemoryDB) with following JSON.
```json
{ "name": "Cache","connectionType": "CLUSTER","seedNodes": [{ "host": "clustercfg.CLUSTER_NAME.xxxxxx.apne1.cache.amazonaws.com","port": 6379 }], "username": "USERNAME", "password": "PASSWORD","tls": { "useTls": true, "clientAuth": false } }
```
> Update api.md to include username for Redis Cluster

- content/embeds/supported-platforms-embed.md
- content/rs/clusters/optimize/optimization.md
- content/rs/networking/port-configurations.md
- content/rs/references/cli-utilities/rladmin/cluster/config.md
- content/rs/references/cli-utilities/rladmin/tune.md
- content/rs/references/rest-api/objects/cluster_settings.md
- content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
- content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
- content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba.md
- [Change envoy ports](https://docs.redis.com/staging/release-rs-diablo-may/rs/networking/port-configurations/#change-the-envoy--ports)
- [rladmin cluster config](https://docs.redis.com/staging/release-rs-diablo-may/rs/references/cli-utilities/rladmin/cluster/config/)
- [Query parameters for optimize shard placement REST API request](https://docs.redis.com/staging/release-rs-diablo-may/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement/#get-request)
- [rladmin tune cluster](https://docs.redis.com/staging/release-rs-diablo-may/rs/references/cli-utilities/rladmin/tune/)
- [REST API cluster settings object](https://docs.redis.com/staging/release-rs-diablo-may/rs/references/rest-api/objects/cluster_settings/)
- [Cluster environment …
> DOC-2164 RS 6.4.2 May release notes and docs

- content/_index.md
- content/glossary/_index.md
Since Hugo [v0.111.0](https://github.com/gohugoio/hugo/releases/tag/v0.111.0), errors are thrown on unclosed tags.
> Throw an error when shortcode is expected to be closed https://github.com/gohugoio/hugo/commit/7d78a498e19c2331a325fa43dd46f4da2b0443a6 @bep https://github.com/gohugoio/hugo/issues/10675
This PR fixes the unclosed tags reported on build.
> Close unclosed shortcode tags

- content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
Added RedisGears 1.2.6 release notes, sourced from the [RedisGears repo release notes](https://github.com/RedisGears/RedisGears/releases/tag/v1.2.6).
> Added RedisGears 1.2.6 release notes

- content/kubernetes/re-clusters/upgrade-redis-cluster.md
- content/kubernetes/release-notes/6-2-18-releases/_index.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
- content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
- content/kubernetes/release-notes/6-4-2-releases/_index.md
- content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
Jira: DOC-2323
Added warning to upgrade article and all release notes for versions 6.2.18 and later. 
Staged previews: 
[Upgrade a Redis Enterprise Cluster (REC)](https://docs.redis.com/staging/DOC-2323/kubernetes/re-clusters/upgrade-redis-cluster/)
[6.4.2 release notes](https://docs.redis.com/staging/DOC-2323/kubernetes/release-notes/6-4-2-releases/)
[6.2.18 release notes](https://docs.redis.com/staging/DOC-2323/kubernetes/release-notes/6-2-18-releases/)
> DOC-2323 RED-102100 warning for SCC upgrade bug

- content/kubernetes/re-clusters/delete_custom_resources.md
We received a report of a possible typo in this REDB deletion warning.
Here's a [staged preview](https://docs.redis.com/staging/typo-fix/kubernetes/re-clusters/delete_custom_resources/#troubleshoot-redb-deletion) that includes the suggested fix.
> k8s: Fix possible typo for REDB deletion warning

- content/rc/api/examples/back-up-and-import-data.md
- content/rc/databases/back-up-data.md
- content/rs/databases/import-export/schedule-backups.md
- content/rs/references/cli-utilities/rladmin/tune.md
- content/rs/references/rest-api/objects/cluster_settings.md
- Cloud
- [Back up a database](https://docs.redis.com/staging/DOC-2235/rc/databases/back-up-data/)
- [Database backup REST API example](https://docs.redis.com/staging/DOC-2235/rc/api/examples/back-up-and-import-data/)
- Software
- [Schedule periodic backups](https://docs.redis.com/staging/DOC-2235/rs/databases/import-export/schedule-backups/)
- [rladmin tune cluster reference](https://docs.redis.com/staging/DOC-2235/rs/references/cli-utilities/rladmin/tune/#tune-cluster)
- [Cluster settings REST API object refeference](https://docs.redis.com/staging/DOC-2235/rs/references/rest-api/objects/cluster_settings/)
> Max simultaneous backups defaults to 4

- content/embeds/r7.2-breaking-changes.md
Staging link: https://docs.redis.com/staging/DOC-2381/rc/changelog/june-2023/
> DOC-2381: Remove 6.4 references from breaking changes

- content/kubernetes/active-active/_index.md
- content/kubernetes/active-active/create-reaadb.md
- content/kubernetes/active-active/prepare-clusters.md
- content/kubernetes/networking/routes.md
These changes aim to clarify what the user needs to do before they start the AA creation process and lists out the variables they'll need defined. Hopefully this will make the docs easier to use. 
Jira: DOC-2140
- https://docs.redis.com/staging/DOC-2140/kubernetes/active-active/prepare-clusters/
- https://docs.redis.com/staging/DOC-2140/kubernetes/active-active/create-reaadb/
> K8s: AA install prereq checklist

- content/kubernetes/re-clusters/upgrade-redis-cluster.md
- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/6-2-18-releases/_index.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
- content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
- content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
- content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
- content/kubernetes/release-notes/6-4-2-releases/_index.md
- content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
- content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
- content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
- content/kubernetes/release-notes/k8s-6-2-10-45-2022-07.md
- content/kubernetes/release-notes/k8s-6-2-12-1.md
- content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
- content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
- content/kubernetes/release-notes/k8s-6-2-8-15-2022-01.md
- content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Pages updated: Supported distributions, Upgrade Redis Enterprise clusters, all 6.4.2 release notes, all 6.2.18 release notes, 6.2.12 release notes.
Preview: 
- https://docs.redis.com/staging/RED-102241/kubernetes/reference/supported_k8s_distributions/
- https://docs.redis.com/staging/RED-102241/kubernetes/re-clusters/upgrade-redis-cluster/#before-upgrading/
- https://docs.redis.com/staging/RED-102241/content/kubernetes/release-notes/6-4-2-releases/6-4-2-6/
- https://docs.redis.com/staging/RED-102241/content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4/
- https://docs.redis.com/staging/RED-102241/content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41/
- https://docs.redis.com/staging/RED-102241/content/kubernetes/release-notes/k8s-6-2-12-1/
> K8s: Red-102241 Upgrade path info

- content/rs/references/cli-utilities/redis-cli/_index.md
[Staged preview](https://docs.redis.com/staging/DOC-1760/rs/references/cli-utilities/redis-cli/#connect-over-tls)
> redis-cli TLS connections

- content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
[Staged preview](https://docs.redis.com/staging/release-rs-diablo-july/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94/)
> RS 6.4.2 July maintenance release notes

- content/rdi/reference/data-transformation-block-types/redis_write.md
As per [RDSC-1404](https://redislabs.atlassian.net/browse/RDSC-1404):
* modfied the nesting job definition in redis.write block
* Details are in the [corresponding PR](https://github.com/RedisLabs/redis-data-integration/pull/895)
[RDSC-1404]: https://redislabs.atlassian.net/browse/RDSC-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RDSC-1404: key-name-for-nesting

- content/rs/references/cli-utilities/rladmin/tune.md
- content/rs/references/compatibility/resp.md
- content/rs/references/rest-api/objects/bdb/_index.md
- content/rs/references/rest-api/objects/cluster_settings.md
- [RESP3 compatibility](https://docs.redis.com/staging/DOC-2585/rs/references/compatibility/resp/)
- [rladmin tune cluster](https://docs.redis.com/staging/DOC-2585/rs/references/cli-utilities/rladmin/tune/)
- [Cluster settings REST API object](https://docs.redis.com/staging/DOC-2585/rs/references/rest-api/objects/cluster_settings/)
- [BDB REST API object](https://docs.redis.com/staging/DOC-2585/rs/references/rest-api/objects/bdb/)
> RS: RESP3 support - policy flag

- content/rs/clusters/logging/log-security.md
[Staged preview](https://docs.redis.com/staging/DOC-2593/rs/clusters/logging/log-security/)
> RS: Update log rotation

- content/embeds/k8s-admission-webhook-cert.md
- content/kubernetes/deployment/openshift/openshift-cli.md
Jira: DOC-2582
Staged preview: The same embedded block exists on these pages: 
https://docs.redis.com/staging/DOC-2582/kubernetes/deployment/quick-start/
https://docs.redis.com/staging/DOC-2582/kubernetes/deployment/openshift/openshift-cli/
https://docs.redis.com/staging/DOC-2582/kubernetes/re-clusters/upgrade-redis-cluster/
> K8s: correct webhook steps

- layouts/shortcodes/table-scrollable.html
Found a bug where a phantom scrollbar appeared below tables on small displays. Try viewing the tables on the following page with different window sizes to test.
[Staged preview](https://docs.redis.com/staging/fix-scrollable-table/kubernetes/reference/supported_k8s_distributions/)
> Fix scroll bar bug in scrollable table shortcode

- content/rs/release-notes/rs-7-2-4-releases/_index.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
- [7.2.4 release notes index page](https://docs.redis.com/staging/rrelledge-patch-2/rs/release-notes/rs-7-2-4-releases/#cluster-recovery-with-manually-uploaded-modules)
- [7.2.4-52 release notes](https://docs.redis.com/staging/rrelledge-patch-2/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52/#cluster-recovery-with-manually-uploaded-modules)
> RS: Cluster recovery with manually uploaded modules (7.2.4 release notes)

- content/rc/databases/back-up-data.md
- content/rc/databases/import-data.md
Staging link: 
https://docs.redis.com/staging/DOC-1896/rc/databases/back-up-data/#aws-s3
https://docs.redis.com/staging/DOC-1896/rc/databases/import-data/#via-aws-s3
> DOC-1896: RC: Update Redis Cloud docs for S3 backup that SSE-KMS is supported and move to bucket policy

- content/rs/references/rest-api/objects/bdb/_index.md
[Staged preview](https://docs.redis.com/staging/DOC-2502/rs/references/rest-api/objects/bdb/)
> RS REST API: Add missing BDB object attribute for replica buffer

- content/rs/references/rest-api/_index.md
DOC-2688
[Staged preview](https://docs.redis.com/staging/DOC-2688/rs/references/rest-api/#certificates)
> RS: Remove tutorial mention from REST API index's certificates section

- content/kubernetes/re-clusters/upgrade-redis-cluster.md
Staging link: http://docs.reds.com/staging/DOC-2748/kubernetes/re-clusters/upgrade-redis-cluster/#reapply-the-scc
> DOC-2478: K8s: Backslash in reapplying security context command

- content/rs/databases/configure/db-defaults.md
- content/rs/databases/configure/replica-ha.md
- content/rs/security/internode-encryption.md
- [Configure database defaults](https://docs.redis.com/staging/DOC-2630/rs/databases/configure/db-defaults/)
- [Replica HA](https://docs.redis.com/staging/DOC-2630/rs/databases/configure/replica-ha/#configure-cluster-policy-for-replica-ha)
- [Internode encryption](https://docs.redis.com/staging/DOC-2630/rs/security/internode-encryption/#change-cluster-policy)
> RS: Configure DB defaults in new UI

- content/rs/databases/durability-ha/clustering.md
DOC-2690
[Staged preview](https://docs.redis.com/staging/DOC-2690/rs/databases/durability-ha/clustering/#standard-hashing-policy)
> RS: Standard hashing policy behaves differently from OSS Redis for multiple hash tags

- layouts/partials/flex/body-beforecontent.html
DOC-2707
To test, click on the version selector and compare the URLs/links between the [staged preview](https://docs.redis.com/staging/DOC-2707/rs/security/) and [latest](https://docs.redis.com/latest/rs/security/).
When you click on a different version in the staged preview, you should be redirected to a different version of the same page instead of being redirected to the main [Redis Enterprise Software page](https://docs.redis.com/latest/rs/).
> Fixed version selector to keep the full URL path instead of trimming it to the base path

- layouts/partials/flex/body-beforecontent.html
[DOC-2707](https://redislabs.atlassian.net/browse/DOC-2707)
To test, click on the version selector and compare the URLs/links between the [staged preview](https://docs.redis.com/staging/DOC-2707-6.0/rs/security/) and [v6.0](https://docs.redis.com/6.0/rs/security/).
When you click on a different version in the staged preview, you should be redirected to a different version of the same page instead of being redirected to the main [Redis Enterprise Software page](https://docs.redis.com/latest/rs/).
[DOC-2707]: https://redislabs.atlassian.net/browse/DOC-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 6.0: Fixed version selector to keep the full URL path instead of trimming it

- layouts/partials/flex/body-beforecontent.html
[DOC-2707](https://redislabs.atlassian.net/browse/DOC-2707)
To test, click on the version selector and compare the URLs/links between the [staged preview](https://docs.redis.com/staging/DOC-2707-6.2/rs/security/) and [v6.2](https://docs.redis.com/6.2/rs/security/).
When you click on a different version in the staged preview, you should be redirected to a different version of the same page instead of being redirected to the main [Redis Enterprise Software page](https://docs.redis.com/latest/rs/).
[DOC-2707]: https://redislabs.atlassian.net/browse/DOC-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 6.2: Fixed version selector to keep the full URL path instead of trimming it

- layouts/partials/flex/body-beforecontent.html
[DOC-2707](https://redislabs.atlassian.net/browse/DOC-2707)
To test, click on the version selector and compare the URLs/links between the [staged preview](https://docs.redis.com/staging/DOC-2707-6.4/rs/security/) and [v6.4](https://docs.redis.com/6.4/rs/security/).
When you click on a different version in the staged preview, you should be redirected to a different version of the same page instead of being redirected to the main [Redis Enterprise Software page](https://docs.redis.com/latest/rs/).
[DOC-2707]: https://redislabs.atlassian.net/browse/DOC-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 6.4: Fixed version selector to keep the full URL path instead of trimming it

- layouts/partials/flex/body-beforecontent.html
[DOC-2707](https://redislabs.atlassian.net/browse/DOC-2707)
To test, click on the version selector and compare the URLs/links between the [staged preview](https://docs.redis.com/staging/DOC-2707-rdi-preview/rdi/quickstart/ingest-guide/) and [rdi-preview](https://docs.redis.com/rdi-preview/rdi/quickstart/ingest-guide/).
When you click on a different version in the staged preview, you should be redirected to a different version of the same page instead of being redirected to the main RDI page.
[DOC-2707]: https://redislabs.atlassian.net/browse/DOC-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> rdi-preview: Fixed version selector to keep the full URL path instead of trimming it

- content/rs/databases/configure/db-defaults.md
- content/rs/references/cli-utilities/rladmin/tune.md
DOC-2944 DOC-3140
- Configure DB defaults
- [Shard placement](https://docs.redis.com/staging/DOC-2944/rs/databases/configure/db-defaults/#shard-placement)
- [Proxy policies](https://docs.redis.com/staging/DOC-2944/rs/databases/configure/db-defaults/#proxy-policies)
- [rladmin tune cluster](https://docs.redis.com/staging/DOC-2944/rs/references/cli-utilities/rladmin/tune/#tune-cluster)
> RS: DB defaults for shard placement and proxy policies

- content/rs/security/certificates/create-certificates.md
[DOC-3093](https://redislabs.atlassian.net/browse/DOC-3093)
[Staged preview](https://docs.redis.com/staging/DOC-3093-v6.4/rs/security/certificates/create-certificates/#create-certificates)
Note: I will open similar PRs for 7.2 and 6.2 docs.
[DOC-3093]: https://redislabs.atlassian.net/browse/DOC-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RS 6.4: Added example to sign private key with CA

- content/rs/databases/import-export/flush.md
https://redislabs.atlassian.net/browse/DOC-3027
Preview: https://docs.redis.com/staging/DOC-3027/rs/databases/import-export/flush/
> DOC-3027 Updated example to use the default recommended port number.

- content/kubernetes/security/manage-rec-credentials.md
`base64 --decodexc` is invalid (no such flag).
The correct flag is `base64 --decode`.
> Fix `base64 --decode` example

- content/rs/databases/active-active/create.md
DOC-3178
[Staged preview](https://docs.redis.com/staging/DOC-3178/rs/databases/active-active/create/)
> RS: Snapshot persistence is not supported for Active-Active DBs

- content/kubernetes/reference/supported_k8s_distributions.md
- content/kubernetes/release-notes/7-2-4-releases/7-2-4-12.md
Jira: DOC-3224
Preview: https://docs.redis.com/staging/DOC-3224/kubernetes/reference/supported_k8s_distributions/
https://docs.redis.com/staging/DOC-3224/kubernetes/release-notes/7-2-4-releases/7-2-4-12/
> K8s: update distro to remove unsupported 1.28

- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
DOC-3283
- [7.2.4-92 (November 2023)](https://docs.redis.com/staging/DOC-3283/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92/#security)
- [7.2.4-72 (October 2023) ](https://docs.redis.com/staging/DOC-3283/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72/#security)
- [7.2.4-64 (September 2023) ](https://docs.redis.com/staging/DOC-3283/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64/#security)
> RS: Add CVE-2023-41056 to 7.2.4 maintenance release notes

- content/rs/references/cli-utilities/rladmin/status.md
- content/rs/references/rest-api/objects/bdb/_index.md
- content/rs/references/rest-api/requests/bdbs/upgrade.md
- content/stack/install/_index.md
- content/stack/install/add-module-to-cluster.md
- content/stack/install/add-module-to-database.md
DOC-3274
- [Install and upgrade modules index page](https://docs.redis.com/staging/DOC-3274/stack/install/)
- [Install a module on a cluster](https://docs.redis.com/staging/DOC-3274/stack/install/add-module-to-cluster/)
- [rladmin status modules reference](https://docs.redis.com/staging/DOC-3274/rs/references/cli-utilities/rladmin/status/#status-modules) - example output now shows 2 sets of modules
- [Upgrade database REST API request parameters](https://docs.redis.com/staging/DOC-3274/rs/references/rest-api/requests/bdbs/upgrade/#request-body) - added `latest_with_modules` and `redis_version` request parameters
- [BDB REST API object reference](https://docs.redis.com/staging/DOC-3274/rs/references/rest-api/objects/bdb/) - marked `module_list`'s `module_id` and …
> RS: Bundle 2 Redis Stack feature sets

- content/stack/bloom/_index.md
Preview build is here: https://docs.redis.com/staging/DOC-3313/stack/bloom/ .
> DOC-3313: correcting link to Bloom filter quick start

- content/rs/installing-upgrading/upgrading/upgrade-database.md
DOC-3315
[Staged preview](https://docs.redis.com/staging/DOC-3315/rs/installing-upgrading/upgrading/upgrade-database/)
> RS: Bug fix to remove default_redis_version from upgrade DB doc

- content/rs/databases/recover.md
- content/rs/references/rest-api/objects/bdb/_index.md
- content/rs/references/rest-api/objects/cluster_settings.md
DOC-3300
DOC-3302
- [Configure automatic recovery](https://docs.redis.com/staging/DOC-3300/rs/databases/recover/#configure-automatic-recovery)
- [Cluster settings REST API object](https://docs.redis.com/staging/DOC-3300/rs/references/rest-api/objects/cluster_settings/)
- [BDB REST API object](https://docs.redis.com/staging/DOC-3300/rs/references/rest-api/objects/bdb/)
> RS: Database auto recovery

- content/rs/references/compatibility/commands/server.md
- content/rs/references/rest-api/requests/bdbs/replica_sources-alerts.md
- content/rs/references/rest-api/requests/modules/_index.md
DOC-3345
Staged preview:
- [Module commands](https://docs.redis.com/staging/DOC-3345/rs/references/compatibility/commands/server/#module-commands)
- [Monitoring commands](https://docs.redis.com/staging/DOC-3345/rs/references/compatibility/commands/server/#monitoring-commands)
- [GET /v1/bdbs/replica_sources/alerts response](https://docs.redis.com/staging/DOC-3345/rs/references/rest-api/requests/bdbs/replica_sources-alerts/#get-all-response)
- [POST /v1/modules](https://docs.redis.com/staging/DOC-3345/rs/references/rest-api/requests/modules/#post-module)
- [POST /v2/modules](https://docs.redis.com/staging/DOC-3345/rs/references/rest-api/requests/modules/#post-module-v2)
> RS: Fix broken relrefs and links in reference docs

- content/rc/cloud-integrations/prometheus-integration.md
Ticket: DOC-3368
Staging link: https://docs.redis.com/staging/DOC-3370/rc/cloud-integrations/prometheus-integration/
> RC: Wrong link in cloud Grafana documentation 

- content/rs/references/cli-utilities/rladmin/cluster/config.md
- content/rs/references/cli-utilities/rladmin/cluster/join.md
DOC-3245
- [rladmin cluster config](https://docs.redis.com/staging/DOC-3245/rs/references/cli-utilities/rladmin/cluster/config/)
- [rladmin cluster join ](https://docs.redis.com/staging/DOC-3245/rs/references/cli-utilities/rladmin/cluster/join/)
> RS: Fixed typo in rladmin cluster config/join command option cnm_http_port

- content/embeds/supported-platforms-embed.md
- content/rs/release-notes/rs-7-4-2-releases/_index.md
- content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
DOC-3365
- [Supported platforms](https://docs.redis.com/staging/DOC-3365/rs/references/supported-platforms/#table-note-2)
- [7.4.2 release notes index page](https://docs.redis.com/staging/DOC-3365/rs/release-notes/rs-7-4-2-releases/#table-note-2)
- [7.4.2-54 release notes](https://docs.redis.com/staging/DOC-3365/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54/#table-note-2)
> RS: Removed OpenSSL 1.0.2 requirement for RS 7.4 on RHEL

- content/rs/references/cli-utilities/rladmin/cluster/debug_info.md
This is not a valid option anymore (sanitized by default)
> Remove `sanitized` from rladmin documentation

- content/rs/networking/port-configurations.md
DOC-3308
[Staged preview](https://docs.redis.com/staging/DOC-3308/rs/networking/port-configurations/#ports-and-port-ranges-used-by-redis-enterprise-software)
> RS: Add port 10050 to reserved ports

- content/rs/release-notes/rs-7-2-4-releases/_index.md
- content/rs/release-notes/rs-7-4-2-releases/_index.md
- content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
Opened a new PR to replace https://github.com/RedisLabs/redislabs-docs/pull/3166 because it accidentally included work-in-progress maintenance release notes. This way, we can merge these changes without reverting the commits or being blocked by the maintenance release.
- [7.4.2 index page](https://docs.redis.com/staging/rs-fuji-rn-patch/rs/release-notes/rs-7-4-2-releases/#cannot-create-redis-v6x-active-active-databases-with-modules)
- [7.4.2-54 release notes](https://docs.redis.com/staging/rs-fuji-rn-patch/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54/#cannot-create-redis-v6x-active-active-databases-with-modules)
- [7.2.4 index page](https://docs.redis.com/staging/rs-fuji-rn-patch/rs/release-notes/rs-7-2-4-releases/#cannot-create-redis-v6x-active-active-databases-with-mod …
> RS: Add Redis v6.x A-A modules limitation to Fuji release notes

- content/rs/clusters/monitoring/prometheus-metrics-definitions.md
DOC-3375
[Staged preview](https://docs.redis.com/staging/DOC-3375/rs/clusters/monitoring/prometheus-metrics-definitions/#node-metrics)
> RS: node_avg_latency should be in milliseconds

- content/rc/databases/create-database.md
Ticket: DOC-3492
Staging link: https://docs.redis.com/staging/DOC-3492/rc/databases/create-database#throughput
> RC: Throughput section changes

- content/rc/security/private-service-connect.md
Ticket: DOC-3526
Staging link: https://docs.redis.com/staging/DOC-3526/rc/security/private-service-connect/
> RC: Enabling private service connection causes issues with the public endpoint

- content/embeds/rc-vpc-peering-cidr-list.md
- content/rc/security/aws-transit-gateway.md
- content/rc/security/cidr-whitelist.md
- content/rc/security/vpc-peering.md
Ticket: DOC-3418
Staging links:
https://docs.redis.com/staging/DOC-3418/rc/security/cidr-whitelist/#define-cidr-allow-list
https://docs.redis.com/staging/DOC-3418/rc/security/aws-transit-gateway/#update-route-tables
https://docs.redis.com/staging/DOC-3418/rc/security/vpc-peering/
> RC: CIDR whitelist and connectivity options fix

- content/rs/references/rest-api/requests/bdbs/syncer_state/_index.md
- content/rs/references/rest-api/requests/bdbs/syncer_state/crdt.md
- content/rs/references/rest-api/requests/bdbs/syncer_state/replica.md
DOC-3270
- [/v1/bdbs/{uid}/syncer_state](https://docs.redis.com/staging/DOC-3270/rs/references/rest-api/requests/bdbs/syncer_state/)
- [/v1/bdbs/{uid}/syncer_state/crdt](https://docs.redis.com/staging/DOC-3270/rs/references/rest-api/requests/bdbs/syncer_state/crdt/)
- [/v1/bdbs/{uid}/syncer_state/replica](https://docs.redis.com/staging/DOC-3270/rs/references/rest-api/requests/bdbs/syncer_state/replica/)
> RS: syncer_state REST API references

- content/rs/databases/active-active/create.md
- content/rs/databases/active-active/manage.md
- content/rs/databases/active-active/planning.md
DOC-3268
- [Considerations for planning Active-Active databases](https://docs.redis.com/staging/DOC-3268/rs/databases/active-active/planning/#participating-clusters)
- [Create an Active-Active database](https://docs.redis.com/staging/DOC-3268/rs/databases/active-active/create/#create-an-active-active-database) - step 7b
- [Add participating clusters](https://docs.redis.com/staging/DOC-3268/rs/databases/active-active/manage/#add-participating-clusters)
> RS: Cannot mix RAM-only and flash clusters in Active-Active config

- content/rs/clusters/cluster-recovery.md
DOC-2950
[Staged preview](https://docs.redis.com/staging/DOC-2950/rs/clusters/cluster-recovery/)
> RS: Recover cluster - removed incorrect rladmin cluster join syntax, removed expands, added reference links

- content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
- content/rs/release-notes/rs-7-2-4-releases/_index.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
- content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
- content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
DOC-3543
The supported platforms snapshot disclaimer from the most recent Redis Enterprise Software release now appears on all release notes that have a supported platforms snapshot:
- [All 7.4.2 release notes](https://docs.redis.com/staging/DOC-3543/rs/release-notes/rs-7-4-2-releases/)
- [All 7.2.4 release notes](https://docs.redis.com/staging/DOC-3543/rs/release-notes/rs-7-2-4-releases/)
- [6.4.2-103 release notes](https://docs.redis.com/staging/DOC-3543/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103/)
> RS: Add supported platforms snapshot disclaimer to previous RS release notes
